package pseudo

import (
	"encoding/hex"
	"errors"
	"strings"

	"github.com/LeJamon/go-xrpl/internal/tx"
	"github.com/LeJamon/go-xrpl/internal/tx/ter"
	"github.com/LeJamon/go-xrpl/keylet"
)

var (
	ErrAmendmentMissing = ter.Errorf(ter.TemMALFORMED, "EnableAmendment missing amendment hash")
)

// EnableAmendment is a pseudo-transaction that enables or tracks amendment voting.
// This transaction is only valid when generated by consensus (validators).
// Reference: rippled Change.cpp applyAmendment()
type EnableAmendment struct {
	tx.BaseTx

	// Amendment is the hash of the amendment being voted on
	Amendment string `json:"Amendment,omitempty" xrpl:"Amendment,omitempty"`

	// LedgerSequence is the ledger sequence for this amendment change
	LedgerSequence *uint32 `json:"LedgerSequence,omitempty" xrpl:"LedgerSequence,omitempty"`
}

// Flags for EnableAmendment pseudo-transactions
const (
	// tfGotMajority indicates the amendment gained majority support
	tfGotMajority uint32 = 0x00010000

	// tfLostMajority indicates the amendment lost majority support
	tfLostMajority uint32 = 0x00020000
)

func (e *EnableAmendment) TxType() tx.Type {
	return tx.TypeAmendment
}

// Reference: rippled Change.cpp preflight()
func (e *EnableAmendment) Validate() error {
	// Pseudo-transaction: minimal validation
	if e.Amendment == "" {
		return ErrAmendmentMissing
	}
	return nil
}

func (e *EnableAmendment) Flatten() (map[string]any, error) {
	return tx.ReflectFlatten(e)
}

// IsPseudoTransaction returns true as EnableAmendment is a pseudo-transaction
func (e *EnableAmendment) IsPseudoTransaction() bool {
	return true
}

// Reference: rippled Change.cpp applyAmendment() lines 248-345
func (e *EnableAmendment) Apply(ctx *tx.ApplyContext) ter.Result {
	// Reference: rippled line 251: uint256 amendment(ctx_.tx.getFieldH256(sfAmendment))
	amendmentHash, err := parseAmendmentHash(e.Amendment)
	if err != nil {
		ctx.Log.Error("enable amendment: failed to parse amendment hash", "amendment", e.Amendment)
		return ter.TefINTERNAL
	}

	// Get or create the Amendments SLE
	// Reference: rippled lines 253-261
	k := keylet.Amendments()
	var sle *AmendmentsSLE

	data, readErr := ctx.View.Read(k)
	if readErr != nil || data == nil {
		// Create new empty Amendments SLE
		sle = &AmendmentsSLE{}
	} else {
		sle, err = ParseAmendmentsSLE(data)
		if err != nil {
			return ter.TefINTERNAL
		}
	}

	isNew := data == nil || readErr != nil

	// Check if amendment is already enabled
	// Reference: rippled lines 265-267
	if sle.ContainsAmendment(amendmentHash) {
		return ter.TefALREADY
	}

	// Parse flags
	// Reference: rippled lines 269-275
	var flags uint32
	if e.Common.Flags != nil {
		flags = *e.Common.Flags
	}
	gotMajority := (flags & tfGotMajority) != 0
	lostMajority := (flags & tfLostMajority) != 0

	if gotMajority && lostMajority {
		return ter.TemINVALID_FLAG
	}

	// Build new majorities list, filtering out the target amendment
	// Reference: rippled lines 277-298
	newMajorities := make([]MajorityEntry, 0, len(sle.Majorities))
	found := false

	for _, entry := range sle.Majorities {
		if entry.Amendment == amendmentHash {
			if gotMajority {
				// Already in majorities and we're trying to add again
				return ter.TefALREADY
			}
			found = true
			// Don't copy this entry (it's being removed for lostMajority,
			// or it will be removed for enable)
		} else {
			// Pass through other entries
			newMajorities = append(newMajorities, entry)
		}
	}

	// lostMajority but amendment wasn't in the majorities list
	// Reference: rippled lines 300-301
	if !found && lostMajority {
		return ter.TefALREADY
	}

	if found && lostMajority {
		ctx.Log.Debug("enable amendment: lost majority",
			"amendment", e.Amendment,
		)
	}

	// Handle gotMajority: add new majority entry
	// Reference: rippled lines 303-317
	if gotMajority {
		ctx.Log.Debug("enable amendment: got majority",
			"amendment", e.Amendment,
		)
		newMajorities = append(newMajorities, MajorityEntry{
			Amendment: amendmentHash,
			CloseTime: ctx.Config.ParentCloseTime,
		})
	} else if !lostMajority {
		// No flags = enable the amendment
		// Reference: rippled lines 318-335
		ctx.Log.Info("enable amendment: amendment enabled",
			"amendment", e.Amendment,
		)
		sle.Amendments = append(sle.Amendments, amendmentHash)

		// The in-memory Table.enable() notification (Change.cpp:327)
		// and setAmendmentBlocked() on unsupported activation (Change.cpp:329-334)
		// are driven by the validated-ledger resync in the ledger service
		// (Table.DoValidatedLedger), not from the pseudo-tx — the
		// ledger SLE remains the single source of truth for enabled amendments.
	}

	// Reference: rippled lines 337-340
	sle.Majorities = newMajorities

	serialized, serErr := SerializeAmendmentsSLE(sle)
	if serErr != nil {
		return ter.TefINTERNAL
	}

	if isNew {
		if insertErr := ctx.View.Insert(k, serialized); insertErr != nil {
			return ter.TefINTERNAL
		}
	} else {
		if updateErr := ctx.View.Update(k, serialized); updateErr != nil {
			return ter.TefINTERNAL
		}
	}

	return ter.TesSUCCESS
}

// parseAmendmentHash parses a hex-encoded amendment hash string into [32]byte.
func parseAmendmentHash(hashStr string) ([32]byte, error) {
	var hash [32]byte
	b, err := hex.DecodeString(strings.TrimPrefix(hashStr, "0x"))
	if err != nil {
		return hash, err
	}
	if len(b) != 32 {
		return hash, errors.New("amendment hash must be 32 bytes")
	}
	copy(hash[:], b)
	return hash, nil
}
