package pseudo

import (
	"encoding/hex"
	"errors"
	"strings"

	"github.com/LeJamon/go-xrpl/amendment"
	"github.com/LeJamon/go-xrpl/internal/ledger/state"
	"github.com/LeJamon/go-xrpl/internal/tx"
	"github.com/LeJamon/go-xrpl/keylet"
	"github.com/LeJamon/go-xrpl/ledger/entry"
)

// fixTrustLinesToSelfIndexes are the two RippleState ledger entries that
// existed on mainnet whose LowLimit and HighLimit belong to the same account
// (a trust line to self). fixTrustLinesToSelf deletes them on activation.
// Reference: rippled Change.cpp activateTrustLinesToSelfFix (lines 233-239).
var fixTrustLinesToSelfIndexes = [...]string{
	"2F8F21EFCAFD7ACFB07D5BB04F0D2E18587820C7611305BB674A64EAB0FA71E1",
	"326035D5C0560A9DA8636545DD5A1B0DFCFF63E68D491B5522B767BB00564B1A",
}

var (
	ErrAmendmentMissing = tx.Errorf(tx.TemMALFORMED, "EnableAmendment missing amendment hash")
)

// EnableAmendment is a pseudo-transaction that enables or tracks amendment voting.
// This transaction is only valid when generated by consensus (validators).
// Reference: rippled Change.cpp applyAmendment()
type EnableAmendment struct {
	tx.BaseTx

	// Amendment is the hash of the amendment being voted on
	Amendment string `json:"Amendment,omitempty" xrpl:"Amendment,omitempty"`

	// LedgerSequence is the ledger sequence for this amendment change
	LedgerSequence *uint32 `json:"LedgerSequence,omitempty" xrpl:"LedgerSequence,omitempty"`
}

// Flags for EnableAmendment pseudo-transactions
const (
	// tfGotMajority indicates the amendment gained majority support
	tfGotMajority uint32 = 0x00010000

	// tfLostMajority indicates the amendment lost majority support
	tfLostMajority uint32 = 0x00020000
)

func (e *EnableAmendment) TxType() tx.Type {
	return tx.TypeAmendment
}

// Reference: rippled Change.cpp preflight()
func (e *EnableAmendment) Validate() error {
	// Pseudo-transaction: minimal validation
	if e.Amendment == "" {
		return ErrAmendmentMissing
	}
	return nil
}

func (e *EnableAmendment) Flatten() (map[string]any, error) {
	return tx.ReflectFlatten(e)
}

// IsPseudoTransaction returns true as EnableAmendment is a pseudo-transaction
func (e *EnableAmendment) IsPseudoTransaction() bool {
	return true
}

// Reference: rippled Change.cpp applyAmendment() lines 248-345
func (e *EnableAmendment) Apply(ctx *tx.ApplyContext) tx.Result {
	// Reference: rippled line 251: uint256 amendment(ctx_.tx.getFieldH256(sfAmendment))
	amendmentHash, err := parseAmendmentHash(e.Amendment)
	if err != nil {
		ctx.Log.Error("enable amendment: failed to parse amendment hash", "amendment", e.Amendment)
		return tx.TefINTERNAL
	}

	// Get or create the Amendments SLE
	// Reference: rippled lines 253-261
	k := keylet.Amendments()
	var sle *AmendmentsSLE

	data, readErr := ctx.View.Read(k)
	if readErr != nil || data == nil {
		// Create new empty Amendments SLE
		sle = &AmendmentsSLE{}
	} else {
		sle, err = ParseAmendmentsSLE(data)
		if err != nil {
			return tx.TefINTERNAL
		}
	}

	isNew := data == nil || readErr != nil

	// Check if amendment is already enabled
	// Reference: rippled lines 265-267
	if sle.ContainsAmendment(amendmentHash) {
		return tx.TefALREADY
	}

	// Parse flags
	// Reference: rippled lines 269-275
	var flags uint32
	if e.Common.Flags != nil {
		flags = *e.Common.Flags
	}
	gotMajority := (flags & tfGotMajority) != 0
	lostMajority := (flags & tfLostMajority) != 0

	if gotMajority && lostMajority {
		return tx.TemINVALID_FLAG
	}

	// Build new majorities list, filtering out the target amendment
	// Reference: rippled lines 277-298
	newMajorities := make([]MajorityEntry, 0, len(sle.Majorities))
	found := false

	for _, entry := range sle.Majorities {
		if entry.Amendment == amendmentHash {
			if gotMajority {
				// Already in majorities and we're trying to add again
				return tx.TefALREADY
			}
			found = true
			// Don't copy this entry (it's being removed for lostMajority,
			// or it will be removed for enable)
		} else {
			// Pass through other entries
			newMajorities = append(newMajorities, entry)
		}
	}

	// lostMajority but amendment wasn't in the majorities list
	// Reference: rippled lines 300-301
	if !found && lostMajority {
		return tx.TefALREADY
	}

	if found && lostMajority {
		ctx.Log.Debug("enable amendment: lost majority",
			"amendment", e.Amendment,
		)
	}

	// Handle gotMajority: add new majority entry
	// Reference: rippled lines 303-317
	if gotMajority {
		ctx.Log.Debug("enable amendment: got majority",
			"amendment", e.Amendment,
		)
		newMajorities = append(newMajorities, MajorityEntry{
			Amendment: amendmentHash,
			CloseTime: ctx.Config.ParentCloseTime,
		})
	} else if !lostMajority {
		// No flags = enable the amendment
		// Reference: rippled lines 318-335
		ctx.Log.Info("enable amendment: amendment enabled",
			"amendment", e.Amendment,
		)
		sle.Amendments = append(sle.Amendments, amendmentHash)

		// Reference: rippled Change.cpp:324-325 — fixTrustLinesToSelf runs a
		// one-off ledger migration when it activates.
		if amendmentHash == amendment.FeatureFixTrustLinesToSelf {
			activateTrustLinesToSelfFix(ctx)
		}

		// The in-memory AmendmentTable.enable() notification (Change.cpp:327)
		// and setAmendmentBlocked() on unsupported activation (Change.cpp:329-334)
		// are driven by the validated-ledger resync in the ledger service
		// (AmendmentTable.DoValidatedLedger), not from the pseudo-tx — the
		// ledger SLE remains the single source of truth for enabled amendments.
	}

	// Reference: rippled lines 337-340
	sle.Majorities = newMajorities

	serialized, serErr := SerializeAmendmentsSLE(sle)
	if serErr != nil {
		return tx.TefINTERNAL
	}

	if isNew {
		if insertErr := ctx.View.Insert(k, serialized); insertErr != nil {
			return tx.TefINTERNAL
		}
	} else {
		if updateErr := ctx.View.Update(k, serialized); updateErr != nil {
			return tx.TefINTERNAL
		}
	}

	return tx.TesSUCCESS
}

// activateTrustLinesToSelfFix removes the known trust-lines-to-self when the
// fixTrustLinesToSelf amendment activates. It is best-effort and never fails
// the enable: a missing, wrong-typed, or non-self entry is skipped, mirroring
// rippled's removeTrustLineToSelf returning success in those cases.
// Reference: rippled Change.cpp:166-246.
func activateTrustLinesToSelfFix(ctx *tx.ApplyContext) {
	for _, indexHex := range fixTrustLinesToSelfIndexes {
		index, err := parseAmendmentHash(indexHex)
		if err != nil {
			continue
		}
		k := keylet.Keylet{Key: index}

		data, readErr := ctx.View.Read(k)
		if readErr != nil || data == nil {
			continue // missing entry -> skip
		}
		if typeCode, typeErr := state.GetLedgerEntryType(data); typeErr != nil || typeCode != uint16(entry.TypeRippleState) {
			continue // not a trust line -> skip
		}
		rs, parseErr := state.ParseRippleState(data)
		if parseErr != nil {
			continue
		}
		// Only a genuine trust line to self: rippled treats the entry as such only
		// when sfLowLimit == sfHighLimit as full STAmounts — currency, issuer, AND
		// value all equal (Change.cpp:187-194 / STAmount::operator==).
		if rs.LowLimit.Issuer != rs.HighLimit.Issuer ||
			rs.LowLimit.Currency != rs.HighLimit.Currency ||
			rs.LowLimit.Value() != rs.HighLimit.Value() {
			continue
		}
		lowID, lowErr := state.DecodeAccountID(rs.LowLimit.Issuer)
		highID, highErr := state.DecodeAccountID(rs.HighLimit.Issuer)
		if lowErr != nil || highErr != nil {
			continue
		}

		// Remove from both owner directories first. Rippled aborts the migration
		// if either dirRemove fails (Change.cpp:196-212); lacking an all-or-nothing
		// sandbox, we skip the entry on failure rather than leave it half-removed.
		if _, derr := state.DirRemove(ctx.View, keylet.OwnerDir(lowID), rs.LowNode, index, false); derr != nil {
			ctx.Log.Warn("fixTrustLinesToSelf: low owner-dir remove failed; skipping", "index", indexHex, "err", derr)
			continue
		}
		if _, derr := state.DirRemove(ctx.View, keylet.OwnerDir(highID), rs.HighNode, index, false); derr != nil {
			ctx.Log.Warn("fixTrustLinesToSelf: high owner-dir remove failed; skipping", "index", indexHex, "err", derr)
			continue
		}

		// Release the reserve held by each side that paid it.
		// Reference: rippled Change.cpp:214-220.
		if rs.Flags&state.LsfLowReserve != 0 {
			_ = tx.AdjustOwnerCount(ctx.View, lowID, -1)
		}
		if rs.Flags&state.LsfHighReserve != 0 {
			_ = tx.AdjustOwnerCount(ctx.View, highID, -1)
		}

		if eraseErr := ctx.View.Erase(k); eraseErr != nil {
			ctx.Log.Warn("fixTrustLinesToSelf: failed to erase trust line to self", "index", indexHex)
			continue
		}
		ctx.Log.Info("fixTrustLinesToSelf: removed trust line to self", "index", indexHex)
	}
}

// parseAmendmentHash parses a hex-encoded amendment hash string into [32]byte.
func parseAmendmentHash(hashStr string) ([32]byte, error) {
	var hash [32]byte
	b, err := hex.DecodeString(strings.TrimPrefix(hashStr, "0x"))
	if err != nil {
		return hash, err
	}
	if len(b) != 32 {
		return hash, errors.New("amendment hash must be 32 bytes")
	}
	copy(hash[:], b)
	return hash, nil
}
