package pseudo

import (
	"errors"
	"strconv"

	"github.com/LeJamon/goXRPLd/internal/tx"

	"github.com/LeJamon/goXRPLd/internal/ledger/state"
	"github.com/LeJamon/goXRPLd/keylet"
)

// SetFee errors matching rippled Change.cpp:43-385.
var (
	ErrSetFeeBadSrcAccount = tx.Errorf(tx.TemBAD_SRC_ACCOUNT, "SetFee must have zero account")
	ErrSetFeeBadFee        = tx.Errorf(tx.TemBAD_FEE, "SetFee must have zero fee")
	ErrSetFeeBadSignature  = tx.Errorf(tx.TemBAD_SIGNATURE, "SetFee must not have signature")
	ErrSetFeeBadSequence   = tx.Errorf(tx.TemBAD_SEQUENCE, "SetFee must have zero sequence")
	ErrSetFeeMalformed     = tx.Errorf(tx.TemMALFORMED, "SetFee has invalid fields")
)

// SetFee is a pseudo-transaction that updates network fee settings.
// This transaction is only valid when generated by consensus (validators).
// Reference: rippled Change.cpp applyFee()
type SetFee struct {
	tx.BaseTx

	// Legacy fields (pre-XRPFees amendment). XRPL JSON convention serializes
	// UInt64 as a hex string; sfBaseFee is decoded as a uint64.
	BaseFee string `json:"BaseFee,omitempty" xrpl:"BaseFee,omitempty"`

	// ReferenceFeeUnits is the reference fee units (typically 10)
	ReferenceFeeUnits *uint32 `json:"ReferenceFeeUnits,omitempty" xrpl:"ReferenceFeeUnits,omitempty"`

	// ReserveBase is the account reserve in drops
	ReserveBase *uint32 `json:"ReserveBase,omitempty" xrpl:"ReserveBase,omitempty"`

	// ReserveIncrement is the owner reserve increment in drops
	ReserveIncrement *uint32 `json:"ReserveIncrement,omitempty" xrpl:"ReserveIncrement,omitempty"`

	// Modern fields (XRPFees amendment)
	// BaseFeeDrops is the base fee in drops
	BaseFeeDrops string `json:"BaseFeeDrops,omitempty" xrpl:"BaseFeeDrops,omitempty"`

	// ReserveBaseDrops is the account reserve in drops
	ReserveBaseDrops string `json:"ReserveBaseDrops,omitempty" xrpl:"ReserveBaseDrops,omitempty"`

	// ReserveIncrementDrops is the owner reserve increment in drops
	ReserveIncrementDrops string `json:"ReserveIncrementDrops,omitempty" xrpl:"ReserveIncrementDrops,omitempty"`

	// LedgerSequence is the ledger sequence for this fee change
	LedgerSequence *uint32 `json:"LedgerSequence,omitempty" xrpl:"LedgerSequence,omitempty"`
}

// NewSetFee creates a new SetFee pseudo-transaction with the canonical
// zero account and the rippled-default common fields stamped via
// applyPseudoTxDefaults (Fee=0, Sequence=0, SigningPubKey="").
func NewSetFee() *SetFee {
	s := &SetFee{
		BaseTx: *tx.NewBaseTx(tx.TypeFee, ZeroAccount),
	}
	applyPseudoTxDefaults(&s.Common)
	return s
}

func (s *SetFee) TxType() tx.Type {
	return tx.TypeFee
}

// Validate runs the per-tx-type structural checks. Pseudo-transactions
// bypass the engine's preflight pipeline (applyPseudoTransaction calls
// Apply() directly), so Apply() invokes preflight/preclaim before the
// state mutation step instead.
func (s *SetFee) Validate() error {
	hasLegacy := s.BaseFee != "" || s.ReferenceFeeUnits != nil ||
		s.ReserveBase != nil || s.ReserveIncrement != nil
	hasModern := s.BaseFeeDrops != "" || s.ReserveBaseDrops != "" ||
		s.ReserveIncrementDrops != ""

	if !hasLegacy && !hasModern {
		return ErrSetFeeMalformed
	}

	return nil
}

func (s *SetFee) Flatten() (map[string]any, error) {
	return tx.ReflectFlatten(s)
}

// IsPseudoTransaction returns true as SetFee is a pseudo-transaction
func (s *SetFee) IsPseudoTransaction() bool {
	return true
}

// preflight mirrors rippled Change::preflight() (Change.cpp:36-80) for
// the common-field surface that applies to every Change tx: zero
// account, zero native fee, empty signing material, zero sequence /
// no PreviousTxnID.
func (s *SetFee) preflight() tx.Result {
	if s.Common.Account != ZeroAccount {
		return tx.TemBAD_SRC_ACCOUNT
	}
	if s.Common.Fee != "" && s.Common.Fee != "0" {
		return tx.TemBAD_FEE
	}
	if s.Common.SigningPubKey != "" || s.Common.TxnSignature != "" ||
		len(s.Common.Signers) > 0 {
		return tx.TemBAD_SIGNATURE
	}
	// Rippled (Change.cpp:65-69) checks sfSequence + sfPreviousTxnID. The
	// PreviousTxnID transaction-field has no representation on tx.Common
	// in goxrpl, so the C++ isFieldPresent(sfPreviousTxnID) check has no
	// reachable analogue here — the field cannot be set on a parsed
	// pseudo-tx.
	if s.Common.Sequence == nil || *s.Common.Sequence != 0 {
		return tx.TemBAD_SEQUENCE
	}
	return tx.TesSUCCESS
}

// preclaim mirrors rippled Change::preclaim() for the ttFEE branch
// (Change.cpp:93-133): the modern XRPFees fields are required and the
// legacy fields forbidden when the amendment is enabled, and the
// reverse holds before activation.
func (s *SetFee) preclaim(ctx *tx.ApplyContext) tx.Result {
	xrpFees := ctx.Config.Rules != nil && ctx.Config.Rules.XRPFeesEnabled()

	hasModern := s.BaseFeeDrops != "" || s.ReserveBaseDrops != "" ||
		s.ReserveIncrementDrops != ""
	hasLegacy := s.BaseFee != "" || s.ReferenceFeeUnits != nil ||
		s.ReserveBase != nil || s.ReserveIncrement != nil

	if xrpFees {
		if s.BaseFeeDrops == "" || s.ReserveBaseDrops == "" || s.ReserveIncrementDrops == "" {
			return tx.TemMALFORMED
		}
		if hasLegacy {
			return tx.TemMALFORMED
		}
	} else {
		if s.BaseFee == "" || s.ReferenceFeeUnits == nil ||
			s.ReserveBase == nil || s.ReserveIncrement == nil {
			return tx.TemMALFORMED
		}
		if hasModern {
			return tx.TemDISABLED
		}
	}
	return tx.TesSUCCESS
}

// Apply mirrors rippled Change::applyFee() (Change.cpp:347-385): it
// either creates or updates the FeeSettings singleton, writing only
// the field set corresponding to the active amendment branch.
// Reference: rippled Change.cpp applyFee()
func (s *SetFee) Apply(ctx *tx.ApplyContext) tx.Result {
	if r := s.preflight(); r != tx.TesSUCCESS {
		return r
	}
	if r := s.preclaim(ctx); r != tx.TesSUCCESS {
		return r
	}

	ctx.Log.Info("set fee apply",
		"baseFeeDrops", s.BaseFeeDrops,
		"reserveBaseDrops", s.ReserveBaseDrops,
		"reserveIncrementDrops", s.ReserveIncrementDrops,
		"baseFee", s.BaseFee,
		"reserveBase", s.ReserveBase,
		"reserveIncrement", s.ReserveIncrement,
	)

	feesKey := keylet.Fees()

	exists, err := ctx.View.Exists(feesKey)
	if err != nil {
		return tx.TefINTERNAL
	}

	var feeSettings *state.FeeSettings
	if exists {
		data, err := ctx.View.Read(feesKey)
		if err != nil {
			return tx.TefINTERNAL
		}
		feeSettings, err = state.ParseFeeSettings(data)
		if err != nil {
			return tx.TefINTERNAL
		}
	} else {
		feeSettings = &state.FeeSettings{}
	}

	xrpFeesEnabled := ctx.Config.Rules != nil && ctx.Config.Rules.XRPFeesEnabled()

	// All parse + nil paths below return tefINTERNAL, not temMALFORMED:
	// preclaim already verified the relevant fields are populated, so a
	// failure here means the field was malformed at serialization time
	// (impossible after preclaim) — the "this shouldn't happen" surface,
	// matching rippled's typed-field assumption in applyFee().
	if xrpFeesEnabled {
		baseDrops, err := parseDropsAmount(s.BaseFeeDrops)
		if err != nil {
			return tx.TefINTERNAL
		}
		reserveDrops, err := parseDropsAmount(s.ReserveBaseDrops)
		if err != nil {
			return tx.TefINTERNAL
		}
		reserveIncDrops, err := parseDropsAmount(s.ReserveIncrementDrops)
		if err != nil {
			return tx.TefINTERNAL
		}
		feeSettings.BaseFeeDrops = baseDrops
		feeSettings.ReserveBaseDrops = reserveDrops
		feeSettings.ReserveIncrementDrops = reserveIncDrops

		// Mirror rippled makeFieldAbsent(sfBaseFee/...) at
		// Change.cpp:368-371: the legacy fields are stripped from the
		// FeeSettings entry once XRPFees activates. SerializeFeeSettings
		// already omits zero-valued legacy fields, so zeroing here is
		// the goxrpl analog of makeFieldAbsent.
		feeSettings.BaseFee = 0
		feeSettings.ReferenceFeeUnits = 0
		feeSettings.ReserveBase = 0
		feeSettings.ReserveIncrement = 0
	} else {
		if s.ReferenceFeeUnits == nil || s.ReserveBase == nil ||
			s.ReserveIncrement == nil {
			return tx.TefINTERNAL
		}
		baseFee, err := parseHexUint64(s.BaseFee)
		if err != nil {
			return tx.TefINTERNAL
		}
		feeSettings.BaseFee = baseFee
		feeSettings.ReferenceFeeUnits = *s.ReferenceFeeUnits
		feeSettings.ReserveBase = *s.ReserveBase
		feeSettings.ReserveIncrement = *s.ReserveIncrement
	}

	data, err := state.SerializeFeeSettings(feeSettings)
	if err != nil {
		ctx.Log.Error("set fee: failed to serialize fee settings", "error", err)
		return tx.TefINTERNAL
	}

	if exists {
		if err := ctx.View.Update(feesKey, data); err != nil {
			ctx.Log.Error("set fee: failed to update fee settings", "error", err)
			return tx.TefINTERNAL
		}
	} else {
		if err := ctx.View.Insert(feesKey, data); err != nil {
			ctx.Log.Error("set fee: failed to insert fee settings", "error", err)
			return tx.TefINTERNAL
		}
	}

	return tx.TesSUCCESS
}

// parseDropsAmount parses a decimal drops string. Empty input is rejected.
func parseDropsAmount(s string) (uint64, error) {
	if s == "" {
		return 0, errors.New("empty drops value")
	}
	return strconv.ParseUint(s, 10, 64)
}

// parseHexUint64 parses a hex-encoded uint64 (XRPL JSON convention for
// the legacy sfBaseFee field). Empty input is rejected.
func parseHexUint64(s string) (uint64, error) {
	if s == "" {
		return 0, errors.New("empty hex value")
	}
	return strconv.ParseUint(s, 16, 64)
}
