package pseudo

import (
	"strconv"

	"github.com/LeJamon/go-xrpl/amendment"
	"github.com/LeJamon/go-xrpl/internal/ledger/state"
	"github.com/LeJamon/go-xrpl/internal/tx"
	"github.com/LeJamon/go-xrpl/internal/tx/ter"
	"github.com/LeJamon/go-xrpl/keylet"
	"github.com/LeJamon/go-xrpl/protocol"
)

// SetFee errors matching rippled
var (
	ErrSetFeeBadSrcAccount = ter.Errorf(ter.TemBAD_SRC_ACCOUNT, "SetFee must have zero account")
	ErrSetFeeBadFee        = ter.Errorf(ter.TemBAD_FEE, "SetFee must have zero fee")
	ErrSetFeeBadSignature  = ter.Errorf(ter.TemBAD_SIGNATURE, "SetFee must not have signature")
	ErrSetFeeBadSequence   = ter.Errorf(ter.TemBAD_SEQUENCE, "SetFee must have zero sequence")
	ErrSetFeeMalformed     = ter.Errorf(ter.TemMALFORMED, "SetFee has invalid fields")
)

// SetFee is a pseudo-transaction that updates network fee settings.
// This transaction is only valid when generated by consensus (validators).
// Reference: rippled Change.cpp applyFee()
type SetFee struct {
	tx.BaseTx

	// Legacy fields (pre-XRPFees amendment)
	// BaseFee is the base transaction fee (hex string for legacy compatibility)
	BaseFee string `json:"BaseFee,omitempty" xrpl:"BaseFee,omitempty"`

	// ReferenceFeeUnits is the reference fee units (typically 10)
	ReferenceFeeUnits *uint32 `json:"ReferenceFeeUnits,omitempty" xrpl:"ReferenceFeeUnits,omitempty"`

	// ReserveBase is the account reserve in drops
	ReserveBase *uint32 `json:"ReserveBase,omitempty" xrpl:"ReserveBase,omitempty"`

	// ReserveIncrement is the owner reserve increment in drops
	ReserveIncrement *uint32 `json:"ReserveIncrement,omitempty" xrpl:"ReserveIncrement,omitempty"`

	// Modern fields (XRPFees amendment)
	// BaseFeeDrops is the base fee in drops
	BaseFeeDrops string `json:"BaseFeeDrops,omitempty" xrpl:"BaseFeeDrops,omitempty"`

	// ReserveBaseDrops is the account reserve in drops
	ReserveBaseDrops string `json:"ReserveBaseDrops,omitempty" xrpl:"ReserveBaseDrops,omitempty"`

	// ReserveIncrementDrops is the owner reserve increment in drops
	ReserveIncrementDrops string `json:"ReserveIncrementDrops,omitempty" xrpl:"ReserveIncrementDrops,omitempty"`

	// LedgerSequence is the ledger sequence for this fee change
	LedgerSequence *uint32 `json:"LedgerSequence,omitempty" xrpl:"LedgerSequence,omitempty"`

	// parsedCache memoises parseFields across Validate / PreclaimPseudo / Apply.
	parsedCache *parsedFeeFields `json:"-" xrpl:"-"`
}

// NewSetFee creates a new SetFee pseudo-transaction.
// This should only be used by consensus/validation code.
func NewSetFee() *SetFee {
	return &SetFee{
		BaseTx: *tx.NewBaseTx(tx.TypeFee, protocol.ZeroAccount),
	}
}

func (s *SetFee) TxType() tx.Type {
	return tx.TypeFee
}

// Validate runs the local syntactic checks that don't need ledger Rules.
// The engine's applyPseudoTransaction enforces the zero-account / zero-fee /
// zero-sequence / no-signature gates from rippled Change::preflight (Change.cpp:36-80);
// per-amendment field-set gating lives in PreclaimPseudo. Validate is reached
// only by non-engine callers (parse.go, unit tests).
func (s *SetFee) Validate() error {
	if !s.hasLegacyFields() && !s.hasModernFields() {
		return ErrSetFeeMalformed
	}
	if _, err := s.parsedOrError(); err != nil {
		return ErrSetFeeMalformed
	}
	return nil
}

// PreclaimPseudo enforces the rippled Change::preclaim ttFEE field-set rules:
// with featureXRPFees enabled, the BaseFeeDrops / ReserveBaseDrops /
// ReserveIncrementDrops triple is required and the legacy quad is forbidden;
// without it, the legacy quad is required and the modern triple is forbidden.
// Reference: rippled Change.cpp:93-133.
func (s *SetFee) PreclaimPseudo(rules *amendment.Rules) ter.Result {
	xrpFees := rules != nil && rules.XRPFeesEnabled()

	if xrpFees {
		if s.BaseFeeDrops == "" || s.ReserveBaseDrops == "" || s.ReserveIncrementDrops == "" {
			return ter.TemMALFORMED
		}
		if s.hasLegacyFields() {
			return ter.TemMALFORMED
		}
	} else {
		if s.BaseFee == "" || s.ReferenceFeeUnits == nil || s.ReserveBase == nil || s.ReserveIncrement == nil {
			return ter.TemMALFORMED
		}
		// rippled returns temDISABLED — not temMALFORMED — when modern fields appear pre-XRPFees.
		if s.hasModernFields() {
			return ter.TemDISABLED
		}
	}

	if _, err := s.parsedOrError(); err != nil {
		return ter.TemMALFORMED
	}

	return ter.TesSUCCESS
}

func (s *SetFee) hasLegacyFields() bool {
	return s.BaseFee != "" || s.ReferenceFeeUnits != nil ||
		s.ReserveBase != nil || s.ReserveIncrement != nil
}

func (s *SetFee) hasModernFields() bool {
	return s.BaseFeeDrops != "" || s.ReserveBaseDrops != "" ||
		s.ReserveIncrementDrops != ""
}

type parsedFeeFields struct {
	baseFee               uint64
	baseFeeDrops          uint64
	reserveBaseDrops      uint64
	reserveIncrementDrops uint64
}

// parsedOrError returns the memoised numeric values, parsing on first call.
// An error from parseFields is always temMALFORMED — preclaim and Apply both
// rely on that mapping.
func (s *SetFee) parsedOrError() (parsedFeeFields, error) {
	if s.parsedCache != nil {
		return *s.parsedCache, nil
	}
	parsed, err := s.parseFields()
	if err != nil {
		return parsed, err
	}
	s.parsedCache = &parsed
	return parsed, nil
}

func (s *SetFee) parseFields() (parsedFeeFields, error) {
	var out parsedFeeFields
	if s.BaseFee != "" {
		v, err := parseHexUint64(s.BaseFee)
		if err != nil {
			return out, err
		}
		out.baseFee = v
	}
	if s.BaseFeeDrops != "" {
		v, err := parseDropsAmount(s.BaseFeeDrops)
		if err != nil {
			return out, err
		}
		out.baseFeeDrops = v
	}
	if s.ReserveBaseDrops != "" {
		v, err := parseDropsAmount(s.ReserveBaseDrops)
		if err != nil {
			return out, err
		}
		out.reserveBaseDrops = v
	}
	if s.ReserveIncrementDrops != "" {
		v, err := parseDropsAmount(s.ReserveIncrementDrops)
		if err != nil {
			return out, err
		}
		out.reserveIncrementDrops = v
	}
	return out, nil
}

func (s *SetFee) Flatten() (map[string]any, error) {
	return tx.ReflectFlatten(s)
}

// IsPseudoTransaction returns true as SetFee is a pseudo-transaction
func (s *SetFee) IsPseudoTransaction() bool {
	return true
}

// This creates or updates the FeeSettings singleton entry.
// Reference: rippled Change.cpp applyFee()
func (s *SetFee) Apply(ctx *tx.ApplyContext) ter.Result {
	ctx.Log.Info("set fee apply",
		"baseFeeDrops", s.BaseFeeDrops,
		"reserveBaseDrops", s.ReserveBaseDrops,
		"reserveIncrementDrops", s.ReserveIncrementDrops,
		"baseFee", s.BaseFee,
		"reserveBase", s.ReserveBase,
		"reserveIncrement", s.ReserveIncrement,
	)

	// PreclaimPseudo has already populated parsedCache; this call hits the
	// cache for engine-path consumers. Apply remains self-contained for the
	// rare callers that bypass the engine wrapper — they trigger the parse
	// here on first access.
	parsed, err := s.parsedOrError()
	if err != nil {
		return ter.TemMALFORMED
	}

	feesKey := keylet.Fees()

	exists, err := ctx.View.Exists(feesKey)
	if err != nil {
		return ter.TefINTERNAL
	}

	var feeSettings *state.FeeSettings

	if exists {
		data, err := ctx.View.Read(feesKey)
		if err != nil {
			return ter.TefINTERNAL
		}

		feeSettings, err = state.ParseFeeSettings(data)
		if err != nil {
			return ter.TefINTERNAL
		}
	} else {
		feeSettings = &state.FeeSettings{}
	}

	xrpFeesEnabled := ctx.Config.Rules != nil && ctx.Config.Rules.XRPFeesEnabled()

	feeSettings.XRPFeesMode = xrpFeesEnabled

	if xrpFeesEnabled {
		feeSettings.BaseFeeDrops = parsed.baseFeeDrops
		feeSettings.ReserveBaseDrops = parsed.reserveBaseDrops
		feeSettings.ReserveIncrementDrops = parsed.reserveIncrementDrops

		// Stale legacy fields are dropped from the active mode. Serialize emits
		// only the modern triple when XRPFeesMode is true, mirroring rippled's
		// makeFieldAbsent calls at Change.cpp:367-371.
		feeSettings.BaseFee = 0
		feeSettings.ReferenceFeeUnits = 0
		feeSettings.ReserveBase = 0
		feeSettings.ReserveIncrement = 0
	} else {
		feeSettings.BaseFee = parsed.baseFee
		if s.ReferenceFeeUnits != nil {
			feeSettings.ReferenceFeeUnits = *s.ReferenceFeeUnits
		}
		if s.ReserveBase != nil {
			feeSettings.ReserveBase = *s.ReserveBase
		}
		if s.ReserveIncrement != nil {
			feeSettings.ReserveIncrement = *s.ReserveIncrement
		}
		feeSettings.BaseFeeDrops = 0
		feeSettings.ReserveBaseDrops = 0
		feeSettings.ReserveIncrementDrops = 0
	}

	data, err := state.SerializeFeeSettings(feeSettings)
	if err != nil {
		ctx.Log.Error("set fee: failed to serialize fee settings", "error", err)
		return ter.TefINTERNAL
	}

	// Insert or update the FeeSettings entry
	if exists {
		if err := ctx.View.Update(feesKey, data); err != nil {
			ctx.Log.Error("set fee: failed to update fee settings", "error", err)
			return ter.TefINTERNAL
		}
	} else {
		if err := ctx.View.Insert(feesKey, data); err != nil {
			ctx.Log.Error("set fee: failed to insert fee settings", "error", err)
			return ter.TefINTERNAL
		}
	}

	return ter.TesSUCCESS
}

// parseDropsAmount parses a decimal drops amount string to uint64.
func parseDropsAmount(s string) (uint64, error) {
	return strconv.ParseUint(s, 10, 64)
}

// parseHexUint64 parses a hex string to uint64.
func parseHexUint64(s string) (uint64, error) {
	return strconv.ParseUint(s, 16, 64)
}
