// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

func init() {
	Register("AccountRoot", func() Entry { return new(AccountRoot) })
}

// AccountRoot is the typed representation of a AccountRoot ledger entry
// on the metadata hot path. present tracks which fields appear on the
// decoded blob so the emit methods only write entries that actually exist.
type AccountRoot struct {
	present              uint64
	Account              string // AccountID (base58)
	Balance              any    // Amount (XRP string | IOU map)
	Sequence             uint32
	OwnerCount           uint32
	Flags                uint32
	RegularKey           string // AccountID (base58)
	Domain               string // Blob (uppercase hex)
	EmailHash            string // Hash128 (uppercase hex)
	MessageKey           string // Blob (uppercase hex)
	TransferRate         uint32
	TickSize             int
	NFTokenMinter        string // AccountID (base58)
	MintedNFTokens       uint32
	BurnedNFTokens       uint32
	FirstNFTokenSequence uint32
	AccountTxnID         string // Hash256 (uppercase hex)
	WalletLocator        string // Hash256 (uppercase hex)
	TicketCount          uint32
	AMMID                string // Hash256 (uppercase hex)
	VaultID              string // Hash256 (uppercase hex)
	WalletSize           uint32
	PreviousTxnID        string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq    uint32
}

const (
	accountrootBitAccount uint64 = 1 << iota
	accountrootBitBalance
	accountrootBitSequence
	accountrootBitOwnerCount
	accountrootBitFlags
	accountrootBitRegularKey
	accountrootBitDomain
	accountrootBitEmailHash
	accountrootBitMessageKey
	accountrootBitTransferRate
	accountrootBitTickSize
	accountrootBitNFTokenMinter
	accountrootBitMintedNFTokens
	accountrootBitBurnedNFTokens
	accountrootBitFirstNFTokenSequence
	accountrootBitAccountTxnID
	accountrootBitWalletLocator
	accountrootBitTicketCount
	accountrootBitAMMID
	accountrootBitVaultID
	accountrootBitWalletSize
	accountrootBitPreviousTxnID
	accountrootBitPreviousTxnLgrSeq
)

// Decode populates the struct from binary ledger-entry data via a streaming
// reader. Unknown / sMD_Never fields are skipped without allocation.
func (a *AccountRoot) Decode(data []byte) error {
	*a = AccountRoot{}
	sr := newStreamReader(data)
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				_ = val // LedgerEntryType is sMD_Never; discard
			default:
				return newErrUnknownField("AccountRoot", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				a.Flags = val
				a.present |= accountrootBitFlags
			case 4:
				a.Sequence = val
				a.present |= accountrootBitSequence
			case 5:
				a.PreviousTxnLgrSeq = val
				a.present |= accountrootBitPreviousTxnLgrSeq
			case 11:
				a.TransferRate = val
				a.present |= accountrootBitTransferRate
			case 12:
				a.WalletSize = val
				a.present |= accountrootBitWalletSize
			case 13:
				a.OwnerCount = val
				a.present |= accountrootBitOwnerCount
			case 40:
				a.TicketCount = val
				a.present |= accountrootBitTicketCount
			case 43:
				a.MintedNFTokens = val
				a.present |= accountrootBitMintedNFTokens
			case 44:
				a.BurnedNFTokens = val
				a.present |= accountrootBitBurnedNFTokens
			case 50:
				a.FirstNFTokenSequence = val
				a.present |= accountrootBitFirstNFTokenSequence
			default:
				return newErrUnknownField("AccountRoot", typeCode, fieldCode)
			}
		case 4: // Hash128
			val, err := sr.readHash(16)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				a.EmailHash = val
				a.present |= accountrootBitEmailHash
			default:
				return newErrUnknownField("AccountRoot", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				a.PreviousTxnID = val
				a.present |= accountrootBitPreviousTxnID
			case 7:
				a.WalletLocator = val
				a.present |= accountrootBitWalletLocator
			case 9:
				a.AccountTxnID = val
				a.present |= accountrootBitAccountTxnID
			case 14:
				a.AMMID = val
				a.present |= accountrootBitAMMID
			case 35:
				a.VaultID = val
				a.present |= accountrootBitVaultID
			default:
				return newErrUnknownField("AccountRoot", typeCode, fieldCode)
			}
		case 6: // Amount
			val, err := sr.readAmount()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				if s, ok := val.(string); ok {
					a.Balance = s
					a.present |= accountrootBitBalance
				}
			default:
				return newErrUnknownField("AccountRoot", typeCode, fieldCode)
			}
		case 7: // Blob
			val, err := sr.readBlobHex()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				a.MessageKey = val
				a.present |= accountrootBitMessageKey
			case 7:
				a.Domain = val
				a.present |= accountrootBitDomain
			default:
				return newErrUnknownField("AccountRoot", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				a.Account = val
				a.present |= accountrootBitAccount
			case 8:
				a.RegularKey = val
				a.present |= accountrootBitRegularKey
			case 9:
				a.NFTokenMinter = val
				a.present |= accountrootBitNFTokenMinter
			default:
				return newErrUnknownField("AccountRoot", typeCode, fieldCode)
			}
		case 16: // UInt8
			byteVal, err := sr.readUint8()
			if err != nil {
				return err
			}
			val := int(byteVal)
			switch fieldCode {
			case 16:
				a.TickSize = val
				a.present |= accountrootBitTickSize
			default:
				return newErrUnknownField("AccountRoot", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("AccountRoot", typeCode, fieldCode)
		}
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (a *AccountRoot) emitAll(out map[string]any, skipDefault bool) {
	if a.present&accountrootBitAccount != 0 && !(skipDefault && a.Account == "") {
		out["Account"] = a.Account
	}
	if a.present&accountrootBitBalance != 0 {
		out["Balance"] = a.Balance
	}
	if a.present&accountrootBitSequence != 0 && !(skipDefault && a.Sequence == 0) {
		out["Sequence"] = a.Sequence
	}
	if a.present&accountrootBitOwnerCount != 0 && !(skipDefault && a.OwnerCount == 0) {
		out["OwnerCount"] = a.OwnerCount
	}
	if a.present&accountrootBitFlags != 0 && !(skipDefault && a.Flags == 0) {
		out["Flags"] = a.Flags
	}
	if a.present&accountrootBitRegularKey != 0 && !(skipDefault && a.RegularKey == "") {
		out["RegularKey"] = a.RegularKey
	}
	if a.present&accountrootBitDomain != 0 && !(skipDefault && a.Domain == "") {
		out["Domain"] = a.Domain
	}
	if a.present&accountrootBitEmailHash != 0 && !(skipDefault && isZeroHexString(a.EmailHash)) {
		out["EmailHash"] = a.EmailHash
	}
	if a.present&accountrootBitMessageKey != 0 && !(skipDefault && a.MessageKey == "") {
		out["MessageKey"] = a.MessageKey
	}
	if a.present&accountrootBitTransferRate != 0 && !(skipDefault && a.TransferRate == 0) {
		out["TransferRate"] = a.TransferRate
	}
	if a.present&accountrootBitTickSize != 0 && !(skipDefault && a.TickSize == 0) {
		out["TickSize"] = a.TickSize
	}
	if a.present&accountrootBitNFTokenMinter != 0 && !(skipDefault && a.NFTokenMinter == "") {
		out["NFTokenMinter"] = a.NFTokenMinter
	}
	if a.present&accountrootBitMintedNFTokens != 0 && !(skipDefault && a.MintedNFTokens == 0) {
		out["MintedNFTokens"] = a.MintedNFTokens
	}
	if a.present&accountrootBitBurnedNFTokens != 0 && !(skipDefault && a.BurnedNFTokens == 0) {
		out["BurnedNFTokens"] = a.BurnedNFTokens
	}
	if a.present&accountrootBitFirstNFTokenSequence != 0 && !(skipDefault && a.FirstNFTokenSequence == 0) {
		out["FirstNFTokenSequence"] = a.FirstNFTokenSequence
	}
	if a.present&accountrootBitAccountTxnID != 0 && !(skipDefault && isZeroHexString(a.AccountTxnID)) {
		out["AccountTxnID"] = a.AccountTxnID
	}
	if a.present&accountrootBitWalletLocator != 0 && !(skipDefault && isZeroHexString(a.WalletLocator)) {
		out["WalletLocator"] = a.WalletLocator
	}
	if a.present&accountrootBitTicketCount != 0 && !(skipDefault && a.TicketCount == 0) {
		out["TicketCount"] = a.TicketCount
	}
	if a.present&accountrootBitAMMID != 0 && !(skipDefault && isZeroHexString(a.AMMID)) {
		out["AMMID"] = a.AMMID
	}
	if a.present&accountrootBitVaultID != 0 && !(skipDefault && isZeroHexString(a.VaultID)) {
		out["VaultID"] = a.VaultID
	}
	if a.present&accountrootBitWalletSize != 0 && !(skipDefault && a.WalletSize == 0) {
		out["WalletSize"] = a.WalletSize
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (a *AccountRoot) EmitNewFields(out map[string]any) {
	a.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (a *AccountRoot) EmitFinalFields(out map[string]any) {
	a.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig).
func (a *AccountRoot) EmitPreviousFields(prev Entry, out map[string]any) {
	p, ok := prev.(*AccountRoot)
	if !ok || p == nil {
		return
	}
	emitIfChangedString(out, "Account", p.Account, a.Account, p.present&accountrootBitAccount, a.present&accountrootBitAccount)
	emitIfChangedAmount(out, "Balance", p.Balance, a.Balance, p.present&accountrootBitBalance, a.present&accountrootBitBalance)
	emitIfChangedUint32(out, "Sequence", p.Sequence, a.Sequence, p.present&accountrootBitSequence, a.present&accountrootBitSequence)
	emitIfChangedUint32(out, "OwnerCount", p.OwnerCount, a.OwnerCount, p.present&accountrootBitOwnerCount, a.present&accountrootBitOwnerCount)
	emitIfChangedUint32(out, "Flags", p.Flags, a.Flags, p.present&accountrootBitFlags, a.present&accountrootBitFlags)
	emitIfChangedString(out, "RegularKey", p.RegularKey, a.RegularKey, p.present&accountrootBitRegularKey, a.present&accountrootBitRegularKey)
	emitIfChangedString(out, "Domain", p.Domain, a.Domain, p.present&accountrootBitDomain, a.present&accountrootBitDomain)
	emitIfChangedString(out, "EmailHash", p.EmailHash, a.EmailHash, p.present&accountrootBitEmailHash, a.present&accountrootBitEmailHash)
	emitIfChangedString(out, "MessageKey", p.MessageKey, a.MessageKey, p.present&accountrootBitMessageKey, a.present&accountrootBitMessageKey)
	emitIfChangedUint32(out, "TransferRate", p.TransferRate, a.TransferRate, p.present&accountrootBitTransferRate, a.present&accountrootBitTransferRate)
	emitIfChangedInt(out, "TickSize", p.TickSize, a.TickSize, p.present&accountrootBitTickSize, a.present&accountrootBitTickSize)
	emitIfChangedString(out, "NFTokenMinter", p.NFTokenMinter, a.NFTokenMinter, p.present&accountrootBitNFTokenMinter, a.present&accountrootBitNFTokenMinter)
	emitIfChangedUint32(out, "MintedNFTokens", p.MintedNFTokens, a.MintedNFTokens, p.present&accountrootBitMintedNFTokens, a.present&accountrootBitMintedNFTokens)
	emitIfChangedUint32(out, "BurnedNFTokens", p.BurnedNFTokens, a.BurnedNFTokens, p.present&accountrootBitBurnedNFTokens, a.present&accountrootBitBurnedNFTokens)
	emitIfChangedUint32(out, "FirstNFTokenSequence", p.FirstNFTokenSequence, a.FirstNFTokenSequence, p.present&accountrootBitFirstNFTokenSequence, a.present&accountrootBitFirstNFTokenSequence)
	emitIfChangedString(out, "AccountTxnID", p.AccountTxnID, a.AccountTxnID, p.present&accountrootBitAccountTxnID, a.present&accountrootBitAccountTxnID)
	emitIfChangedString(out, "WalletLocator", p.WalletLocator, a.WalletLocator, p.present&accountrootBitWalletLocator, a.present&accountrootBitWalletLocator)
	emitIfChangedUint32(out, "TicketCount", p.TicketCount, a.TicketCount, p.present&accountrootBitTicketCount, a.present&accountrootBitTicketCount)
	emitIfChangedString(out, "AMMID", p.AMMID, a.AMMID, p.present&accountrootBitAMMID, a.present&accountrootBitAMMID)
	emitIfChangedString(out, "VaultID", p.VaultID, a.VaultID, p.present&accountrootBitVaultID, a.present&accountrootBitVaultID)
	emitIfChangedUint32(out, "WalletSize", p.WalletSize, a.WalletSize, p.present&accountrootBitWalletSize, a.present&accountrootBitWalletSize)
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (a *AccountRoot) EmitDeleteFinalFields(out map[string]any) {
	a.emitAll(out, false)
	if a.present&accountrootBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = a.PreviousTxnID
	}
	if a.present&accountrootBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = a.PreviousTxnLgrSeq
	}
}

// EmitDeletePreviousFields mirrors EmitPreviousFields for DeletedNode.
func (a *AccountRoot) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	a.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (a *AccountRoot) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if a.present&accountrootBitPreviousTxnID != 0 {
		id = a.PreviousTxnID
	}
	if a.present&accountrootBitPreviousTxnLgrSeq != 0 {
		seq = a.PreviousTxnLgrSeq
	}
	return id, seq
}
