// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

func init() {
	Register("Amendments", func() Entry { return new(Amendments) })
}

// Amendments is the typed representation of a Amendments ledger entry
// on the metadata hot path. present tracks which fields appear on the
// decoded blob so the emit methods only write entries that actually exist.
type Amendments struct {
	present           uint64
	Flags             uint32
	Amendments        []string
	Majorities        []any
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
}

const (
	amendmentsBitFlags uint64 = 1 << iota
	amendmentsBitAmendments
	amendmentsBitMajorities
	amendmentsBitPreviousTxnID
	amendmentsBitPreviousTxnLgrSeq
)

// Decode populates the struct from binary ledger-entry data via a streaming
// reader. Unknown / sMD_Never fields are skipped without allocation.
func (a *Amendments) Decode(data []byte) error {
	*a = Amendments{}
	sr := newStreamReader(data)
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				_ = val // LedgerEntryType is sMD_Never; discard
			default:
				return newErrUnknownField("Amendments", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				a.Flags = val
				a.present |= amendmentsBitFlags
			case 5:
				a.PreviousTxnLgrSeq = val
				a.present |= amendmentsBitPreviousTxnLgrSeq
			default:
				return newErrUnknownField("Amendments", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				a.PreviousTxnID = val
				a.present |= amendmentsBitPreviousTxnID
			default:
				return newErrUnknownField("Amendments", typeCode, fieldCode)
			}
		case 15: // STArray
			val, err := sr.readSTArray()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 16:
				a.Majorities = val
				a.present |= amendmentsBitMajorities
			default:
				return newErrUnknownField("Amendments", typeCode, fieldCode)
			}
		case 19: // Vector256
			val, err := sr.readVector256()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 3:
				a.Amendments = val
				a.present |= amendmentsBitAmendments
			default:
				return newErrUnknownField("Amendments", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("Amendments", typeCode, fieldCode)
		}
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (a *Amendments) emitAll(out map[string]any, skipDefault bool) {
	if a.present&amendmentsBitFlags != 0 && !(skipDefault && a.Flags == 0) {
		out["Flags"] = a.Flags
	}
	if a.present&amendmentsBitAmendments != 0 {
		out["Amendments"] = a.Amendments
	}
	if a.present&amendmentsBitMajorities != 0 {
		out["Majorities"] = a.Majorities
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (a *Amendments) EmitNewFields(out map[string]any) {
	a.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (a *Amendments) EmitFinalFields(out map[string]any) {
	a.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig).
func (a *Amendments) EmitPreviousFields(prev Entry, out map[string]any) {
	p, ok := prev.(*Amendments)
	if !ok || p == nil {
		return
	}
	emitIfChangedUint32(out, "Flags", p.Flags, a.Flags, p.present&amendmentsBitFlags, a.present&amendmentsBitFlags)
	emitIfChangedStringSlice(out, "Amendments", p.Amendments, a.Amendments, p.present&amendmentsBitAmendments, a.present&amendmentsBitAmendments)
	emitIfChangedDeep(out, "Majorities", p.Majorities, a.Majorities, p.present&amendmentsBitMajorities, a.present&amendmentsBitMajorities)
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (a *Amendments) EmitDeleteFinalFields(out map[string]any) {
	a.emitAll(out, false)
	if a.present&amendmentsBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = a.PreviousTxnID
	}
	if a.present&amendmentsBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = a.PreviousTxnLgrSeq
	}
}

// EmitDeletePreviousFields mirrors EmitPreviousFields for DeletedNode.
func (a *Amendments) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	a.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (a *Amendments) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if a.present&amendmentsBitPreviousTxnID != 0 {
		id = a.PreviousTxnID
	}
	if a.present&amendmentsBitPreviousTxnLgrSeq != 0 {
		seq = a.PreviousTxnLgrSeq
	}
	return id, seq
}
