// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

func init() {
	Register("AMM", func() Entry { return new(AMM) })
}

// AMM is the typed metadata-hot-path representation of a
// AMM ledger entry. The present bitset tracks which fields appear on
// the decoded blob so the emit methods only write entries that actually exist.
type AMM struct {
	present           uint64
	Account           string // AccountID (base58)
	TradingFee        int
	VoteSlots         []any
	AuctionSlot       map[string]any
	LPTokenBalance    any // Amount (XRP string | IOU map)
	Asset             any
	Asset2            any
	OwnerNode         string // UInt64 (lowercase hex, no leading zeros)
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
}

const (
	ammBitAccount uint64 = 1 << iota
	ammBitTradingFee
	ammBitVoteSlots
	ammBitAuctionSlot
	ammBitLPTokenBalance
	ammBitAsset
	ammBitAsset2
	ammBitOwnerNode
	ammBitPreviousTxnID
	ammBitPreviousTxnLgrSeq
)

// Decode populates the struct from binary ledger-entry data via a streaming
// reader. Unknown / sMD_Never fields are skipped without allocation.
func (a *AMM) Decode(data []byte) error {
	*a = AMM{}
	sr := newStreamReader(data)
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				_ = val // LedgerEntryType is sMD_Never; discard
			case 5:
				a.TradingFee = val
				a.present |= ammBitTradingFee
			default:
				return newErrUnknownField("AMM", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				a.PreviousTxnLgrSeq = val
				a.present |= ammBitPreviousTxnLgrSeq
			default:
				return newErrUnknownField("AMM", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 4:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				a.OwnerNode = val
				a.present |= ammBitOwnerNode
			default:
				return newErrUnknownField("AMM", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				a.PreviousTxnID = val
				a.present |= ammBitPreviousTxnID
			default:
				return newErrUnknownField("AMM", typeCode, fieldCode)
			}
		case 6: // Amount
			val, err := sr.readAmountAny()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 31:
				a.LPTokenBalance = val
				a.present |= ammBitLPTokenBalance
			default:
				return newErrUnknownField("AMM", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				a.Account = val
				a.present |= ammBitAccount
			default:
				return newErrUnknownField("AMM", typeCode, fieldCode)
			}
		case 14: // STObject
			val, err := sr.readSTObject()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 26:
				a.AuctionSlot = val
				a.present |= ammBitAuctionSlot
			default:
				return newErrUnknownField("AMM", typeCode, fieldCode)
			}
		case 15: // STArray
			val, err := sr.readSTArray()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 12:
				a.VoteSlots = val
				a.present |= ammBitVoteSlots
			default:
				return newErrUnknownField("AMM", typeCode, fieldCode)
			}
		case 24: // Issue
			val, err := sr.readIssue()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 3:
				a.Asset = val
				a.present |= ammBitAsset
			case 4:
				a.Asset2 = val
				a.present |= ammBitAsset2
			default:
				return newErrUnknownField("AMM", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("AMM", typeCode, fieldCode)
		}
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (a *AMM) emitAll(out map[string]any, skipDefault bool) {
	if a.present&ammBitAccount != 0 && !(skipDefault && a.Account == "") {
		out["Account"] = a.Account
	}
	if a.present&ammBitTradingFee != 0 && !(skipDefault && a.TradingFee == 0) {
		out["TradingFee"] = a.TradingFee
	}
	if a.present&ammBitVoteSlots != 0 {
		out["VoteSlots"] = a.VoteSlots
	}
	if a.present&ammBitAuctionSlot != 0 {
		out["AuctionSlot"] = a.AuctionSlot
	}
	if a.present&ammBitLPTokenBalance != 0 {
		out["LPTokenBalance"] = a.LPTokenBalance
	}
	if a.present&ammBitAsset != 0 {
		out["Asset"] = a.Asset
	}
	if a.present&ammBitAsset2 != 0 {
		out["Asset2"] = a.Asset2
	}
	if a.present&ammBitOwnerNode != 0 && !(skipDefault && isZeroHexString(a.OwnerNode)) {
		out["OwnerNode"] = a.OwnerNode
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (a *AMM) EmitNewFields(out map[string]any) {
	a.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (a *AMM) EmitFinalFields(out map[string]any) {
	a.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig).
func (a *AMM) EmitPreviousFields(prev Entry, out map[string]any) {
	p, ok := prev.(*AMM)
	if !ok || p == nil {
		return
	}
	emitIfChangedString(out, "Account", p.Account, a.Account, p.present&ammBitAccount, a.present&ammBitAccount)
	emitIfChangedInt(out, "TradingFee", p.TradingFee, a.TradingFee, p.present&ammBitTradingFee, a.present&ammBitTradingFee)
	emitIfChangedDeep(out, "VoteSlots", p.VoteSlots, a.VoteSlots, p.present&ammBitVoteSlots, a.present&ammBitVoteSlots)
	emitIfChangedDeep(out, "AuctionSlot", p.AuctionSlot, a.AuctionSlot, p.present&ammBitAuctionSlot, a.present&ammBitAuctionSlot)
	emitIfChangedAmount(out, "LPTokenBalance", p.LPTokenBalance, a.LPTokenBalance, p.present&ammBitLPTokenBalance, a.present&ammBitLPTokenBalance)
	emitIfChangedDeep(out, "Asset", p.Asset, a.Asset, p.present&ammBitAsset, a.present&ammBitAsset)
	emitIfChangedDeep(out, "Asset2", p.Asset2, a.Asset2, p.present&ammBitAsset2, a.present&ammBitAsset2)
	emitIfChangedString(out, "OwnerNode", p.OwnerNode, a.OwnerNode, p.present&ammBitOwnerNode, a.present&ammBitOwnerNode)
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (a *AMM) EmitDeleteFinalFields(out map[string]any) {
	a.emitAll(out, false)
	if a.present&ammBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = a.PreviousTxnID
	}
	if a.present&ammBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = a.PreviousTxnLgrSeq
	}
}

func (a *AMM) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	a.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (a *AMM) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if a.present&ammBitPreviousTxnID != 0 {
		id = a.PreviousTxnID
	}
	if a.present&ammBitPreviousTxnLgrSeq != 0 {
		seq = a.PreviousTxnLgrSeq
	}
	return id, seq
}
