// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

func init() {
	Register("Credential", func() Entry { return new(Credential) })
}

// Credential is the typed representation of a Credential ledger entry
// on the metadata hot path. present tracks which fields appear on the
// decoded blob so the emit methods only write entries that actually exist.
type Credential struct {
	present           uint64
	Subject           string // AccountID (base58)
	Issuer            string // AccountID (base58)
	CredentialType    string // Blob (uppercase hex)
	Expiration        uint32
	URI               string // Blob (uppercase hex)
	IssuerNode        string // UInt64 (uppercase hex)
	SubjectNode       string // UInt64 (uppercase hex)
	Flags             uint32
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
}

const (
	credentialBitSubject uint64 = 1 << iota
	credentialBitIssuer
	credentialBitCredentialType
	credentialBitExpiration
	credentialBitURI
	credentialBitIssuerNode
	credentialBitSubjectNode
	credentialBitFlags
	credentialBitPreviousTxnID
	credentialBitPreviousTxnLgrSeq
)

// Decode populates the struct from binary ledger-entry data via a streaming
// reader. Unknown / sMD_Never fields are skipped without allocation.
func (c *Credential) Decode(data []byte) error {
	*c = Credential{}
	sr := newStreamReader(data)
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				_ = val // LedgerEntryType is sMD_Never; discard
			default:
				_ = val
				return newErrUnknownField("Credential", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				c.Flags = val
				c.present |= credentialBitFlags
			case 5:
				c.PreviousTxnLgrSeq = val
				c.present |= credentialBitPreviousTxnLgrSeq
			case 10:
				c.Expiration = val
				c.present |= credentialBitExpiration
			default:
				_ = val
				return newErrUnknownField("Credential", typeCode, fieldCode)
			}
		case 3: // UInt64
			val, err := sr.readUint64Hex()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 27:
				c.IssuerNode = val
				c.present |= credentialBitIssuerNode
			case 28:
				c.SubjectNode = val
				c.present |= credentialBitSubjectNode
			default:
				_ = val
				return newErrUnknownField("Credential", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				c.PreviousTxnID = val
				c.present |= credentialBitPreviousTxnID
			default:
				_ = val
				return newErrUnknownField("Credential", typeCode, fieldCode)
			}
		case 7: // Blob
			val, err := sr.readBlobHex()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				c.URI = val
				c.present |= credentialBitURI
			case 31:
				c.CredentialType = val
				c.present |= credentialBitCredentialType
			default:
				_ = val
				return newErrUnknownField("Credential", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 4:
				c.Issuer = val
				c.present |= credentialBitIssuer
			case 24:
				c.Subject = val
				c.present |= credentialBitSubject
			default:
				_ = val
				return newErrUnknownField("Credential", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("Credential", typeCode, fieldCode)
		}
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (c *Credential) emitAll(out map[string]any, skipDefault bool) {
	if c.present&credentialBitSubject != 0 && !(skipDefault && c.Subject == "") {
		out["Subject"] = c.Subject
	}
	if c.present&credentialBitIssuer != 0 && !(skipDefault && c.Issuer == "") {
		out["Issuer"] = c.Issuer
	}
	if c.present&credentialBitCredentialType != 0 && !(skipDefault && c.CredentialType == "") {
		out["CredentialType"] = c.CredentialType
	}
	if c.present&credentialBitExpiration != 0 && !(skipDefault && c.Expiration == 0) {
		out["Expiration"] = c.Expiration
	}
	if c.present&credentialBitURI != 0 && !(skipDefault && c.URI == "") {
		out["URI"] = c.URI
	}
	if c.present&credentialBitIssuerNode != 0 && !(skipDefault && isZeroHexString(c.IssuerNode)) {
		out["IssuerNode"] = c.IssuerNode
	}
	if c.present&credentialBitSubjectNode != 0 && !(skipDefault && isZeroHexString(c.SubjectNode)) {
		out["SubjectNode"] = c.SubjectNode
	}
	if c.present&credentialBitFlags != 0 && !(skipDefault && c.Flags == 0) {
		out["Flags"] = c.Flags
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (c *Credential) EmitNewFields(out map[string]any) {
	c.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (c *Credential) EmitFinalFields(out map[string]any) {
	c.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig).
func (c *Credential) EmitPreviousFields(prev Entry, out map[string]any) {
	p, ok := prev.(*Credential)
	if !ok || p == nil {
		return
	}
	emitIfChangedString(out, "Subject", p.Subject, c.Subject, p.present&credentialBitSubject, c.present&credentialBitSubject)
	emitIfChangedString(out, "Issuer", p.Issuer, c.Issuer, p.present&credentialBitIssuer, c.present&credentialBitIssuer)
	emitIfChangedString(out, "CredentialType", p.CredentialType, c.CredentialType, p.present&credentialBitCredentialType, c.present&credentialBitCredentialType)
	emitIfChangedUint32(out, "Expiration", p.Expiration, c.Expiration, p.present&credentialBitExpiration, c.present&credentialBitExpiration)
	emitIfChangedString(out, "URI", p.URI, c.URI, p.present&credentialBitURI, c.present&credentialBitURI)
	emitIfChangedString(out, "IssuerNode", p.IssuerNode, c.IssuerNode, p.present&credentialBitIssuerNode, c.present&credentialBitIssuerNode)
	emitIfChangedString(out, "SubjectNode", p.SubjectNode, c.SubjectNode, p.present&credentialBitSubjectNode, c.present&credentialBitSubjectNode)
	emitIfChangedUint32(out, "Flags", p.Flags, c.Flags, p.present&credentialBitFlags, c.present&credentialBitFlags)
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (c *Credential) EmitDeleteFinalFields(out map[string]any) {
	c.emitAll(out, false)
	if c.present&credentialBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = c.PreviousTxnID
	}
	if c.present&credentialBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = c.PreviousTxnLgrSeq
	}
}

// EmitDeletePreviousFields mirrors EmitPreviousFields for DeletedNode.
func (c *Credential) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	c.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (c *Credential) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if c.present&credentialBitPreviousTxnID != 0 {
		id = c.PreviousTxnID
	}
	if c.present&credentialBitPreviousTxnLgrSeq != 0 {
		seq = c.PreviousTxnLgrSeq
	}
	return id, seq
}
