// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

import (
	"github.com/LeJamon/goXRPLd/codec/binarycodec"
	"github.com/LeJamon/goXRPLd/crypto/common"
	"github.com/LeJamon/goXRPLd/protocol"
)

func init() {
	Register("DepositPreauth", func() Entry { return new(DepositPreauth) })
}

// DepositPreauth is the typed representation of a DepositPreauth ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every on-wire field — including those excluded from metadata
// (sMD_Never) — so Decode → Encode is byte-identical.
type DepositPreauth struct {
	present              uint64
	Account              string // AccountID (base58)
	Authorize            string // AccountID (base58)
	OwnerNode            string // UInt64 (lowercase hex, no leading zeros)
	AuthorizeCredentials []any
	Flags                uint32
	PreviousTxnID        string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq    uint32
}

const (
	depositpreauthBitAccount uint64 = 1 << iota
	depositpreauthBitAuthorize
	depositpreauthBitOwnerNode
	depositpreauthBitAuthorizeCredentials
	depositpreauthBitFlags
	depositpreauthBitPreviousTxnID
	depositpreauthBitPreviousTxnLgrSeq
)

// Decode populates the struct from binary ledger-entry data via a streaming
// reader. Unknown / sMD_Never fields are skipped without allocation.
func (d *DepositPreauth) Decode(data []byte) error {
	*d = DepositPreauth{}
	sr := newStreamReader(data)
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				_ = val // synthetic LedgerEntryType; discard
			default:
				return newErrUnknownField("DepositPreauth", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				d.Flags = val
				d.present |= depositpreauthBitFlags
			case 5:
				d.PreviousTxnLgrSeq = val
				d.present |= depositpreauthBitPreviousTxnLgrSeq
			default:
				return newErrUnknownField("DepositPreauth", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 4:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				d.OwnerNode = val
				d.present |= depositpreauthBitOwnerNode
			default:
				return newErrUnknownField("DepositPreauth", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				d.PreviousTxnID = val
				d.present |= depositpreauthBitPreviousTxnID
			default:
				return newErrUnknownField("DepositPreauth", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				d.Account = val
				d.present |= depositpreauthBitAccount
			case 5:
				d.Authorize = val
				d.present |= depositpreauthBitAuthorize
			default:
				return newErrUnknownField("DepositPreauth", typeCode, fieldCode)
			}
		case 15: // STArray
			val, err := sr.readSTArray()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 26:
				d.AuthorizeCredentials = val
				d.present |= depositpreauthBitAuthorizeCredentials
			default:
				return newErrUnknownField("DepositPreauth", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("DepositPreauth", typeCode, fieldCode)
		}
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (d *DepositPreauth) emitAll(out map[string]any, skipDefault bool) {
	if d.present&depositpreauthBitAccount != 0 && !(skipDefault && d.Account == "") {
		out["Account"] = d.Account
	}
	if d.present&depositpreauthBitAuthorize != 0 && !(skipDefault && d.Authorize == "") {
		out["Authorize"] = d.Authorize
	}
	if d.present&depositpreauthBitOwnerNode != 0 && !(skipDefault && isZeroHexString(d.OwnerNode)) {
		out["OwnerNode"] = d.OwnerNode
	}
	if d.present&depositpreauthBitAuthorizeCredentials != 0 {
		out["AuthorizeCredentials"] = d.AuthorizeCredentials
	}
	if d.present&depositpreauthBitFlags != 0 && !(skipDefault && d.Flags == 0) {
		out["Flags"] = d.Flags
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (d *DepositPreauth) EmitNewFields(out map[string]any) {
	d.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (d *DepositPreauth) EmitFinalFields(out map[string]any) {
	d.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (d *DepositPreauth) EmitPreviousFields(prev Entry, out map[string]any) {
	p, ok := prev.(*DepositPreauth)
	if !ok || p == nil {
		return
	}
	emitIfChangedString(out, "Account", p.Account, d.Account, p.present&depositpreauthBitAccount, d.present&depositpreauthBitAccount)
	emitIfChangedString(out, "Authorize", p.Authorize, d.Authorize, p.present&depositpreauthBitAuthorize, d.present&depositpreauthBitAuthorize)
	emitIfChangedString(out, "OwnerNode", p.OwnerNode, d.OwnerNode, p.present&depositpreauthBitOwnerNode, d.present&depositpreauthBitOwnerNode)
	emitIfChangedDeep(out, "AuthorizeCredentials", p.AuthorizeCredentials, d.AuthorizeCredentials, p.present&depositpreauthBitAuthorizeCredentials, d.present&depositpreauthBitAuthorizeCredentials)
	emitIfChangedUint32(out, "Flags", p.Flags, d.Flags, p.present&depositpreauthBitFlags, d.present&depositpreauthBitFlags)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (d *DepositPreauth) EmitChangeOrigFields(out map[string]any) {
	if d.present&depositpreauthBitAccount != 0 {
		out["Account"] = d.Account
	}
	if d.present&depositpreauthBitAuthorize != 0 {
		out["Authorize"] = d.Authorize
	}
	if d.present&depositpreauthBitOwnerNode != 0 {
		out["OwnerNode"] = d.OwnerNode
	}
	if d.present&depositpreauthBitAuthorizeCredentials != 0 {
		out["AuthorizeCredentials"] = d.AuthorizeCredentials
	}
	if d.present&depositpreauthBitFlags != 0 {
		out["Flags"] = d.Flags
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (d *DepositPreauth) EmitDeleteFinalFields(out map[string]any) {
	d.emitAll(out, false)
	if d.present&depositpreauthBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = d.PreviousTxnID
	}
	if d.present&depositpreauthBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = d.PreviousTxnLgrSeq
	}
}

func (d *DepositPreauth) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	d.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (d *DepositPreauth) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if d.present&depositpreauthBitPreviousTxnID != 0 {
		id = d.PreviousTxnID
	}
	if d.present&depositpreauthBitPreviousTxnLgrSeq != 0 {
		seq = d.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (d *DepositPreauth) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "DepositPreauth",
	}
	if d.present&depositpreauthBitAccount != 0 {
		out["Account"] = d.Account
	}
	if d.present&depositpreauthBitAuthorize != 0 {
		out["Authorize"] = d.Authorize
	}
	if d.present&depositpreauthBitOwnerNode != 0 {
		out["OwnerNode"] = d.OwnerNode
	}
	if d.present&depositpreauthBitAuthorizeCredentials != 0 {
		out["AuthorizeCredentials"] = d.AuthorizeCredentials
	}
	if d.present&depositpreauthBitFlags != 0 {
		out["Flags"] = d.Flags
	}
	if d.present&depositpreauthBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = d.PreviousTxnID
	}
	if d.present&depositpreauthBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = d.PreviousTxnLgrSeq
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Round-trip
// invariant: Decode(data); Encode() == data for any byte sequence that
// Decode accepts.
func (d *DepositPreauth) Encode() ([]byte, error) {
	return binarycodec.EncodeBytes(d.ToMap())
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (d *DepositPreauth) Hash(index [32]byte) ([32]byte, error) {
	data, err := d.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode
	return common.Sha512Half(prefix[:], data, index[:]), nil
}
