// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

func init() {
	Register("DirectoryNode", func() Entry { return new(DirectoryNode) })
}

// DirectoryNode is the typed representation of a DirectoryNode ledger entry
// on the metadata hot path. present tracks which fields appear on the
// decoded blob so the emit methods only write entries that actually exist.
type DirectoryNode struct {
	present           uint64
	Flags             uint32
	RootIndex         string // Hash256 (uppercase hex)
	IndexNext         string // UInt64 (uppercase hex)
	IndexPrevious     string // UInt64 (uppercase hex)
	Owner             string // AccountID (base58)
	TakerPaysCurrency string // Hash160 (uppercase hex)
	TakerPaysIssuer   string // Hash160 (uppercase hex)
	TakerGetsCurrency string // Hash160 (uppercase hex)
	TakerGetsIssuer   string // Hash160 (uppercase hex)
	ExchangeRate      string // UInt64 (uppercase hex)
	NFTokenID         string // Hash256 (uppercase hex)
	DomainID          string // Hash256 (uppercase hex)
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
}

const (
	dnBitFlags uint64 = 1 << iota
	dnBitRootIndex
	dnBitIndexes
	dnBitIndexNext
	dnBitIndexPrevious
	dnBitOwner
	dnBitTakerPaysCurrency
	dnBitTakerPaysIssuer
	dnBitTakerGetsCurrency
	dnBitTakerGetsIssuer
	dnBitExchangeRate
	dnBitNFTokenID
	dnBitDomainID
	dnBitPreviousTxnID
	dnBitPreviousTxnLgrSeq
)

// Decode populates the struct from binary ledger-entry data via a streaming
// reader. Unknown / sMD_Never fields are skipped without allocation.
func (d *DirectoryNode) Decode(data []byte) error {
	*d = DirectoryNode{}
	sr := newStreamReader(data)
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		switch typeCode {
		case 1: // UInt16 — LedgerEntryType is the only AccountRoot/Offer/etc. UInt16 and is sMD_Never; discard.
			if _, err := sr.readUint16(); err != nil {
				return err
			}
		case 2: // UInt32
			v, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				d.Flags = v
				d.present |= dnBitFlags
			case 5:
				d.PreviousTxnLgrSeq = v
				d.present |= dnBitPreviousTxnLgrSeq
			default:
				_ = v
			}
		case 3: // UInt64
			v, err := sr.readUint64Hex()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				d.IndexNext = v
				d.present |= dnBitIndexNext
			case 2:
				d.IndexPrevious = v
				d.present |= dnBitIndexPrevious
			case 6:
				d.ExchangeRate = v
				d.present |= dnBitExchangeRate
			default:
				_ = v
			}
		case 5: // Hash256
			v, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				d.PreviousTxnID = v
				d.present |= dnBitPreviousTxnID
			case 8:
				d.RootIndex = v
				d.present |= dnBitRootIndex
			case 10:
				d.NFTokenID = v
				d.present |= dnBitNFTokenID
			case 34:
				d.DomainID = v
				d.present |= dnBitDomainID
			default:
				_ = v
			}
		case 8: // AccountID
			v, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				d.Owner = v
				d.present |= dnBitOwner
			default:
				_ = v
			}
		case 17: // Hash160
			v, err := sr.readHash(20)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				d.TakerPaysCurrency = v
				d.present |= dnBitTakerPaysCurrency
			case 2:
				d.TakerPaysIssuer = v
				d.present |= dnBitTakerPaysIssuer
			case 3:
				d.TakerGetsCurrency = v
				d.present |= dnBitTakerGetsCurrency
			case 4:
				d.TakerGetsIssuer = v
				d.present |= dnBitTakerGetsIssuer
			default:
				_ = v
			}
		default:
			if err := sr.skipField(typeCode); err != nil {
				return err
			}
		}
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (d *DirectoryNode) emitAll(out map[string]any, skipDefault bool) {
	if d.present&dnBitFlags != 0 && !(skipDefault && d.Flags == 0) {
		out["Flags"] = d.Flags
	}
	if d.present&dnBitIndexNext != 0 && !(skipDefault && isZeroHexString(d.IndexNext)) {
		out["IndexNext"] = d.IndexNext
	}
	if d.present&dnBitIndexPrevious != 0 && !(skipDefault && isZeroHexString(d.IndexPrevious)) {
		out["IndexPrevious"] = d.IndexPrevious
	}
	if d.present&dnBitOwner != 0 && !(skipDefault && d.Owner == "") {
		out["Owner"] = d.Owner
	}
	if d.present&dnBitTakerPaysCurrency != 0 && !(skipDefault && isZeroHexString(d.TakerPaysCurrency)) {
		out["TakerPaysCurrency"] = d.TakerPaysCurrency
	}
	if d.present&dnBitTakerPaysIssuer != 0 && !(skipDefault && isZeroHexString(d.TakerPaysIssuer)) {
		out["TakerPaysIssuer"] = d.TakerPaysIssuer
	}
	if d.present&dnBitTakerGetsCurrency != 0 && !(skipDefault && isZeroHexString(d.TakerGetsCurrency)) {
		out["TakerGetsCurrency"] = d.TakerGetsCurrency
	}
	if d.present&dnBitTakerGetsIssuer != 0 && !(skipDefault && isZeroHexString(d.TakerGetsIssuer)) {
		out["TakerGetsIssuer"] = d.TakerGetsIssuer
	}
	if d.present&dnBitExchangeRate != 0 && !(skipDefault && isZeroHexString(d.ExchangeRate)) {
		out["ExchangeRate"] = d.ExchangeRate
	}
	if d.present&dnBitNFTokenID != 0 && !(skipDefault && isZeroHexString(d.NFTokenID)) {
		out["NFTokenID"] = d.NFTokenID
	}
	if d.present&dnBitDomainID != 0 && !(skipDefault && isZeroHexString(d.DomainID)) {
		out["DomainID"] = d.DomainID
	}
	if d.present&dnBitRootIndex != 0 {
		out["RootIndex"] = d.RootIndex
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (d *DirectoryNode) EmitNewFields(out map[string]any) {
	d.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (d *DirectoryNode) EmitFinalFields(out map[string]any) {
	d.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig).
func (d *DirectoryNode) EmitPreviousFields(prev Entry, out map[string]any) {
	p, ok := prev.(*DirectoryNode)
	if !ok || p == nil {
		return
	}
	emitIfChangedUint32(out, "Flags", p.Flags, d.Flags, p.present&dnBitFlags, d.present&dnBitFlags)
	emitIfChangedString(out, "RootIndex", p.RootIndex, d.RootIndex, p.present&dnBitRootIndex, d.present&dnBitRootIndex)
	emitIfChangedString(out, "IndexNext", p.IndexNext, d.IndexNext, p.present&dnBitIndexNext, d.present&dnBitIndexNext)
	emitIfChangedString(out, "IndexPrevious", p.IndexPrevious, d.IndexPrevious, p.present&dnBitIndexPrevious, d.present&dnBitIndexPrevious)
	emitIfChangedString(out, "Owner", p.Owner, d.Owner, p.present&dnBitOwner, d.present&dnBitOwner)
	emitIfChangedString(out, "TakerPaysCurrency", p.TakerPaysCurrency, d.TakerPaysCurrency, p.present&dnBitTakerPaysCurrency, d.present&dnBitTakerPaysCurrency)
	emitIfChangedString(out, "TakerPaysIssuer", p.TakerPaysIssuer, d.TakerPaysIssuer, p.present&dnBitTakerPaysIssuer, d.present&dnBitTakerPaysIssuer)
	emitIfChangedString(out, "TakerGetsCurrency", p.TakerGetsCurrency, d.TakerGetsCurrency, p.present&dnBitTakerGetsCurrency, d.present&dnBitTakerGetsCurrency)
	emitIfChangedString(out, "TakerGetsIssuer", p.TakerGetsIssuer, d.TakerGetsIssuer, p.present&dnBitTakerGetsIssuer, d.present&dnBitTakerGetsIssuer)
	emitIfChangedString(out, "ExchangeRate", p.ExchangeRate, d.ExchangeRate, p.present&dnBitExchangeRate, d.present&dnBitExchangeRate)
	emitIfChangedString(out, "NFTokenID", p.NFTokenID, d.NFTokenID, p.present&dnBitNFTokenID, d.present&dnBitNFTokenID)
	emitIfChangedString(out, "DomainID", p.DomainID, d.DomainID, p.present&dnBitDomainID, d.present&dnBitDomainID)
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (d *DirectoryNode) EmitDeleteFinalFields(out map[string]any) {
	d.emitAll(out, false)
	if d.present&dnBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = d.PreviousTxnID
	}
	if d.present&dnBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = d.PreviousTxnLgrSeq
	}
}

// EmitDeletePreviousFields mirrors EmitPreviousFields for DeletedNode.
func (d *DirectoryNode) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	d.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (d *DirectoryNode) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if d.present&dnBitPreviousTxnID != 0 {
		id = d.PreviousTxnID
	}
	if d.present&dnBitPreviousTxnLgrSeq != 0 {
		seq = d.PreviousTxnLgrSeq
	}
	return id, seq
}
