// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

import (
	"github.com/LeJamon/go-xrpl/codec/binarycodec"
	"github.com/LeJamon/go-xrpl/crypto/common"
	"github.com/LeJamon/go-xrpl/protocol"
)

func init() {
	Register("LoanBroker", func() Entry { return new(LoanBroker) })
}

// LoanBroker is the typed representation of a LoanBroker ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every on-wire field — including those excluded from metadata
// (sMD_Never) — so Decode → Encode is byte-identical.
type LoanBroker struct {
	present              uint64
	Sequence             uint32
	OwnerNode            string // UInt64 (lowercase hex, no leading zeros)
	VaultNode            string // UInt64 (lowercase hex, no leading zeros)
	VaultID              string // Hash256 (uppercase hex)
	Account              string // AccountID (base58)
	Owner                string // AccountID (base58)
	LoanSequence         uint32
	Data                 string // Blob (uppercase hex)
	ManagementFeeRate    int
	OwnerCount           uint32
	DebtTotal            any
	DebtMaximum          any
	CoverAvailable       any
	CoverRateMinimum     uint32
	CoverRateLiquidation uint32
	Flags                uint32
	PreviousTxnID        string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq    uint32
}

const (
	loanbrokerBitSequence uint64 = 1 << iota
	loanbrokerBitOwnerNode
	loanbrokerBitVaultNode
	loanbrokerBitVaultID
	loanbrokerBitAccount
	loanbrokerBitOwner
	loanbrokerBitLoanSequence
	loanbrokerBitData
	loanbrokerBitManagementFeeRate
	loanbrokerBitOwnerCount
	loanbrokerBitDebtTotal
	loanbrokerBitDebtMaximum
	loanbrokerBitCoverAvailable
	loanbrokerBitCoverRateMinimum
	loanbrokerBitCoverRateLiquidation
	loanbrokerBitFlags
	loanbrokerBitPreviousTxnID
	loanbrokerBitPreviousTxnLgrSeq
)

// Decode populates the struct from binary ledger-entry data via a streaming
// reader. Unknown / sMD_Never fields are skipped without allocation.
func (l *LoanBroker) Decode(data []byte) error {
	*l = LoanBroker{}
	sr := newStreamReader(data)
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				_ = val // synthetic LedgerEntryType; discard
			case 22:
				l.ManagementFeeRate = val
				l.present |= loanbrokerBitManagementFeeRate
			default:
				return newErrUnknownField("LoanBroker", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				l.Flags = val
				l.present |= loanbrokerBitFlags
			case 4:
				l.Sequence = val
				l.present |= loanbrokerBitSequence
			case 5:
				l.PreviousTxnLgrSeq = val
				l.present |= loanbrokerBitPreviousTxnLgrSeq
			case 13:
				l.OwnerCount = val
				l.present |= loanbrokerBitOwnerCount
			case 61:
				l.LoanSequence = val
				l.present |= loanbrokerBitLoanSequence
			case 62:
				l.CoverRateMinimum = val
				l.present |= loanbrokerBitCoverRateMinimum
			case 63:
				l.CoverRateLiquidation = val
				l.present |= loanbrokerBitCoverRateLiquidation
			default:
				return newErrUnknownField("LoanBroker", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 4:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				l.OwnerNode = val
				l.present |= loanbrokerBitOwnerNode
			case 30:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				l.VaultNode = val
				l.present |= loanbrokerBitVaultNode
			default:
				return newErrUnknownField("LoanBroker", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				l.PreviousTxnID = val
				l.present |= loanbrokerBitPreviousTxnID
			case 35:
				l.VaultID = val
				l.present |= loanbrokerBitVaultID
			default:
				return newErrUnknownField("LoanBroker", typeCode, fieldCode)
			}
		case 7: // Blob
			val, err := sr.readBlobHex()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 27:
				l.Data = val
				l.present |= loanbrokerBitData
			default:
				return newErrUnknownField("LoanBroker", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				l.Account = val
				l.present |= loanbrokerBitAccount
			case 2:
				l.Owner = val
				l.present |= loanbrokerBitOwner
			default:
				return newErrUnknownField("LoanBroker", typeCode, fieldCode)
			}
		case 9: // Number
			val, err := sr.readNumber()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 6:
				l.DebtTotal = val
				l.present |= loanbrokerBitDebtTotal
			case 7:
				l.DebtMaximum = val
				l.present |= loanbrokerBitDebtMaximum
			case 8:
				l.CoverAvailable = val
				l.present |= loanbrokerBitCoverAvailable
			default:
				return newErrUnknownField("LoanBroker", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("LoanBroker", typeCode, fieldCode)
		}
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (l *LoanBroker) emitAll(out map[string]any, skipDefault bool) {
	if l.present&loanbrokerBitSequence != 0 && !(skipDefault && l.Sequence == 0) {
		out["Sequence"] = l.Sequence
	}
	if l.present&loanbrokerBitOwnerNode != 0 && !(skipDefault && isZeroHexString(l.OwnerNode)) {
		out["OwnerNode"] = l.OwnerNode
	}
	if l.present&loanbrokerBitVaultNode != 0 && !(skipDefault && isZeroHexString(l.VaultNode)) {
		out["VaultNode"] = l.VaultNode
	}
	if l.present&loanbrokerBitVaultID != 0 && !(skipDefault && isZeroHexString(l.VaultID)) {
		out["VaultID"] = l.VaultID
	}
	if l.present&loanbrokerBitAccount != 0 && !(skipDefault && l.Account == "") {
		out["Account"] = l.Account
	}
	if l.present&loanbrokerBitOwner != 0 && !(skipDefault && l.Owner == "") {
		out["Owner"] = l.Owner
	}
	if l.present&loanbrokerBitLoanSequence != 0 && !(skipDefault && l.LoanSequence == 0) {
		out["LoanSequence"] = l.LoanSequence
	}
	if l.present&loanbrokerBitData != 0 && !(skipDefault && l.Data == "") {
		out["Data"] = l.Data
	}
	if l.present&loanbrokerBitManagementFeeRate != 0 && !(skipDefault && l.ManagementFeeRate == 0) {
		out["ManagementFeeRate"] = l.ManagementFeeRate
	}
	if l.present&loanbrokerBitOwnerCount != 0 && !(skipDefault && l.OwnerCount == 0) {
		out["OwnerCount"] = l.OwnerCount
	}
	if l.present&loanbrokerBitDebtTotal != 0 && !(skipDefault && numberIsDefault(l.DebtTotal)) {
		out["DebtTotal"] = l.DebtTotal
	}
	if l.present&loanbrokerBitDebtMaximum != 0 && !(skipDefault && numberIsDefault(l.DebtMaximum)) {
		out["DebtMaximum"] = l.DebtMaximum
	}
	if l.present&loanbrokerBitCoverAvailable != 0 && !(skipDefault && numberIsDefault(l.CoverAvailable)) {
		out["CoverAvailable"] = l.CoverAvailable
	}
	if l.present&loanbrokerBitCoverRateMinimum != 0 && !(skipDefault && l.CoverRateMinimum == 0) {
		out["CoverRateMinimum"] = l.CoverRateMinimum
	}
	if l.present&loanbrokerBitCoverRateLiquidation != 0 && !(skipDefault && l.CoverRateLiquidation == 0) {
		out["CoverRateLiquidation"] = l.CoverRateLiquidation
	}
	if l.present&loanbrokerBitFlags != 0 && !(skipDefault && l.Flags == 0) {
		out["Flags"] = l.Flags
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (l *LoanBroker) EmitNewFields(out map[string]any) {
	l.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (l *LoanBroker) EmitFinalFields(out map[string]any) {
	l.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (l *LoanBroker) EmitPreviousFields(prev Entry, out map[string]any) {
	prv, ok := prev.(*LoanBroker)
	if !ok || prv == nil {
		return
	}
	emitIfChangedUint32(out, "Sequence", prv.Sequence, l.Sequence, prv.present&loanbrokerBitSequence, l.present&loanbrokerBitSequence)
	emitIfChangedString(out, "OwnerNode", prv.OwnerNode, l.OwnerNode, prv.present&loanbrokerBitOwnerNode, l.present&loanbrokerBitOwnerNode)
	emitIfChangedString(out, "VaultNode", prv.VaultNode, l.VaultNode, prv.present&loanbrokerBitVaultNode, l.present&loanbrokerBitVaultNode)
	emitIfChangedString(out, "VaultID", prv.VaultID, l.VaultID, prv.present&loanbrokerBitVaultID, l.present&loanbrokerBitVaultID)
	emitIfChangedString(out, "Account", prv.Account, l.Account, prv.present&loanbrokerBitAccount, l.present&loanbrokerBitAccount)
	emitIfChangedString(out, "Owner", prv.Owner, l.Owner, prv.present&loanbrokerBitOwner, l.present&loanbrokerBitOwner)
	emitIfChangedUint32(out, "LoanSequence", prv.LoanSequence, l.LoanSequence, prv.present&loanbrokerBitLoanSequence, l.present&loanbrokerBitLoanSequence)
	emitIfChangedString(out, "Data", prv.Data, l.Data, prv.present&loanbrokerBitData, l.present&loanbrokerBitData)
	emitIfChangedInt(out, "ManagementFeeRate", prv.ManagementFeeRate, l.ManagementFeeRate, prv.present&loanbrokerBitManagementFeeRate, l.present&loanbrokerBitManagementFeeRate)
	emitIfChangedUint32(out, "OwnerCount", prv.OwnerCount, l.OwnerCount, prv.present&loanbrokerBitOwnerCount, l.present&loanbrokerBitOwnerCount)
	emitIfChangedDeep(out, "DebtTotal", prv.DebtTotal, l.DebtTotal, prv.present&loanbrokerBitDebtTotal, l.present&loanbrokerBitDebtTotal)
	emitIfChangedDeep(out, "DebtMaximum", prv.DebtMaximum, l.DebtMaximum, prv.present&loanbrokerBitDebtMaximum, l.present&loanbrokerBitDebtMaximum)
	emitIfChangedDeep(out, "CoverAvailable", prv.CoverAvailable, l.CoverAvailable, prv.present&loanbrokerBitCoverAvailable, l.present&loanbrokerBitCoverAvailable)
	emitIfChangedUint32(out, "CoverRateMinimum", prv.CoverRateMinimum, l.CoverRateMinimum, prv.present&loanbrokerBitCoverRateMinimum, l.present&loanbrokerBitCoverRateMinimum)
	emitIfChangedUint32(out, "CoverRateLiquidation", prv.CoverRateLiquidation, l.CoverRateLiquidation, prv.present&loanbrokerBitCoverRateLiquidation, l.present&loanbrokerBitCoverRateLiquidation)
	emitIfChangedUint32(out, "Flags", prv.Flags, l.Flags, prv.present&loanbrokerBitFlags, l.present&loanbrokerBitFlags)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (l *LoanBroker) EmitChangeOrigFields(out map[string]any) {
	if l.present&loanbrokerBitSequence != 0 {
		out["Sequence"] = l.Sequence
	}
	if l.present&loanbrokerBitOwnerNode != 0 {
		out["OwnerNode"] = l.OwnerNode
	}
	if l.present&loanbrokerBitVaultNode != 0 {
		out["VaultNode"] = l.VaultNode
	}
	if l.present&loanbrokerBitVaultID != 0 {
		out["VaultID"] = l.VaultID
	}
	if l.present&loanbrokerBitAccount != 0 {
		out["Account"] = l.Account
	}
	if l.present&loanbrokerBitOwner != 0 {
		out["Owner"] = l.Owner
	}
	if l.present&loanbrokerBitLoanSequence != 0 {
		out["LoanSequence"] = l.LoanSequence
	}
	if l.present&loanbrokerBitData != 0 {
		out["Data"] = l.Data
	}
	if l.present&loanbrokerBitManagementFeeRate != 0 {
		out["ManagementFeeRate"] = l.ManagementFeeRate
	}
	if l.present&loanbrokerBitOwnerCount != 0 {
		out["OwnerCount"] = l.OwnerCount
	}
	if l.present&loanbrokerBitDebtTotal != 0 {
		out["DebtTotal"] = l.DebtTotal
	}
	if l.present&loanbrokerBitDebtMaximum != 0 {
		out["DebtMaximum"] = l.DebtMaximum
	}
	if l.present&loanbrokerBitCoverAvailable != 0 {
		out["CoverAvailable"] = l.CoverAvailable
	}
	if l.present&loanbrokerBitCoverRateMinimum != 0 {
		out["CoverRateMinimum"] = l.CoverRateMinimum
	}
	if l.present&loanbrokerBitCoverRateLiquidation != 0 {
		out["CoverRateLiquidation"] = l.CoverRateLiquidation
	}
	if l.present&loanbrokerBitFlags != 0 {
		out["Flags"] = l.Flags
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (l *LoanBroker) EmitDeleteFinalFields(out map[string]any) {
	l.emitAll(out, false)
	if l.present&loanbrokerBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = l.PreviousTxnID
	}
	if l.present&loanbrokerBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = l.PreviousTxnLgrSeq
	}
}

func (l *LoanBroker) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	l.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (l *LoanBroker) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if l.present&loanbrokerBitPreviousTxnID != 0 {
		id = l.PreviousTxnID
	}
	if l.present&loanbrokerBitPreviousTxnLgrSeq != 0 {
		seq = l.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (l *LoanBroker) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "LoanBroker",
	}
	if l.present&loanbrokerBitSequence != 0 {
		out["Sequence"] = l.Sequence
	}
	if l.present&loanbrokerBitOwnerNode != 0 {
		out["OwnerNode"] = l.OwnerNode
	}
	if l.present&loanbrokerBitVaultNode != 0 {
		out["VaultNode"] = l.VaultNode
	}
	if l.present&loanbrokerBitVaultID != 0 {
		out["VaultID"] = l.VaultID
	}
	if l.present&loanbrokerBitAccount != 0 {
		out["Account"] = l.Account
	}
	if l.present&loanbrokerBitOwner != 0 {
		out["Owner"] = l.Owner
	}
	if l.present&loanbrokerBitLoanSequence != 0 {
		out["LoanSequence"] = l.LoanSequence
	}
	if l.present&loanbrokerBitData != 0 {
		out["Data"] = l.Data
	}
	if l.present&loanbrokerBitManagementFeeRate != 0 {
		out["ManagementFeeRate"] = l.ManagementFeeRate
	}
	if l.present&loanbrokerBitOwnerCount != 0 {
		out["OwnerCount"] = l.OwnerCount
	}
	if l.present&loanbrokerBitDebtTotal != 0 {
		out["DebtTotal"] = l.DebtTotal
	}
	if l.present&loanbrokerBitDebtMaximum != 0 {
		out["DebtMaximum"] = l.DebtMaximum
	}
	if l.present&loanbrokerBitCoverAvailable != 0 {
		out["CoverAvailable"] = l.CoverAvailable
	}
	if l.present&loanbrokerBitCoverRateMinimum != 0 {
		out["CoverRateMinimum"] = l.CoverRateMinimum
	}
	if l.present&loanbrokerBitCoverRateLiquidation != 0 {
		out["CoverRateLiquidation"] = l.CoverRateLiquidation
	}
	if l.present&loanbrokerBitFlags != 0 {
		out["Flags"] = l.Flags
	}
	if l.present&loanbrokerBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = l.PreviousTxnID
	}
	if l.present&loanbrokerBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = l.PreviousTxnLgrSeq
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Round-trip
// invariant: Decode(data); Encode() == data for any byte sequence that
// Decode accepts.
func (l *LoanBroker) Encode() ([]byte, error) {
	return binarycodec.EncodeBytes(l.ToMap())
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (l *LoanBroker) Hash(index [32]byte) ([32]byte, error) {
	data, err := l.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode()
	return common.Sha512Half(prefix[:], data, index[:]), nil
}
