// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

import (
	"github.com/LeJamon/go-xrpl/codec/binarycodec"
	"github.com/LeJamon/go-xrpl/crypto/common"
	"github.com/LeJamon/go-xrpl/protocol"
)

func init() {
	Register("MPToken", func() Entry { return new(MPToken) })
}

// MPToken is the typed representation of a MPToken ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every on-wire field — including those excluded from metadata
// (sMD_Never) — so Decode → Encode is byte-identical.
type MPToken struct {
	present           uint64
	Account           string // AccountID (base58)
	Issuer            string // AccountID (base58)
	Sequence          uint32
	MPTokenIssuanceID string
	MPTAmount         string // UInt64 (decimal string, sMD_BaseTen)
	LockedAmount      string // UInt64 (decimal string, sMD_BaseTen)
	OwnerNode         string // UInt64 (lowercase hex, no leading zeros)
	Flags             uint32
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
}

const (
	mptokenBitAccount uint64 = 1 << iota
	mptokenBitIssuer
	mptokenBitSequence
	mptokenBitMPTokenIssuanceID
	mptokenBitMPTAmount
	mptokenBitLockedAmount
	mptokenBitOwnerNode
	mptokenBitFlags
	mptokenBitPreviousTxnID
	mptokenBitPreviousTxnLgrSeq
)

// Decode populates the struct from binary ledger-entry data via a streaming
// reader. Unknown / sMD_Never fields are skipped without allocation.
func (m *MPToken) Decode(data []byte) error {
	*m = MPToken{}
	sr := newStreamReader(data)
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				_ = val // synthetic LedgerEntryType; discard
			default:
				return newErrUnknownField("MPToken", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				m.Flags = val
				m.present |= mptokenBitFlags
			case 4:
				m.Sequence = val
				m.present |= mptokenBitSequence
			case 5:
				m.PreviousTxnLgrSeq = val
				m.present |= mptokenBitPreviousTxnLgrSeq
			default:
				return newErrUnknownField("MPToken", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 4:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				m.OwnerNode = val
				m.present |= mptokenBitOwnerNode
			case 26:
				val, err := sr.readUint64Decimal()
				if err != nil {
					return err
				}
				m.MPTAmount = val
				m.present |= mptokenBitMPTAmount
			case 29:
				val, err := sr.readUint64Decimal()
				if err != nil {
					return err
				}
				m.LockedAmount = val
				m.present |= mptokenBitLockedAmount
			default:
				return newErrUnknownField("MPToken", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				m.PreviousTxnID = val
				m.present |= mptokenBitPreviousTxnID
			default:
				return newErrUnknownField("MPToken", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				m.Account = val
				m.present |= mptokenBitAccount
			case 4:
				m.Issuer = val
				m.present |= mptokenBitIssuer
			default:
				return newErrUnknownField("MPToken", typeCode, fieldCode)
			}
		case 21: // Hash192
			val, err := sr.readHash(24)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				m.MPTokenIssuanceID = val
				m.present |= mptokenBitMPTokenIssuanceID
			default:
				return newErrUnknownField("MPToken", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("MPToken", typeCode, fieldCode)
		}
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (m *MPToken) emitAll(out map[string]any, skipDefault bool) {
	if m.present&mptokenBitAccount != 0 && !(skipDefault && m.Account == "") {
		out["Account"] = m.Account
	}
	if m.present&mptokenBitIssuer != 0 && !(skipDefault && m.Issuer == "") {
		out["Issuer"] = m.Issuer
	}
	if m.present&mptokenBitSequence != 0 && !(skipDefault && m.Sequence == 0) {
		out["Sequence"] = m.Sequence
	}
	if m.present&mptokenBitMPTokenIssuanceID != 0 && !(skipDefault && isZeroHexString(m.MPTokenIssuanceID)) {
		out["MPTokenIssuanceID"] = m.MPTokenIssuanceID
	}
	if m.present&mptokenBitMPTAmount != 0 && !(skipDefault && isZeroHexString(m.MPTAmount)) {
		out["MPTAmount"] = m.MPTAmount
	}
	if m.present&mptokenBitLockedAmount != 0 && !(skipDefault && isZeroHexString(m.LockedAmount)) {
		out["LockedAmount"] = m.LockedAmount
	}
	if m.present&mptokenBitOwnerNode != 0 && !(skipDefault && isZeroHexString(m.OwnerNode)) {
		out["OwnerNode"] = m.OwnerNode
	}
	if m.present&mptokenBitFlags != 0 && !(skipDefault && m.Flags == 0) {
		out["Flags"] = m.Flags
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (m *MPToken) EmitNewFields(out map[string]any) {
	m.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (m *MPToken) EmitFinalFields(out map[string]any) {
	m.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (m *MPToken) EmitPreviousFields(prev Entry, out map[string]any) {
	prv, ok := prev.(*MPToken)
	if !ok || prv == nil {
		return
	}
	emitIfChangedString(out, "Account", prv.Account, m.Account, prv.present&mptokenBitAccount, m.present&mptokenBitAccount)
	emitIfChangedString(out, "Issuer", prv.Issuer, m.Issuer, prv.present&mptokenBitIssuer, m.present&mptokenBitIssuer)
	emitIfChangedUint32(out, "Sequence", prv.Sequence, m.Sequence, prv.present&mptokenBitSequence, m.present&mptokenBitSequence)
	emitIfChangedString(out, "MPTokenIssuanceID", prv.MPTokenIssuanceID, m.MPTokenIssuanceID, prv.present&mptokenBitMPTokenIssuanceID, m.present&mptokenBitMPTokenIssuanceID)
	emitIfChangedString(out, "MPTAmount", prv.MPTAmount, m.MPTAmount, prv.present&mptokenBitMPTAmount, m.present&mptokenBitMPTAmount)
	emitIfChangedString(out, "LockedAmount", prv.LockedAmount, m.LockedAmount, prv.present&mptokenBitLockedAmount, m.present&mptokenBitLockedAmount)
	emitIfChangedString(out, "OwnerNode", prv.OwnerNode, m.OwnerNode, prv.present&mptokenBitOwnerNode, m.present&mptokenBitOwnerNode)
	emitIfChangedUint32(out, "Flags", prv.Flags, m.Flags, prv.present&mptokenBitFlags, m.present&mptokenBitFlags)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (m *MPToken) EmitChangeOrigFields(out map[string]any) {
	if m.present&mptokenBitAccount != 0 {
		out["Account"] = m.Account
	}
	if m.present&mptokenBitIssuer != 0 {
		out["Issuer"] = m.Issuer
	}
	if m.present&mptokenBitSequence != 0 {
		out["Sequence"] = m.Sequence
	}
	if m.present&mptokenBitMPTokenIssuanceID != 0 {
		out["MPTokenIssuanceID"] = m.MPTokenIssuanceID
	}
	if m.present&mptokenBitMPTAmount != 0 {
		out["MPTAmount"] = m.MPTAmount
	}
	if m.present&mptokenBitLockedAmount != 0 {
		out["LockedAmount"] = m.LockedAmount
	}
	if m.present&mptokenBitOwnerNode != 0 {
		out["OwnerNode"] = m.OwnerNode
	}
	if m.present&mptokenBitFlags != 0 {
		out["Flags"] = m.Flags
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (m *MPToken) EmitDeleteFinalFields(out map[string]any) {
	m.emitAll(out, false)
	if m.present&mptokenBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = m.PreviousTxnID
	}
	if m.present&mptokenBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = m.PreviousTxnLgrSeq
	}
}

func (m *MPToken) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	m.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (m *MPToken) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if m.present&mptokenBitPreviousTxnID != 0 {
		id = m.PreviousTxnID
	}
	if m.present&mptokenBitPreviousTxnLgrSeq != 0 {
		seq = m.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (m *MPToken) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "MPToken",
	}
	if m.present&mptokenBitAccount != 0 {
		out["Account"] = m.Account
	}
	if m.present&mptokenBitIssuer != 0 {
		out["Issuer"] = m.Issuer
	}
	if m.present&mptokenBitSequence != 0 {
		out["Sequence"] = m.Sequence
	}
	if m.present&mptokenBitMPTokenIssuanceID != 0 {
		out["MPTokenIssuanceID"] = m.MPTokenIssuanceID
	}
	if m.present&mptokenBitMPTAmount != 0 {
		out["MPTAmount"] = m.MPTAmount
	}
	if m.present&mptokenBitLockedAmount != 0 {
		out["LockedAmount"] = m.LockedAmount
	}
	if m.present&mptokenBitOwnerNode != 0 {
		out["OwnerNode"] = m.OwnerNode
	}
	if m.present&mptokenBitFlags != 0 {
		out["Flags"] = m.Flags
	}
	if m.present&mptokenBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = m.PreviousTxnID
	}
	if m.present&mptokenBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = m.PreviousTxnLgrSeq
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Round-trip
// invariant: Decode(data); Encode() == data for any byte sequence that
// Decode accepts.
func (m *MPToken) Encode() ([]byte, error) {
	return binarycodec.EncodeBytes(m.ToMap())
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (m *MPToken) Hash(index [32]byte) ([32]byte, error) {
	data, err := m.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode
	return common.Sha512Half(prefix[:], data, index[:]), nil
}
