// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

import (
	"github.com/LeJamon/go-xrpl/codec/binarycodec"
	"github.com/LeJamon/go-xrpl/crypto/common"
	"github.com/LeJamon/go-xrpl/protocol"
)

func init() {
	Register("NegativeUNL", func() Entry { return new(NegativeUNL) })
}

// NegativeUNL is the typed representation of a NegativeUNL ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every on-wire field — including those excluded from metadata
// (sMD_Never) — so Decode → Encode is byte-identical.
type NegativeUNL struct {
	present             uint64
	Flags               uint32
	DisabledValidators  []any
	ValidatorToDisable  string // Blob (uppercase hex)
	ValidatorToReEnable string // Blob (uppercase hex)
	PreviousTxnID       string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq   uint32
}

const (
	negativeunlBitFlags uint64 = 1 << iota
	negativeunlBitDisabledValidators
	negativeunlBitValidatorToDisable
	negativeunlBitValidatorToReEnable
	negativeunlBitPreviousTxnID
	negativeunlBitPreviousTxnLgrSeq
)

// Decode populates the struct from binary ledger-entry data via a streaming
// reader. Unknown / sMD_Never fields are skipped without allocation.
func (n *NegativeUNL) Decode(data []byte) error {
	*n = NegativeUNL{}
	sr := newStreamReader(data)
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				_ = val // synthetic LedgerEntryType; discard
			default:
				return newErrUnknownField("NegativeUNL", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				n.Flags = val
				n.present |= negativeunlBitFlags
			case 5:
				n.PreviousTxnLgrSeq = val
				n.present |= negativeunlBitPreviousTxnLgrSeq
			default:
				return newErrUnknownField("NegativeUNL", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				n.PreviousTxnID = val
				n.present |= negativeunlBitPreviousTxnID
			default:
				return newErrUnknownField("NegativeUNL", typeCode, fieldCode)
			}
		case 7: // Blob
			val, err := sr.readBlobHex()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 20:
				n.ValidatorToDisable = val
				n.present |= negativeunlBitValidatorToDisable
			case 21:
				n.ValidatorToReEnable = val
				n.present |= negativeunlBitValidatorToReEnable
			default:
				return newErrUnknownField("NegativeUNL", typeCode, fieldCode)
			}
		case 15: // STArray
			val, err := sr.readSTArray()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 17:
				n.DisabledValidators = val
				n.present |= negativeunlBitDisabledValidators
			default:
				return newErrUnknownField("NegativeUNL", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("NegativeUNL", typeCode, fieldCode)
		}
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (n *NegativeUNL) emitAll(out map[string]any, skipDefault bool) {
	if n.present&negativeunlBitFlags != 0 && !(skipDefault && n.Flags == 0) {
		out["Flags"] = n.Flags
	}
	if n.present&negativeunlBitDisabledValidators != 0 {
		out["DisabledValidators"] = n.DisabledValidators
	}
	if n.present&negativeunlBitValidatorToDisable != 0 && !(skipDefault && n.ValidatorToDisable == "") {
		out["ValidatorToDisable"] = n.ValidatorToDisable
	}
	if n.present&negativeunlBitValidatorToReEnable != 0 && !(skipDefault && n.ValidatorToReEnable == "") {
		out["ValidatorToReEnable"] = n.ValidatorToReEnable
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (n *NegativeUNL) EmitNewFields(out map[string]any) {
	n.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (n *NegativeUNL) EmitFinalFields(out map[string]any) {
	n.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (n *NegativeUNL) EmitPreviousFields(prev Entry, out map[string]any) {
	p, ok := prev.(*NegativeUNL)
	if !ok || p == nil {
		return
	}
	emitIfChangedUint32(out, "Flags", p.Flags, n.Flags, p.present&negativeunlBitFlags, n.present&negativeunlBitFlags)
	emitIfChangedDeep(out, "DisabledValidators", p.DisabledValidators, n.DisabledValidators, p.present&negativeunlBitDisabledValidators, n.present&negativeunlBitDisabledValidators)
	emitIfChangedString(out, "ValidatorToDisable", p.ValidatorToDisable, n.ValidatorToDisable, p.present&negativeunlBitValidatorToDisable, n.present&negativeunlBitValidatorToDisable)
	emitIfChangedString(out, "ValidatorToReEnable", p.ValidatorToReEnable, n.ValidatorToReEnable, p.present&negativeunlBitValidatorToReEnable, n.present&negativeunlBitValidatorToReEnable)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (n *NegativeUNL) EmitChangeOrigFields(out map[string]any) {
	if n.present&negativeunlBitFlags != 0 {
		out["Flags"] = n.Flags
	}
	if n.present&negativeunlBitDisabledValidators != 0 {
		out["DisabledValidators"] = n.DisabledValidators
	}
	if n.present&negativeunlBitValidatorToDisable != 0 {
		out["ValidatorToDisable"] = n.ValidatorToDisable
	}
	if n.present&negativeunlBitValidatorToReEnable != 0 {
		out["ValidatorToReEnable"] = n.ValidatorToReEnable
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (n *NegativeUNL) EmitDeleteFinalFields(out map[string]any) {
	n.emitAll(out, false)
	if n.present&negativeunlBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = n.PreviousTxnID
	}
	if n.present&negativeunlBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = n.PreviousTxnLgrSeq
	}
}

func (n *NegativeUNL) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	n.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (n *NegativeUNL) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if n.present&negativeunlBitPreviousTxnID != 0 {
		id = n.PreviousTxnID
	}
	if n.present&negativeunlBitPreviousTxnLgrSeq != 0 {
		seq = n.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (n *NegativeUNL) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "NegativeUNL",
	}
	if n.present&negativeunlBitFlags != 0 {
		out["Flags"] = n.Flags
	}
	if n.present&negativeunlBitDisabledValidators != 0 {
		out["DisabledValidators"] = n.DisabledValidators
	}
	if n.present&negativeunlBitValidatorToDisable != 0 {
		out["ValidatorToDisable"] = n.ValidatorToDisable
	}
	if n.present&negativeunlBitValidatorToReEnable != 0 {
		out["ValidatorToReEnable"] = n.ValidatorToReEnable
	}
	if n.present&negativeunlBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = n.PreviousTxnID
	}
	if n.present&negativeunlBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = n.PreviousTxnLgrSeq
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Round-trip
// invariant: Decode(data); Encode() == data for any byte sequence that
// Decode accepts.
func (n *NegativeUNL) Encode() ([]byte, error) {
	return binarycodec.EncodeBytes(n.ToMap())
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (n *NegativeUNL) Hash(index [32]byte) ([32]byte, error) {
	data, err := n.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode
	return common.Sha512Half(prefix[:], data, index[:]), nil
}
