// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

import (
	"github.com/LeJamon/go-xrpl/codec/binarycodec"
	"github.com/LeJamon/go-xrpl/crypto/common"
	"github.com/LeJamon/go-xrpl/protocol"
)

func init() {
	Register("NFTokenOffer", func() Entry { return new(NFTokenOffer) })
}

// NFTokenOffer is the typed representation of a NFTokenOffer ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every on-wire field — including those excluded from metadata
// (sMD_Never) — so Decode → Encode is byte-identical.
type NFTokenOffer struct {
	present           uint64
	Owner             string // AccountID (base58)
	NFTokenID         string // Hash256 (uppercase hex)
	Amount            any    // Amount (XRP string | IOU map)
	OwnerNode         string // UInt64 (lowercase hex, no leading zeros)
	NFTokenOfferNode  string // UInt64 (lowercase hex, no leading zeros)
	Destination       string // AccountID (base58)
	Expiration        uint32
	Flags             uint32
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
}

const (
	nftokenofferBitOwner uint64 = 1 << iota
	nftokenofferBitNFTokenID
	nftokenofferBitAmount
	nftokenofferBitOwnerNode
	nftokenofferBitNFTokenOfferNode
	nftokenofferBitDestination
	nftokenofferBitExpiration
	nftokenofferBitFlags
	nftokenofferBitPreviousTxnID
	nftokenofferBitPreviousTxnLgrSeq
)

// Decode populates the struct from binary ledger-entry data via a streaming
// reader. Unknown / sMD_Never fields are skipped without allocation.
func (n *NFTokenOffer) Decode(data []byte) error {
	*n = NFTokenOffer{}
	sr := newStreamReader(data)
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				_ = val // synthetic LedgerEntryType; discard
			default:
				return newErrUnknownField("NFTokenOffer", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				n.Flags = val
				n.present |= nftokenofferBitFlags
			case 5:
				n.PreviousTxnLgrSeq = val
				n.present |= nftokenofferBitPreviousTxnLgrSeq
			case 10:
				n.Expiration = val
				n.present |= nftokenofferBitExpiration
			default:
				return newErrUnknownField("NFTokenOffer", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 4:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				n.OwnerNode = val
				n.present |= nftokenofferBitOwnerNode
			case 12:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				n.NFTokenOfferNode = val
				n.present |= nftokenofferBitNFTokenOfferNode
			default:
				return newErrUnknownField("NFTokenOffer", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				n.PreviousTxnID = val
				n.present |= nftokenofferBitPreviousTxnID
			case 10:
				n.NFTokenID = val
				n.present |= nftokenofferBitNFTokenID
			default:
				return newErrUnknownField("NFTokenOffer", typeCode, fieldCode)
			}
		case 6: // Amount
			val, err := sr.readAmountAny()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				n.Amount = val
				n.present |= nftokenofferBitAmount
			default:
				return newErrUnknownField("NFTokenOffer", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				n.Owner = val
				n.present |= nftokenofferBitOwner
			case 3:
				n.Destination = val
				n.present |= nftokenofferBitDestination
			default:
				return newErrUnknownField("NFTokenOffer", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("NFTokenOffer", typeCode, fieldCode)
		}
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (n *NFTokenOffer) emitAll(out map[string]any, skipDefault bool) {
	if n.present&nftokenofferBitOwner != 0 && !(skipDefault && n.Owner == "") {
		out["Owner"] = n.Owner
	}
	if n.present&nftokenofferBitNFTokenID != 0 && !(skipDefault && isZeroHexString(n.NFTokenID)) {
		out["NFTokenID"] = n.NFTokenID
	}
	if n.present&nftokenofferBitAmount != 0 && !(skipDefault && amountIsDefault(n.Amount)) {
		out["Amount"] = n.Amount
	}
	if n.present&nftokenofferBitOwnerNode != 0 && !(skipDefault && isZeroHexString(n.OwnerNode)) {
		out["OwnerNode"] = n.OwnerNode
	}
	if n.present&nftokenofferBitNFTokenOfferNode != 0 && !(skipDefault && isZeroHexString(n.NFTokenOfferNode)) {
		out["NFTokenOfferNode"] = n.NFTokenOfferNode
	}
	if n.present&nftokenofferBitDestination != 0 && !(skipDefault && n.Destination == "") {
		out["Destination"] = n.Destination
	}
	if n.present&nftokenofferBitExpiration != 0 && !(skipDefault && n.Expiration == 0) {
		out["Expiration"] = n.Expiration
	}
	if n.present&nftokenofferBitFlags != 0 && !(skipDefault && n.Flags == 0) {
		out["Flags"] = n.Flags
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (n *NFTokenOffer) EmitNewFields(out map[string]any) {
	n.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (n *NFTokenOffer) EmitFinalFields(out map[string]any) {
	n.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (n *NFTokenOffer) EmitPreviousFields(prev Entry, out map[string]any) {
	prv, ok := prev.(*NFTokenOffer)
	if !ok || prv == nil {
		return
	}
	emitIfChangedString(out, "Owner", prv.Owner, n.Owner, prv.present&nftokenofferBitOwner, n.present&nftokenofferBitOwner)
	emitIfChangedString(out, "NFTokenID", prv.NFTokenID, n.NFTokenID, prv.present&nftokenofferBitNFTokenID, n.present&nftokenofferBitNFTokenID)
	emitIfChangedAmount(out, "Amount", prv.Amount, n.Amount, prv.present&nftokenofferBitAmount, n.present&nftokenofferBitAmount)
	emitIfChangedString(out, "OwnerNode", prv.OwnerNode, n.OwnerNode, prv.present&nftokenofferBitOwnerNode, n.present&nftokenofferBitOwnerNode)
	emitIfChangedString(out, "NFTokenOfferNode", prv.NFTokenOfferNode, n.NFTokenOfferNode, prv.present&nftokenofferBitNFTokenOfferNode, n.present&nftokenofferBitNFTokenOfferNode)
	emitIfChangedString(out, "Destination", prv.Destination, n.Destination, prv.present&nftokenofferBitDestination, n.present&nftokenofferBitDestination)
	emitIfChangedUint32(out, "Expiration", prv.Expiration, n.Expiration, prv.present&nftokenofferBitExpiration, n.present&nftokenofferBitExpiration)
	emitIfChangedUint32(out, "Flags", prv.Flags, n.Flags, prv.present&nftokenofferBitFlags, n.present&nftokenofferBitFlags)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (n *NFTokenOffer) EmitChangeOrigFields(out map[string]any) {
	if n.present&nftokenofferBitOwner != 0 {
		out["Owner"] = n.Owner
	}
	if n.present&nftokenofferBitNFTokenID != 0 {
		out["NFTokenID"] = n.NFTokenID
	}
	if n.present&nftokenofferBitAmount != 0 {
		out["Amount"] = n.Amount
	}
	if n.present&nftokenofferBitOwnerNode != 0 {
		out["OwnerNode"] = n.OwnerNode
	}
	if n.present&nftokenofferBitNFTokenOfferNode != 0 {
		out["NFTokenOfferNode"] = n.NFTokenOfferNode
	}
	if n.present&nftokenofferBitDestination != 0 {
		out["Destination"] = n.Destination
	}
	if n.present&nftokenofferBitExpiration != 0 {
		out["Expiration"] = n.Expiration
	}
	if n.present&nftokenofferBitFlags != 0 {
		out["Flags"] = n.Flags
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (n *NFTokenOffer) EmitDeleteFinalFields(out map[string]any) {
	n.emitAll(out, false)
	if n.present&nftokenofferBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = n.PreviousTxnID
	}
	if n.present&nftokenofferBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = n.PreviousTxnLgrSeq
	}
}

func (n *NFTokenOffer) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	n.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (n *NFTokenOffer) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if n.present&nftokenofferBitPreviousTxnID != 0 {
		id = n.PreviousTxnID
	}
	if n.present&nftokenofferBitPreviousTxnLgrSeq != 0 {
		seq = n.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (n *NFTokenOffer) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "NFTokenOffer",
	}
	if n.present&nftokenofferBitOwner != 0 {
		out["Owner"] = n.Owner
	}
	if n.present&nftokenofferBitNFTokenID != 0 {
		out["NFTokenID"] = n.NFTokenID
	}
	if n.present&nftokenofferBitAmount != 0 {
		out["Amount"] = n.Amount
	}
	if n.present&nftokenofferBitOwnerNode != 0 {
		out["OwnerNode"] = n.OwnerNode
	}
	if n.present&nftokenofferBitNFTokenOfferNode != 0 {
		out["NFTokenOfferNode"] = n.NFTokenOfferNode
	}
	if n.present&nftokenofferBitDestination != 0 {
		out["Destination"] = n.Destination
	}
	if n.present&nftokenofferBitExpiration != 0 {
		out["Expiration"] = n.Expiration
	}
	if n.present&nftokenofferBitFlags != 0 {
		out["Flags"] = n.Flags
	}
	if n.present&nftokenofferBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = n.PreviousTxnID
	}
	if n.present&nftokenofferBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = n.PreviousTxnLgrSeq
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Round-trip
// invariant: Decode(data); Encode() == data for any byte sequence that
// Decode accepts.
func (n *NFTokenOffer) Encode() ([]byte, error) {
	return binarycodec.EncodeBytes(n.ToMap())
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (n *NFTokenOffer) Hash(index [32]byte) ([32]byte, error) {
	data, err := n.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode
	return common.Sha512Half(prefix[:], data, index[:]), nil
}
