// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

import (
	"errors"
	"fmt"

	"github.com/LeJamon/go-xrpl/codec/binarycodec"
	"github.com/LeJamon/go-xrpl/crypto/sha512half"
	"github.com/LeJamon/go-xrpl/protocol"
)

func init() {
	Register("Offer", func() Entry { return new(Offer) })
}

// Offer is the typed representation of a Offer ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every canonical field declared in the spec — including those excluded from
// metadata (sMD_Never) — so decoding and re-encoding does not drop them.
type Offer struct {
	present           uint64
	decoded           bool
	dirty             bool
	Account           string // AccountID (base58)
	Sequence          uint32
	TakerPays         any    // Amount (XRP string | IOU map)
	TakerGets         any    // Amount (XRP string | IOU map)
	BookDirectory     string // Hash256 (uppercase hex)
	BookNode          string // UInt64 (lowercase hex, no leading zeros)
	OwnerNode         string // UInt64 (lowercase hex, no leading zeros)
	Expiration        uint32
	Flags             uint32
	DomainID          string // Hash256 (uppercase hex)
	AdditionalBooks   []any
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
	Sponsor           string // AccountID (base58)
}

const (
	offerBitAccount uint64 = 1 << iota
	offerBitSequence
	offerBitTakerPays
	offerBitTakerGets
	offerBitBookDirectory
	offerBitBookNode
	offerBitOwnerNode
	offerBitExpiration
	offerBitFlags
	offerBitDomainID
	offerBitAdditionalBooks
	offerBitPreviousTxnID
	offerBitPreviousTxnLgrSeq
	offerBitSponsor
)

// SetAccount assigns Account and updates its serialized presence.
func (o *Offer) SetAccount(value string) {
	o.Account = value
	o.dirty = true
	o.present |= offerBitAccount
}

// SetSequence assigns Sequence and updates its serialized presence.
func (o *Offer) SetSequence(value uint32) {
	o.Sequence = value
	o.dirty = true
	o.present |= offerBitSequence
}

// SetTakerPays assigns TakerPays and updates its serialized presence.
func (o *Offer) SetTakerPays(value any) {
	o.TakerPays = value
	o.dirty = true
	o.present |= offerBitTakerPays
}

// SetTakerGets assigns TakerGets and updates its serialized presence.
func (o *Offer) SetTakerGets(value any) {
	o.TakerGets = value
	o.dirty = true
	o.present |= offerBitTakerGets
}

// SetBookDirectory assigns BookDirectory and updates its serialized presence.
func (o *Offer) SetBookDirectory(value string) {
	o.BookDirectory = value
	o.dirty = true
	o.present |= offerBitBookDirectory
}

// SetBookNode assigns BookNode and updates its serialized presence.
func (o *Offer) SetBookNode(value string) {
	o.BookNode = value
	o.dirty = true
	o.present |= offerBitBookNode
}

// SetOwnerNode assigns OwnerNode and updates its serialized presence.
func (o *Offer) SetOwnerNode(value string) {
	o.OwnerNode = value
	o.dirty = true
	o.present |= offerBitOwnerNode
}

// SetExpiration assigns Expiration and updates its serialized presence.
func (o *Offer) SetExpiration(value uint32) {
	o.Expiration = value
	o.dirty = true
	o.present |= offerBitExpiration
}

// SetFlags assigns Flags and updates its serialized presence.
func (o *Offer) SetFlags(value uint32) {
	o.Flags = value
	o.dirty = true
	o.present |= offerBitFlags
}

// SetDomainID assigns DomainID and updates its serialized presence.
func (o *Offer) SetDomainID(value string) {
	o.DomainID = value
	o.dirty = true
	o.present |= offerBitDomainID
}

// SetAdditionalBooks assigns AdditionalBooks and updates its serialized presence.
func (o *Offer) SetAdditionalBooks(value []any) {
	o.AdditionalBooks = value
	o.dirty = true
	o.present |= offerBitAdditionalBooks
}

// SetPreviousTxnID assigns PreviousTxnID and updates its serialized presence.
func (o *Offer) SetPreviousTxnID(value string) {
	o.PreviousTxnID = value
	o.dirty = true
	o.present |= offerBitPreviousTxnID
}

// SetPreviousTxnLgrSeq assigns PreviousTxnLgrSeq and updates its serialized presence.
func (o *Offer) SetPreviousTxnLgrSeq(value uint32) {
	o.PreviousTxnLgrSeq = value
	o.dirty = true
	o.present |= offerBitPreviousTxnLgrSeq
}

// SetSponsor assigns Sponsor and updates its serialized presence.
func (o *Offer) SetSponsor(value string) {
	o.Sponsor = value
	o.dirty = true
	o.present |= offerBitSponsor
}

func (o *Offer) validateRequired() error {
	if o.decoded && !o.dirty {
		return nil
	}
	if o.present&offerBitAccount == 0 {
		return errors.New("ledgerfields: Offer: required field Account is not set")
	}
	if o.present&offerBitSequence == 0 {
		return errors.New("ledgerfields: Offer: required field Sequence is not set")
	}
	if o.present&offerBitTakerPays == 0 {
		return errors.New("ledgerfields: Offer: required field TakerPays is not set")
	}
	if o.present&offerBitTakerGets == 0 {
		return errors.New("ledgerfields: Offer: required field TakerGets is not set")
	}
	if o.present&offerBitBookDirectory == 0 {
		return errors.New("ledgerfields: Offer: required field BookDirectory is not set")
	}
	if o.present&offerBitBookNode == 0 {
		return errors.New("ledgerfields: Offer: required field BookNode is not set")
	}
	if o.present&offerBitOwnerNode == 0 {
		return errors.New("ledgerfields: Offer: required field OwnerNode is not set")
	}
	if o.present&offerBitFlags == 0 {
		return errors.New("ledgerfields: Offer: required field Flags is not set")
	}
	return nil
}

func (o *Offer) validateDecoded() error {
	if o.present&offerBitAccount == 0 {
		return errors.New("ledgerfields: Offer: required field Account is missing")
	}
	if o.present&offerBitSequence == 0 {
		return errors.New("ledgerfields: Offer: required field Sequence is missing")
	}
	if o.present&offerBitTakerPays == 0 {
		return errors.New("ledgerfields: Offer: required field TakerPays is missing")
	}
	if o.present&offerBitTakerGets == 0 {
		return errors.New("ledgerfields: Offer: required field TakerGets is missing")
	}
	if o.present&offerBitBookDirectory == 0 {
		return errors.New("ledgerfields: Offer: required field BookDirectory is missing")
	}
	if o.present&offerBitBookNode == 0 {
		return errors.New("ledgerfields: Offer: required field BookNode is missing")
	}
	if o.present&offerBitOwnerNode == 0 {
		return errors.New("ledgerfields: Offer: required field OwnerNode is missing")
	}
	if o.present&offerBitFlags == 0 {
		return errors.New("ledgerfields: Offer: required field Flags is missing")
	}
	if o.present&offerBitPreviousTxnID == 0 {
		return errors.New("ledgerfields: Offer: required field PreviousTxnID is missing")
	}
	if o.present&offerBitPreviousTxnLgrSeq == 0 {
		return errors.New("ledgerfields: Offer: required field PreviousTxnLgrSeq is missing")
	}
	return nil
}

// Decode populates the struct from binary ledger-entry data via a streaming
// reader and enforces the current rippled ledger template.
func (o *Offer) Decode(data []byte) error {
	return o.decode(data, false)
}

func (o *Offer) decodeLegacy(data []byte) error {
	return o.decode(data, true)
}

func (o *Offer) decode(data []byte, legacy bool) error {
	*o = Offer{}
	sr := newStreamReader(data)
	seenFields := make(map[[2]int]struct{})
	sawLedgerEntryType := false
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		fieldID := [2]int{typeCode, fieldCode}
		if _, exists := seenFields[fieldID]; exists {
			return fmt.Errorf("ledgerfields: Offer: duplicate field type=%d field=%d", typeCode, fieldCode)
		}
		seenFields[fieldID] = struct{}{}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				if val != 111 {
					return fmt.Errorf("ledgerfields: Offer: LedgerEntryType is %d, want 111", val)
				}
				sawLedgerEntryType = true
			default:
				return newErrUnknownField("Offer", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				o.Flags = val
				o.present |= offerBitFlags
			case 4:
				o.Sequence = val
				o.present |= offerBitSequence
			case 5:
				o.PreviousTxnLgrSeq = val
				o.present |= offerBitPreviousTxnLgrSeq
			case 10:
				o.Expiration = val
				o.present |= offerBitExpiration
			default:
				return newErrUnknownField("Offer", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 3:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				o.BookNode = val
				o.present |= offerBitBookNode
			case 4:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				o.OwnerNode = val
				o.present |= offerBitOwnerNode
			default:
				return newErrUnknownField("Offer", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				o.PreviousTxnID = val
				o.present |= offerBitPreviousTxnID
			case 16:
				o.BookDirectory = val
				o.present |= offerBitBookDirectory
			case 34:
				o.DomainID = val
				o.present |= offerBitDomainID
			default:
				return newErrUnknownField("Offer", typeCode, fieldCode)
			}
		case 6: // Amount
			val, err := sr.readAmountAny()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 4:
				o.TakerPays = val
				o.present |= offerBitTakerPays
			case 5:
				o.TakerGets = val
				o.present |= offerBitTakerGets
			default:
				return newErrUnknownField("Offer", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				o.Account = val
				o.present |= offerBitAccount
			case 27:
				o.Sponsor = val
				o.present |= offerBitSponsor
			default:
				return newErrUnknownField("Offer", typeCode, fieldCode)
			}
		case 15: // STArray
			val, err := sr.readSTArray()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 13:
				o.AdditionalBooks = val
				o.present |= offerBitAdditionalBooks
			default:
				return newErrUnknownField("Offer", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("Offer", typeCode, fieldCode)
		}
	}
	if !sawLedgerEntryType {
		return errors.New("ledgerfields: Offer: missing LedgerEntryType")
	}
	o.decoded = true
	if !legacy {
		return o.validateDecoded()
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (o *Offer) emitAll(out map[string]any, skipDefault bool) {
	if o.present&offerBitAccount != 0 && !(skipDefault && o.Account == "") {
		out["Account"] = o.Account
	}
	if o.present&offerBitSequence != 0 && !(skipDefault && o.Sequence == 0) {
		out["Sequence"] = o.Sequence
	}
	if o.present&offerBitTakerPays != 0 && !(skipDefault && amountIsDefault(o.TakerPays)) {
		out["TakerPays"] = o.TakerPays
	}
	if o.present&offerBitTakerGets != 0 && !(skipDefault && amountIsDefault(o.TakerGets)) {
		out["TakerGets"] = o.TakerGets
	}
	if o.present&offerBitBookDirectory != 0 && !(skipDefault && isZeroHexString(o.BookDirectory)) {
		out["BookDirectory"] = o.BookDirectory
	}
	if o.present&offerBitBookNode != 0 && !(skipDefault && isZeroHexString(o.BookNode)) {
		out["BookNode"] = o.BookNode
	}
	if o.present&offerBitOwnerNode != 0 && !(skipDefault && isZeroHexString(o.OwnerNode)) {
		out["OwnerNode"] = o.OwnerNode
	}
	if o.present&offerBitExpiration != 0 && !(skipDefault && o.Expiration == 0) {
		out["Expiration"] = o.Expiration
	}
	if o.present&offerBitFlags != 0 && !(skipDefault && o.Flags == 0) {
		out["Flags"] = o.Flags
	}
	if o.present&offerBitDomainID != 0 && !(skipDefault && isZeroHexString(o.DomainID)) {
		out["DomainID"] = o.DomainID
	}
	if o.present&offerBitAdditionalBooks != 0 && !(skipDefault && len(o.AdditionalBooks) == 0) {
		out["AdditionalBooks"] = o.AdditionalBooks
	}
	if o.present&offerBitSponsor != 0 && !(skipDefault && o.Sponsor == "") {
		out["Sponsor"] = o.Sponsor
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (o *Offer) EmitNewFields(out map[string]any) {
	o.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (o *Offer) EmitFinalFields(out map[string]any) {
	o.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (o *Offer) EmitPreviousFields(prev Entry, out map[string]any) {
	prv, ok := prev.(*Offer)
	if !ok || prv == nil {
		return
	}
	emitIfChangedString(out, "Account", prv.Account, o.Account, prv.present&offerBitAccount, o.present&offerBitAccount)
	emitIfChangedUint32(out, "Sequence", prv.Sequence, o.Sequence, prv.present&offerBitSequence, o.present&offerBitSequence)
	emitIfChangedAmount(out, "TakerPays", prv.TakerPays, o.TakerPays, prv.present&offerBitTakerPays, o.present&offerBitTakerPays)
	emitIfChangedAmount(out, "TakerGets", prv.TakerGets, o.TakerGets, prv.present&offerBitTakerGets, o.present&offerBitTakerGets)
	emitIfChangedString(out, "BookDirectory", prv.BookDirectory, o.BookDirectory, prv.present&offerBitBookDirectory, o.present&offerBitBookDirectory)
	emitIfChangedString(out, "BookNode", prv.BookNode, o.BookNode, prv.present&offerBitBookNode, o.present&offerBitBookNode)
	emitIfChangedString(out, "OwnerNode", prv.OwnerNode, o.OwnerNode, prv.present&offerBitOwnerNode, o.present&offerBitOwnerNode)
	emitIfChangedUint32(out, "Expiration", prv.Expiration, o.Expiration, prv.present&offerBitExpiration, o.present&offerBitExpiration)
	emitIfChangedUint32(out, "Flags", prv.Flags, o.Flags, prv.present&offerBitFlags, o.present&offerBitFlags)
	emitIfChangedString(out, "DomainID", prv.DomainID, o.DomainID, prv.present&offerBitDomainID, o.present&offerBitDomainID)
	emitIfChangedDeep(out, "AdditionalBooks", prv.AdditionalBooks, o.AdditionalBooks, prv.present&offerBitAdditionalBooks, o.present&offerBitAdditionalBooks)
	emitIfChangedString(out, "Sponsor", prv.Sponsor, o.Sponsor, prv.present&offerBitSponsor, o.present&offerBitSponsor)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (o *Offer) EmitChangeOrigFields(out map[string]any) {
	if o.present&offerBitAccount != 0 {
		out["Account"] = o.Account
	}
	if o.present&offerBitSequence != 0 {
		out["Sequence"] = o.Sequence
	}
	if o.present&offerBitTakerPays != 0 {
		out["TakerPays"] = o.TakerPays
	}
	if o.present&offerBitTakerGets != 0 {
		out["TakerGets"] = o.TakerGets
	}
	if o.present&offerBitBookDirectory != 0 {
		out["BookDirectory"] = o.BookDirectory
	}
	if o.present&offerBitBookNode != 0 {
		out["BookNode"] = o.BookNode
	}
	if o.present&offerBitOwnerNode != 0 {
		out["OwnerNode"] = o.OwnerNode
	}
	if o.present&offerBitExpiration != 0 {
		out["Expiration"] = o.Expiration
	}
	if o.present&offerBitFlags != 0 {
		out["Flags"] = o.Flags
	}
	if o.present&offerBitDomainID != 0 {
		out["DomainID"] = o.DomainID
	}
	if o.present&offerBitAdditionalBooks != 0 {
		out["AdditionalBooks"] = o.AdditionalBooks
	}
	if o.present&offerBitSponsor != 0 {
		out["Sponsor"] = o.Sponsor
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (o *Offer) EmitDeleteFinalFields(out map[string]any) {
	o.emitAll(out, false)
	if o.present&offerBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = o.PreviousTxnID
	}
	if o.present&offerBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = o.PreviousTxnLgrSeq
	}
}

func (o *Offer) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	o.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (o *Offer) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if o.present&offerBitPreviousTxnID != 0 {
		id = o.PreviousTxnID
	}
	if o.present&offerBitPreviousTxnLgrSeq != 0 {
		seq = o.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (o *Offer) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "Offer",
	}
	if o.present&offerBitAccount != 0 {
		out["Account"] = o.Account
	}
	if o.present&offerBitSequence != 0 {
		out["Sequence"] = o.Sequence
	}
	if o.present&offerBitTakerPays != 0 {
		out["TakerPays"] = o.TakerPays
	}
	if o.present&offerBitTakerGets != 0 {
		out["TakerGets"] = o.TakerGets
	}
	if o.present&offerBitBookDirectory != 0 {
		out["BookDirectory"] = o.BookDirectory
	}
	if o.present&offerBitBookNode != 0 {
		out["BookNode"] = o.BookNode
	}
	if o.present&offerBitOwnerNode != 0 {
		out["OwnerNode"] = o.OwnerNode
	}
	if o.present&offerBitExpiration != 0 {
		out["Expiration"] = o.Expiration
	}
	if o.present&offerBitFlags != 0 {
		out["Flags"] = o.Flags
	}
	if o.present&offerBitDomainID != 0 {
		out["DomainID"] = o.DomainID
	}
	if o.present&offerBitAdditionalBooks != 0 {
		out["AdditionalBooks"] = o.AdditionalBooks
	}
	if o.present&offerBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = o.PreviousTxnID
	}
	if o.present&offerBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = o.PreviousTxnLgrSeq
	}
	if o.present&offerBitSponsor != 0 {
		out["Sponsor"] = o.Sponsor
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Legacy decode
// aliases and non-canonical input ordering are emitted in canonical form.
func (o *Offer) Encode() ([]byte, error) {
	if err := o.validateRequired(); err != nil {
		return nil, err
	}
	out := o.ToMap()
	if o.present&offerBitPreviousTxnID == 0 {
		out["PreviousTxnID"] = "0000000000000000000000000000000000000000000000000000000000000000"
	}
	if o.present&offerBitPreviousTxnLgrSeq == 0 {
		out["PreviousTxnLgrSeq"] = uint32(0)
	}
	return binarycodec.EncodeBytes(out)
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (o *Offer) Hash(index [32]byte) ([32]byte, error) {
	data, err := o.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode()
	return sha512half.Sum(prefix[:], data, index[:]), nil
}
