// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

import (
	"github.com/LeJamon/goXRPLd/codec/binarycodec"
	"github.com/LeJamon/goXRPLd/crypto/common"
	"github.com/LeJamon/goXRPLd/protocol"
)

func init() {
	Register("Offer", func() Entry { return new(Offer) })
}

// Offer is the typed representation of a Offer ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every on-wire field — including those excluded from metadata
// (sMD_Never) — so Decode → Encode is byte-identical.
type Offer struct {
	present           uint64
	Account           string // AccountID (base58)
	Sequence          uint32
	TakerPays         any    // Amount (XRP string | IOU map)
	TakerGets         any    // Amount (XRP string | IOU map)
	BookDirectory     string // Hash256 (uppercase hex)
	BookNode          string // UInt64 (lowercase hex, no leading zeros)
	OwnerNode         string // UInt64 (lowercase hex, no leading zeros)
	Expiration        uint32
	Flags             uint32
	DomainID          string // Hash256 (uppercase hex)
	AdditionalBooks   []any
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
}

const (
	offerBitAccount uint64 = 1 << iota
	offerBitSequence
	offerBitTakerPays
	offerBitTakerGets
	offerBitBookDirectory
	offerBitBookNode
	offerBitOwnerNode
	offerBitExpiration
	offerBitFlags
	offerBitDomainID
	offerBitAdditionalBooks
	offerBitPreviousTxnID
	offerBitPreviousTxnLgrSeq
)

// Decode populates the struct from binary ledger-entry data via a streaming
// reader. Unknown / sMD_Never fields are skipped without allocation.
func (o *Offer) Decode(data []byte) error {
	*o = Offer{}
	sr := newStreamReader(data)
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				_ = val // synthetic LedgerEntryType; discard
			default:
				return newErrUnknownField("Offer", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				o.Flags = val
				o.present |= offerBitFlags
			case 4:
				o.Sequence = val
				o.present |= offerBitSequence
			case 5:
				o.PreviousTxnLgrSeq = val
				o.present |= offerBitPreviousTxnLgrSeq
			case 10:
				o.Expiration = val
				o.present |= offerBitExpiration
			default:
				return newErrUnknownField("Offer", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 3:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				o.BookNode = val
				o.present |= offerBitBookNode
			case 4:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				o.OwnerNode = val
				o.present |= offerBitOwnerNode
			default:
				return newErrUnknownField("Offer", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				o.PreviousTxnID = val
				o.present |= offerBitPreviousTxnID
			case 16:
				o.BookDirectory = val
				o.present |= offerBitBookDirectory
			case 34:
				o.DomainID = val
				o.present |= offerBitDomainID
			default:
				return newErrUnknownField("Offer", typeCode, fieldCode)
			}
		case 6: // Amount
			val, err := sr.readAmountAny()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 4:
				o.TakerPays = val
				o.present |= offerBitTakerPays
			case 5:
				o.TakerGets = val
				o.present |= offerBitTakerGets
			default:
				return newErrUnknownField("Offer", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				o.Account = val
				o.present |= offerBitAccount
			default:
				return newErrUnknownField("Offer", typeCode, fieldCode)
			}
		case 15: // STArray
			val, err := sr.readSTArray()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 13:
				o.AdditionalBooks = val
				o.present |= offerBitAdditionalBooks
			default:
				return newErrUnknownField("Offer", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("Offer", typeCode, fieldCode)
		}
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (o *Offer) emitAll(out map[string]any, skipDefault bool) {
	if o.present&offerBitAccount != 0 && !(skipDefault && o.Account == "") {
		out["Account"] = o.Account
	}
	if o.present&offerBitSequence != 0 && !(skipDefault && o.Sequence == 0) {
		out["Sequence"] = o.Sequence
	}
	if o.present&offerBitTakerPays != 0 {
		out["TakerPays"] = o.TakerPays
	}
	if o.present&offerBitTakerGets != 0 {
		out["TakerGets"] = o.TakerGets
	}
	if o.present&offerBitBookDirectory != 0 && !(skipDefault && isZeroHexString(o.BookDirectory)) {
		out["BookDirectory"] = o.BookDirectory
	}
	if o.present&offerBitBookNode != 0 && !(skipDefault && isZeroHexString(o.BookNode)) {
		out["BookNode"] = o.BookNode
	}
	if o.present&offerBitOwnerNode != 0 && !(skipDefault && isZeroHexString(o.OwnerNode)) {
		out["OwnerNode"] = o.OwnerNode
	}
	if o.present&offerBitExpiration != 0 && !(skipDefault && o.Expiration == 0) {
		out["Expiration"] = o.Expiration
	}
	if o.present&offerBitFlags != 0 && !(skipDefault && o.Flags == 0) {
		out["Flags"] = o.Flags
	}
	if o.present&offerBitDomainID != 0 && !(skipDefault && isZeroHexString(o.DomainID)) {
		out["DomainID"] = o.DomainID
	}
	if o.present&offerBitAdditionalBooks != 0 {
		out["AdditionalBooks"] = o.AdditionalBooks
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (o *Offer) EmitNewFields(out map[string]any) {
	o.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (o *Offer) EmitFinalFields(out map[string]any) {
	o.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (o *Offer) EmitPreviousFields(prev Entry, out map[string]any) {
	p, ok := prev.(*Offer)
	if !ok || p == nil {
		return
	}
	emitIfChangedString(out, "Account", p.Account, o.Account, p.present&offerBitAccount, o.present&offerBitAccount)
	emitIfChangedUint32(out, "Sequence", p.Sequence, o.Sequence, p.present&offerBitSequence, o.present&offerBitSequence)
	emitIfChangedAmount(out, "TakerPays", p.TakerPays, o.TakerPays, p.present&offerBitTakerPays, o.present&offerBitTakerPays)
	emitIfChangedAmount(out, "TakerGets", p.TakerGets, o.TakerGets, p.present&offerBitTakerGets, o.present&offerBitTakerGets)
	emitIfChangedString(out, "BookDirectory", p.BookDirectory, o.BookDirectory, p.present&offerBitBookDirectory, o.present&offerBitBookDirectory)
	emitIfChangedString(out, "BookNode", p.BookNode, o.BookNode, p.present&offerBitBookNode, o.present&offerBitBookNode)
	emitIfChangedString(out, "OwnerNode", p.OwnerNode, o.OwnerNode, p.present&offerBitOwnerNode, o.present&offerBitOwnerNode)
	emitIfChangedUint32(out, "Expiration", p.Expiration, o.Expiration, p.present&offerBitExpiration, o.present&offerBitExpiration)
	emitIfChangedUint32(out, "Flags", p.Flags, o.Flags, p.present&offerBitFlags, o.present&offerBitFlags)
	emitIfChangedString(out, "DomainID", p.DomainID, o.DomainID, p.present&offerBitDomainID, o.present&offerBitDomainID)
	emitIfChangedDeep(out, "AdditionalBooks", p.AdditionalBooks, o.AdditionalBooks, p.present&offerBitAdditionalBooks, o.present&offerBitAdditionalBooks)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (o *Offer) EmitChangeOrigFields(out map[string]any) {
	if o.present&offerBitAccount != 0 {
		out["Account"] = o.Account
	}
	if o.present&offerBitSequence != 0 {
		out["Sequence"] = o.Sequence
	}
	if o.present&offerBitTakerPays != 0 {
		out["TakerPays"] = o.TakerPays
	}
	if o.present&offerBitTakerGets != 0 {
		out["TakerGets"] = o.TakerGets
	}
	if o.present&offerBitBookDirectory != 0 {
		out["BookDirectory"] = o.BookDirectory
	}
	if o.present&offerBitBookNode != 0 {
		out["BookNode"] = o.BookNode
	}
	if o.present&offerBitOwnerNode != 0 {
		out["OwnerNode"] = o.OwnerNode
	}
	if o.present&offerBitExpiration != 0 {
		out["Expiration"] = o.Expiration
	}
	if o.present&offerBitFlags != 0 {
		out["Flags"] = o.Flags
	}
	if o.present&offerBitDomainID != 0 {
		out["DomainID"] = o.DomainID
	}
	if o.present&offerBitAdditionalBooks != 0 {
		out["AdditionalBooks"] = o.AdditionalBooks
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (o *Offer) EmitDeleteFinalFields(out map[string]any) {
	o.emitAll(out, false)
	if o.present&offerBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = o.PreviousTxnID
	}
	if o.present&offerBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = o.PreviousTxnLgrSeq
	}
}

func (o *Offer) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	o.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (o *Offer) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if o.present&offerBitPreviousTxnID != 0 {
		id = o.PreviousTxnID
	}
	if o.present&offerBitPreviousTxnLgrSeq != 0 {
		seq = o.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (o *Offer) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "Offer",
	}
	if o.present&offerBitAccount != 0 {
		out["Account"] = o.Account
	}
	if o.present&offerBitSequence != 0 {
		out["Sequence"] = o.Sequence
	}
	if o.present&offerBitTakerPays != 0 {
		out["TakerPays"] = o.TakerPays
	}
	if o.present&offerBitTakerGets != 0 {
		out["TakerGets"] = o.TakerGets
	}
	if o.present&offerBitBookDirectory != 0 {
		out["BookDirectory"] = o.BookDirectory
	}
	if o.present&offerBitBookNode != 0 {
		out["BookNode"] = o.BookNode
	}
	if o.present&offerBitOwnerNode != 0 {
		out["OwnerNode"] = o.OwnerNode
	}
	if o.present&offerBitExpiration != 0 {
		out["Expiration"] = o.Expiration
	}
	if o.present&offerBitFlags != 0 {
		out["Flags"] = o.Flags
	}
	if o.present&offerBitDomainID != 0 {
		out["DomainID"] = o.DomainID
	}
	if o.present&offerBitAdditionalBooks != 0 {
		out["AdditionalBooks"] = o.AdditionalBooks
	}
	if o.present&offerBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = o.PreviousTxnID
	}
	if o.present&offerBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = o.PreviousTxnLgrSeq
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Round-trip
// invariant: Decode(data); Encode() == data for any byte sequence that
// Decode accepts.
func (o *Offer) Encode() ([]byte, error) {
	return binarycodec.EncodeBytes(o.ToMap())
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (o *Offer) Hash(index [32]byte) ([32]byte, error) {
	data, err := o.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode
	return common.Sha512Half(prefix[:], data, index[:]), nil
}
