// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

import (
	"errors"
	"fmt"

	"github.com/LeJamon/go-xrpl/codec/binarycodec"
	"github.com/LeJamon/go-xrpl/crypto/sha512half"
	"github.com/LeJamon/go-xrpl/protocol"
)

func init() {
	Register("Oracle", func() Entry { return new(Oracle) })
}

// Oracle is the typed representation of a Oracle ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every canonical field declared in the spec — including those excluded from
// metadata (sMD_Never) — so decoding and re-encoding does not drop them.
type Oracle struct {
	present           uint64
	decoded           bool
	dirty             bool
	Owner             string // AccountID (base58)
	OracleDocumentID  uint32
	Provider          string // Blob (uppercase hex)
	PriceDataSeries   []any
	AssetClass        string // Blob (uppercase hex)
	LastUpdateTime    uint32
	URI               string // Blob (uppercase hex)
	OwnerNode         string // UInt64 (lowercase hex, no leading zeros)
	Flags             uint32
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
	Sponsor           string // AccountID (base58)
}

const (
	oracleBitOwner uint64 = 1 << iota
	oracleBitOracleDocumentID
	oracleBitProvider
	oracleBitPriceDataSeries
	oracleBitAssetClass
	oracleBitLastUpdateTime
	oracleBitURI
	oracleBitOwnerNode
	oracleBitFlags
	oracleBitPreviousTxnID
	oracleBitPreviousTxnLgrSeq
	oracleBitSponsor
)

// SetOwner assigns Owner and updates its serialized presence.
func (o *Oracle) SetOwner(value string) {
	o.Owner = value
	o.dirty = true
	o.present |= oracleBitOwner
}

// SetOracleDocumentID assigns OracleDocumentID and updates its serialized presence.
func (o *Oracle) SetOracleDocumentID(value uint32) {
	o.OracleDocumentID = value
	o.dirty = true
	o.present |= oracleBitOracleDocumentID
}

// SetProvider assigns Provider and updates its serialized presence.
func (o *Oracle) SetProvider(value string) {
	o.Provider = value
	o.dirty = true
	o.present |= oracleBitProvider
}

// SetPriceDataSeries assigns PriceDataSeries and updates its serialized presence.
func (o *Oracle) SetPriceDataSeries(value []any) {
	o.PriceDataSeries = value
	o.dirty = true
	o.present |= oracleBitPriceDataSeries
}

// SetAssetClass assigns AssetClass and updates its serialized presence.
func (o *Oracle) SetAssetClass(value string) {
	o.AssetClass = value
	o.dirty = true
	o.present |= oracleBitAssetClass
}

// SetLastUpdateTime assigns LastUpdateTime and updates its serialized presence.
func (o *Oracle) SetLastUpdateTime(value uint32) {
	o.LastUpdateTime = value
	o.dirty = true
	o.present |= oracleBitLastUpdateTime
}

// SetURI assigns URI and updates its serialized presence.
func (o *Oracle) SetURI(value string) {
	o.URI = value
	o.dirty = true
	o.present |= oracleBitURI
}

// SetOwnerNode assigns OwnerNode and updates its serialized presence.
func (o *Oracle) SetOwnerNode(value string) {
	o.OwnerNode = value
	o.dirty = true
	o.present |= oracleBitOwnerNode
}

// SetFlags assigns Flags and updates its serialized presence.
func (o *Oracle) SetFlags(value uint32) {
	o.Flags = value
	o.dirty = true
	o.present |= oracleBitFlags
}

// SetPreviousTxnID assigns PreviousTxnID and updates its serialized presence.
func (o *Oracle) SetPreviousTxnID(value string) {
	o.PreviousTxnID = value
	o.dirty = true
	o.present |= oracleBitPreviousTxnID
}

// SetPreviousTxnLgrSeq assigns PreviousTxnLgrSeq and updates its serialized presence.
func (o *Oracle) SetPreviousTxnLgrSeq(value uint32) {
	o.PreviousTxnLgrSeq = value
	o.dirty = true
	o.present |= oracleBitPreviousTxnLgrSeq
}

// SetSponsor assigns Sponsor and updates its serialized presence.
func (o *Oracle) SetSponsor(value string) {
	o.Sponsor = value
	o.dirty = true
	o.present |= oracleBitSponsor
}

func (o *Oracle) validateRequired() error {
	if o.decoded && !o.dirty {
		return nil
	}
	if o.present&oracleBitOwner == 0 {
		return errors.New("ledgerfields: Oracle: required field Owner is not set")
	}
	if o.present&oracleBitProvider == 0 {
		return errors.New("ledgerfields: Oracle: required field Provider is not set")
	}
	if o.present&oracleBitPriceDataSeries == 0 {
		return errors.New("ledgerfields: Oracle: required field PriceDataSeries is not set")
	}
	if o.present&oracleBitAssetClass == 0 {
		return errors.New("ledgerfields: Oracle: required field AssetClass is not set")
	}
	if o.present&oracleBitLastUpdateTime == 0 {
		return errors.New("ledgerfields: Oracle: required field LastUpdateTime is not set")
	}
	if o.present&oracleBitOwnerNode == 0 {
		return errors.New("ledgerfields: Oracle: required field OwnerNode is not set")
	}
	if o.present&oracleBitFlags == 0 {
		return errors.New("ledgerfields: Oracle: required field Flags is not set")
	}
	return nil
}

func (o *Oracle) validateDecoded() error {
	if o.present&oracleBitOwner == 0 {
		return errors.New("ledgerfields: Oracle: required field Owner is missing")
	}
	if o.present&oracleBitProvider == 0 {
		return errors.New("ledgerfields: Oracle: required field Provider is missing")
	}
	if o.present&oracleBitPriceDataSeries == 0 {
		return errors.New("ledgerfields: Oracle: required field PriceDataSeries is missing")
	}
	if o.present&oracleBitAssetClass == 0 {
		return errors.New("ledgerfields: Oracle: required field AssetClass is missing")
	}
	if o.present&oracleBitLastUpdateTime == 0 {
		return errors.New("ledgerfields: Oracle: required field LastUpdateTime is missing")
	}
	if o.present&oracleBitOwnerNode == 0 {
		return errors.New("ledgerfields: Oracle: required field OwnerNode is missing")
	}
	if o.present&oracleBitFlags == 0 {
		return errors.New("ledgerfields: Oracle: required field Flags is missing")
	}
	if o.present&oracleBitPreviousTxnID == 0 {
		return errors.New("ledgerfields: Oracle: required field PreviousTxnID is missing")
	}
	if o.present&oracleBitPreviousTxnLgrSeq == 0 {
		return errors.New("ledgerfields: Oracle: required field PreviousTxnLgrSeq is missing")
	}
	return nil
}

// Decode populates the struct from binary ledger-entry data via a streaming
// reader and enforces the current rippled ledger template.
func (o *Oracle) Decode(data []byte) error {
	return o.decode(data, false)
}

func (o *Oracle) decodeLegacy(data []byte) error {
	return o.decode(data, true)
}

func (o *Oracle) decode(data []byte, legacy bool) error {
	*o = Oracle{}
	sr := newStreamReader(data)
	seenFields := make(map[[2]int]struct{})
	sawLedgerEntryType := false
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		fieldID := [2]int{typeCode, fieldCode}
		if _, exists := seenFields[fieldID]; exists {
			return fmt.Errorf("ledgerfields: Oracle: duplicate field type=%d field=%d", typeCode, fieldCode)
		}
		seenFields[fieldID] = struct{}{}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				if val != 128 {
					return fmt.Errorf("ledgerfields: Oracle: LedgerEntryType is %d, want 128", val)
				}
				sawLedgerEntryType = true
			default:
				return newErrUnknownField("Oracle", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				o.Flags = val
				o.present |= oracleBitFlags
			case 5:
				o.PreviousTxnLgrSeq = val
				o.present |= oracleBitPreviousTxnLgrSeq
			case 15:
				o.LastUpdateTime = val
				o.present |= oracleBitLastUpdateTime
			case 51:
				o.OracleDocumentID = val
				o.present |= oracleBitOracleDocumentID
			default:
				return newErrUnknownField("Oracle", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 4:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				o.OwnerNode = val
				o.present |= oracleBitOwnerNode
			default:
				return newErrUnknownField("Oracle", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				o.PreviousTxnID = val
				o.present |= oracleBitPreviousTxnID
			default:
				return newErrUnknownField("Oracle", typeCode, fieldCode)
			}
		case 7: // Blob
			val, err := sr.readBlobHex()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				o.URI = val
				o.present |= oracleBitURI
			case 28:
				o.AssetClass = val
				o.present |= oracleBitAssetClass
			case 29:
				o.Provider = val
				o.present |= oracleBitProvider
			default:
				return newErrUnknownField("Oracle", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				o.Owner = val
				o.present |= oracleBitOwner
			case 27:
				o.Sponsor = val
				o.present |= oracleBitSponsor
			default:
				return newErrUnknownField("Oracle", typeCode, fieldCode)
			}
		case 15: // STArray
			val, err := sr.readSTArray()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 24:
				o.PriceDataSeries = val
				o.present |= oracleBitPriceDataSeries
			default:
				return newErrUnknownField("Oracle", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("Oracle", typeCode, fieldCode)
		}
	}
	if !sawLedgerEntryType {
		return errors.New("ledgerfields: Oracle: missing LedgerEntryType")
	}
	o.decoded = true
	if !legacy {
		return o.validateDecoded()
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (o *Oracle) emitAll(out map[string]any, skipDefault bool) {
	if o.present&oracleBitOwner != 0 && !(skipDefault && o.Owner == "") {
		out["Owner"] = o.Owner
	}
	if o.present&oracleBitOracleDocumentID != 0 && !(skipDefault && o.OracleDocumentID == 0) {
		out["OracleDocumentID"] = o.OracleDocumentID
	}
	if o.present&oracleBitProvider != 0 && !(skipDefault && o.Provider == "") {
		out["Provider"] = o.Provider
	}
	if o.present&oracleBitPriceDataSeries != 0 && !(skipDefault && len(o.PriceDataSeries) == 0) {
		out["PriceDataSeries"] = o.PriceDataSeries
	}
	if o.present&oracleBitAssetClass != 0 && !(skipDefault && o.AssetClass == "") {
		out["AssetClass"] = o.AssetClass
	}
	if o.present&oracleBitLastUpdateTime != 0 && !(skipDefault && o.LastUpdateTime == 0) {
		out["LastUpdateTime"] = o.LastUpdateTime
	}
	if o.present&oracleBitURI != 0 && !(skipDefault && o.URI == "") {
		out["URI"] = o.URI
	}
	if o.present&oracleBitOwnerNode != 0 && !(skipDefault && isZeroHexString(o.OwnerNode)) {
		out["OwnerNode"] = o.OwnerNode
	}
	if o.present&oracleBitFlags != 0 && !(skipDefault && o.Flags == 0) {
		out["Flags"] = o.Flags
	}
	if o.present&oracleBitSponsor != 0 && !(skipDefault && o.Sponsor == "") {
		out["Sponsor"] = o.Sponsor
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (o *Oracle) EmitNewFields(out map[string]any) {
	o.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (o *Oracle) EmitFinalFields(out map[string]any) {
	o.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (o *Oracle) EmitPreviousFields(prev Entry, out map[string]any) {
	prv, ok := prev.(*Oracle)
	if !ok || prv == nil {
		return
	}
	emitIfChangedString(out, "Owner", prv.Owner, o.Owner, prv.present&oracleBitOwner, o.present&oracleBitOwner)
	emitIfChangedUint32(out, "OracleDocumentID", prv.OracleDocumentID, o.OracleDocumentID, prv.present&oracleBitOracleDocumentID, o.present&oracleBitOracleDocumentID)
	emitIfChangedString(out, "Provider", prv.Provider, o.Provider, prv.present&oracleBitProvider, o.present&oracleBitProvider)
	emitIfChangedDeep(out, "PriceDataSeries", prv.PriceDataSeries, o.PriceDataSeries, prv.present&oracleBitPriceDataSeries, o.present&oracleBitPriceDataSeries)
	emitIfChangedString(out, "AssetClass", prv.AssetClass, o.AssetClass, prv.present&oracleBitAssetClass, o.present&oracleBitAssetClass)
	emitIfChangedUint32(out, "LastUpdateTime", prv.LastUpdateTime, o.LastUpdateTime, prv.present&oracleBitLastUpdateTime, o.present&oracleBitLastUpdateTime)
	emitIfChangedString(out, "URI", prv.URI, o.URI, prv.present&oracleBitURI, o.present&oracleBitURI)
	emitIfChangedString(out, "OwnerNode", prv.OwnerNode, o.OwnerNode, prv.present&oracleBitOwnerNode, o.present&oracleBitOwnerNode)
	emitIfChangedUint32(out, "Flags", prv.Flags, o.Flags, prv.present&oracleBitFlags, o.present&oracleBitFlags)
	emitIfChangedString(out, "Sponsor", prv.Sponsor, o.Sponsor, prv.present&oracleBitSponsor, o.present&oracleBitSponsor)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (o *Oracle) EmitChangeOrigFields(out map[string]any) {
	if o.present&oracleBitOwner != 0 {
		out["Owner"] = o.Owner
	}
	if o.present&oracleBitOracleDocumentID != 0 {
		out["OracleDocumentID"] = o.OracleDocumentID
	}
	if o.present&oracleBitProvider != 0 {
		out["Provider"] = o.Provider
	}
	if o.present&oracleBitPriceDataSeries != 0 {
		out["PriceDataSeries"] = o.PriceDataSeries
	}
	if o.present&oracleBitAssetClass != 0 {
		out["AssetClass"] = o.AssetClass
	}
	if o.present&oracleBitLastUpdateTime != 0 {
		out["LastUpdateTime"] = o.LastUpdateTime
	}
	if o.present&oracleBitURI != 0 {
		out["URI"] = o.URI
	}
	if o.present&oracleBitOwnerNode != 0 {
		out["OwnerNode"] = o.OwnerNode
	}
	if o.present&oracleBitFlags != 0 {
		out["Flags"] = o.Flags
	}
	if o.present&oracleBitSponsor != 0 {
		out["Sponsor"] = o.Sponsor
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (o *Oracle) EmitDeleteFinalFields(out map[string]any) {
	o.emitAll(out, false)
	if o.present&oracleBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = o.PreviousTxnID
	}
	if o.present&oracleBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = o.PreviousTxnLgrSeq
	}
}

func (o *Oracle) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	o.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (o *Oracle) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if o.present&oracleBitPreviousTxnID != 0 {
		id = o.PreviousTxnID
	}
	if o.present&oracleBitPreviousTxnLgrSeq != 0 {
		seq = o.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (o *Oracle) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "Oracle",
	}
	if o.present&oracleBitOwner != 0 {
		out["Owner"] = o.Owner
	}
	if o.present&oracleBitOracleDocumentID != 0 {
		out["OracleDocumentID"] = o.OracleDocumentID
	}
	if o.present&oracleBitProvider != 0 {
		out["Provider"] = o.Provider
	}
	if o.present&oracleBitPriceDataSeries != 0 {
		out["PriceDataSeries"] = o.PriceDataSeries
	}
	if o.present&oracleBitAssetClass != 0 {
		out["AssetClass"] = o.AssetClass
	}
	if o.present&oracleBitLastUpdateTime != 0 {
		out["LastUpdateTime"] = o.LastUpdateTime
	}
	if o.present&oracleBitURI != 0 {
		out["URI"] = o.URI
	}
	if o.present&oracleBitOwnerNode != 0 {
		out["OwnerNode"] = o.OwnerNode
	}
	if o.present&oracleBitFlags != 0 {
		out["Flags"] = o.Flags
	}
	if o.present&oracleBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = o.PreviousTxnID
	}
	if o.present&oracleBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = o.PreviousTxnLgrSeq
	}
	if o.present&oracleBitSponsor != 0 {
		out["Sponsor"] = o.Sponsor
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Legacy decode
// aliases and non-canonical input ordering are emitted in canonical form.
func (o *Oracle) Encode() ([]byte, error) {
	if err := o.validateRequired(); err != nil {
		return nil, err
	}
	out := o.ToMap()
	if o.present&oracleBitPreviousTxnID == 0 {
		out["PreviousTxnID"] = "0000000000000000000000000000000000000000000000000000000000000000"
	}
	if o.present&oracleBitPreviousTxnLgrSeq == 0 {
		out["PreviousTxnLgrSeq"] = uint32(0)
	}
	return binarycodec.EncodeBytes(out)
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (o *Oracle) Hash(index [32]byte) ([32]byte, error) {
	data, err := o.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode()
	return sha512half.Sum(prefix[:], data, index[:]), nil
}
