// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

import (
	"github.com/LeJamon/go-xrpl/codec/binarycodec"
	"github.com/LeJamon/go-xrpl/crypto/common"
	"github.com/LeJamon/go-xrpl/protocol"
)

func init() {
	Register("PayChannel", func() Entry { return new(PayChannel) })
}

// PayChannel is the typed representation of a PayChannel ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every on-wire field — including those excluded from metadata
// (sMD_Never) — so Decode → Encode is byte-identical.
type PayChannel struct {
	present           uint64
	Account           string // AccountID (base58)
	Destination       string // AccountID (base58)
	Amount            any    // Amount (XRP string | IOU map)
	Balance           any    // Amount (XRP string | IOU map)
	PublicKey         string // Blob (uppercase hex)
	SettleDelay       uint32
	Expiration        uint32
	CancelAfter       uint32
	SourceTag         uint32
	DestinationTag    uint32
	OwnerNode         string // UInt64 (lowercase hex, no leading zeros)
	DestinationNode   string // UInt64 (lowercase hex, no leading zeros)
	Flags             uint32
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
}

const (
	paychannelBitAccount uint64 = 1 << iota
	paychannelBitDestination
	paychannelBitAmount
	paychannelBitBalance
	paychannelBitPublicKey
	paychannelBitSettleDelay
	paychannelBitExpiration
	paychannelBitCancelAfter
	paychannelBitSourceTag
	paychannelBitDestinationTag
	paychannelBitOwnerNode
	paychannelBitDestinationNode
	paychannelBitFlags
	paychannelBitPreviousTxnID
	paychannelBitPreviousTxnLgrSeq
)

// Decode populates the struct from binary ledger-entry data via a streaming
// reader. Unknown / sMD_Never fields are skipped without allocation.
func (p *PayChannel) Decode(data []byte) error {
	*p = PayChannel{}
	sr := newStreamReader(data)
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				_ = val // synthetic LedgerEntryType; discard
			default:
				return newErrUnknownField("PayChannel", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				p.Flags = val
				p.present |= paychannelBitFlags
			case 3:
				p.SourceTag = val
				p.present |= paychannelBitSourceTag
			case 5:
				p.PreviousTxnLgrSeq = val
				p.present |= paychannelBitPreviousTxnLgrSeq
			case 10:
				p.Expiration = val
				p.present |= paychannelBitExpiration
			case 14:
				p.DestinationTag = val
				p.present |= paychannelBitDestinationTag
			case 36:
				p.CancelAfter = val
				p.present |= paychannelBitCancelAfter
			case 39:
				p.SettleDelay = val
				p.present |= paychannelBitSettleDelay
			default:
				return newErrUnknownField("PayChannel", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 4:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				p.OwnerNode = val
				p.present |= paychannelBitOwnerNode
			case 9:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				p.DestinationNode = val
				p.present |= paychannelBitDestinationNode
			default:
				return newErrUnknownField("PayChannel", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				p.PreviousTxnID = val
				p.present |= paychannelBitPreviousTxnID
			default:
				return newErrUnknownField("PayChannel", typeCode, fieldCode)
			}
		case 6: // Amount
			val, err := sr.readAmountAny()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				p.Amount = val
				p.present |= paychannelBitAmount
			case 2:
				p.Balance = val
				p.present |= paychannelBitBalance
			default:
				return newErrUnknownField("PayChannel", typeCode, fieldCode)
			}
		case 7: // Blob
			val, err := sr.readBlobHex()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				p.PublicKey = val
				p.present |= paychannelBitPublicKey
			default:
				return newErrUnknownField("PayChannel", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				p.Account = val
				p.present |= paychannelBitAccount
			case 3:
				p.Destination = val
				p.present |= paychannelBitDestination
			default:
				return newErrUnknownField("PayChannel", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("PayChannel", typeCode, fieldCode)
		}
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (p *PayChannel) emitAll(out map[string]any, skipDefault bool) {
	if p.present&paychannelBitAccount != 0 && !(skipDefault && p.Account == "") {
		out["Account"] = p.Account
	}
	if p.present&paychannelBitDestination != 0 && !(skipDefault && p.Destination == "") {
		out["Destination"] = p.Destination
	}
	if p.present&paychannelBitAmount != 0 {
		out["Amount"] = p.Amount
	}
	if p.present&paychannelBitBalance != 0 {
		out["Balance"] = p.Balance
	}
	if p.present&paychannelBitPublicKey != 0 && !(skipDefault && p.PublicKey == "") {
		out["PublicKey"] = p.PublicKey
	}
	if p.present&paychannelBitSettleDelay != 0 && !(skipDefault && p.SettleDelay == 0) {
		out["SettleDelay"] = p.SettleDelay
	}
	if p.present&paychannelBitExpiration != 0 && !(skipDefault && p.Expiration == 0) {
		out["Expiration"] = p.Expiration
	}
	if p.present&paychannelBitCancelAfter != 0 && !(skipDefault && p.CancelAfter == 0) {
		out["CancelAfter"] = p.CancelAfter
	}
	if p.present&paychannelBitSourceTag != 0 && !(skipDefault && p.SourceTag == 0) {
		out["SourceTag"] = p.SourceTag
	}
	if p.present&paychannelBitDestinationTag != 0 && !(skipDefault && p.DestinationTag == 0) {
		out["DestinationTag"] = p.DestinationTag
	}
	if p.present&paychannelBitOwnerNode != 0 && !(skipDefault && isZeroHexString(p.OwnerNode)) {
		out["OwnerNode"] = p.OwnerNode
	}
	if p.present&paychannelBitDestinationNode != 0 && !(skipDefault && isZeroHexString(p.DestinationNode)) {
		out["DestinationNode"] = p.DestinationNode
	}
	if p.present&paychannelBitFlags != 0 && !(skipDefault && p.Flags == 0) {
		out["Flags"] = p.Flags
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (p *PayChannel) EmitNewFields(out map[string]any) {
	p.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (p *PayChannel) EmitFinalFields(out map[string]any) {
	p.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (p *PayChannel) EmitPreviousFields(prev Entry, out map[string]any) {
	p, ok := prev.(*PayChannel)
	if !ok || p == nil {
		return
	}
	emitIfChangedString(out, "Account", p.Account, p.Account, p.present&paychannelBitAccount, p.present&paychannelBitAccount)
	emitIfChangedString(out, "Destination", p.Destination, p.Destination, p.present&paychannelBitDestination, p.present&paychannelBitDestination)
	emitIfChangedAmount(out, "Amount", p.Amount, p.Amount, p.present&paychannelBitAmount, p.present&paychannelBitAmount)
	emitIfChangedAmount(out, "Balance", p.Balance, p.Balance, p.present&paychannelBitBalance, p.present&paychannelBitBalance)
	emitIfChangedString(out, "PublicKey", p.PublicKey, p.PublicKey, p.present&paychannelBitPublicKey, p.present&paychannelBitPublicKey)
	emitIfChangedUint32(out, "SettleDelay", p.SettleDelay, p.SettleDelay, p.present&paychannelBitSettleDelay, p.present&paychannelBitSettleDelay)
	emitIfChangedUint32(out, "Expiration", p.Expiration, p.Expiration, p.present&paychannelBitExpiration, p.present&paychannelBitExpiration)
	emitIfChangedUint32(out, "CancelAfter", p.CancelAfter, p.CancelAfter, p.present&paychannelBitCancelAfter, p.present&paychannelBitCancelAfter)
	emitIfChangedUint32(out, "SourceTag", p.SourceTag, p.SourceTag, p.present&paychannelBitSourceTag, p.present&paychannelBitSourceTag)
	emitIfChangedUint32(out, "DestinationTag", p.DestinationTag, p.DestinationTag, p.present&paychannelBitDestinationTag, p.present&paychannelBitDestinationTag)
	emitIfChangedString(out, "OwnerNode", p.OwnerNode, p.OwnerNode, p.present&paychannelBitOwnerNode, p.present&paychannelBitOwnerNode)
	emitIfChangedString(out, "DestinationNode", p.DestinationNode, p.DestinationNode, p.present&paychannelBitDestinationNode, p.present&paychannelBitDestinationNode)
	emitIfChangedUint32(out, "Flags", p.Flags, p.Flags, p.present&paychannelBitFlags, p.present&paychannelBitFlags)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (p *PayChannel) EmitChangeOrigFields(out map[string]any) {
	if p.present&paychannelBitAccount != 0 {
		out["Account"] = p.Account
	}
	if p.present&paychannelBitDestination != 0 {
		out["Destination"] = p.Destination
	}
	if p.present&paychannelBitAmount != 0 {
		out["Amount"] = p.Amount
	}
	if p.present&paychannelBitBalance != 0 {
		out["Balance"] = p.Balance
	}
	if p.present&paychannelBitPublicKey != 0 {
		out["PublicKey"] = p.PublicKey
	}
	if p.present&paychannelBitSettleDelay != 0 {
		out["SettleDelay"] = p.SettleDelay
	}
	if p.present&paychannelBitExpiration != 0 {
		out["Expiration"] = p.Expiration
	}
	if p.present&paychannelBitCancelAfter != 0 {
		out["CancelAfter"] = p.CancelAfter
	}
	if p.present&paychannelBitSourceTag != 0 {
		out["SourceTag"] = p.SourceTag
	}
	if p.present&paychannelBitDestinationTag != 0 {
		out["DestinationTag"] = p.DestinationTag
	}
	if p.present&paychannelBitOwnerNode != 0 {
		out["OwnerNode"] = p.OwnerNode
	}
	if p.present&paychannelBitDestinationNode != 0 {
		out["DestinationNode"] = p.DestinationNode
	}
	if p.present&paychannelBitFlags != 0 {
		out["Flags"] = p.Flags
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (p *PayChannel) EmitDeleteFinalFields(out map[string]any) {
	p.emitAll(out, false)
	if p.present&paychannelBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = p.PreviousTxnID
	}
	if p.present&paychannelBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = p.PreviousTxnLgrSeq
	}
}

func (p *PayChannel) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	p.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (p *PayChannel) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if p.present&paychannelBitPreviousTxnID != 0 {
		id = p.PreviousTxnID
	}
	if p.present&paychannelBitPreviousTxnLgrSeq != 0 {
		seq = p.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (p *PayChannel) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "PayChannel",
	}
	if p.present&paychannelBitAccount != 0 {
		out["Account"] = p.Account
	}
	if p.present&paychannelBitDestination != 0 {
		out["Destination"] = p.Destination
	}
	if p.present&paychannelBitAmount != 0 {
		out["Amount"] = p.Amount
	}
	if p.present&paychannelBitBalance != 0 {
		out["Balance"] = p.Balance
	}
	if p.present&paychannelBitPublicKey != 0 {
		out["PublicKey"] = p.PublicKey
	}
	if p.present&paychannelBitSettleDelay != 0 {
		out["SettleDelay"] = p.SettleDelay
	}
	if p.present&paychannelBitExpiration != 0 {
		out["Expiration"] = p.Expiration
	}
	if p.present&paychannelBitCancelAfter != 0 {
		out["CancelAfter"] = p.CancelAfter
	}
	if p.present&paychannelBitSourceTag != 0 {
		out["SourceTag"] = p.SourceTag
	}
	if p.present&paychannelBitDestinationTag != 0 {
		out["DestinationTag"] = p.DestinationTag
	}
	if p.present&paychannelBitOwnerNode != 0 {
		out["OwnerNode"] = p.OwnerNode
	}
	if p.present&paychannelBitDestinationNode != 0 {
		out["DestinationNode"] = p.DestinationNode
	}
	if p.present&paychannelBitFlags != 0 {
		out["Flags"] = p.Flags
	}
	if p.present&paychannelBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = p.PreviousTxnID
	}
	if p.present&paychannelBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = p.PreviousTxnLgrSeq
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Round-trip
// invariant: Decode(data); Encode() == data for any byte sequence that
// Decode accepts.
func (p *PayChannel) Encode() ([]byte, error) {
	return binarycodec.EncodeBytes(p.ToMap())
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (p *PayChannel) Hash(index [32]byte) ([32]byte, error) {
	data, err := p.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode
	return common.Sha512Half(prefix[:], data, index[:]), nil
}
