// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

import (
	"errors"
	"fmt"

	"github.com/LeJamon/go-xrpl/codec/binarycodec"
	"github.com/LeJamon/go-xrpl/crypto/sha512half"
	"github.com/LeJamon/go-xrpl/protocol"
)

func init() {
	Register("PayChannel", func() Entry { return new(PayChannel) })
}

// PayChannel is the typed representation of a PayChannel ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every canonical field declared in the spec — including those excluded from
// metadata (sMD_Never) — so decoding and re-encoding does not drop them.
type PayChannel struct {
	present           uint64
	decoded           bool
	dirty             bool
	Account           string // AccountID (base58)
	Destination       string // AccountID (base58)
	Sequence          uint32
	Amount            any    // Amount (XRP string | IOU map)
	Balance           any    // Amount (XRP string | IOU map)
	PublicKey         string // Blob (uppercase hex)
	SettleDelay       uint32
	Expiration        uint32
	CancelAfter       uint32
	SourceTag         uint32
	DestinationTag    uint32
	OwnerNode         string // UInt64 (lowercase hex, no leading zeros)
	DestinationNode   string // UInt64 (lowercase hex, no leading zeros)
	Flags             uint32
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
}

const (
	paychannelBitAccount uint64 = 1 << iota
	paychannelBitDestination
	paychannelBitSequence
	paychannelBitAmount
	paychannelBitBalance
	paychannelBitPublicKey
	paychannelBitSettleDelay
	paychannelBitExpiration
	paychannelBitCancelAfter
	paychannelBitSourceTag
	paychannelBitDestinationTag
	paychannelBitOwnerNode
	paychannelBitDestinationNode
	paychannelBitFlags
	paychannelBitPreviousTxnID
	paychannelBitPreviousTxnLgrSeq
)

// SetAccount assigns Account and updates its serialized presence.
func (p *PayChannel) SetAccount(value string) {
	p.Account = value
	p.dirty = true
	p.present |= paychannelBitAccount
}

// SetDestination assigns Destination and updates its serialized presence.
func (p *PayChannel) SetDestination(value string) {
	p.Destination = value
	p.dirty = true
	p.present |= paychannelBitDestination
}

// SetSequence assigns Sequence and updates its serialized presence.
func (p *PayChannel) SetSequence(value uint32) {
	p.Sequence = value
	p.dirty = true
	p.present |= paychannelBitSequence
}

// SetAmount assigns Amount and updates its serialized presence.
func (p *PayChannel) SetAmount(value any) {
	p.Amount = value
	p.dirty = true
	p.present |= paychannelBitAmount
}

// SetBalance assigns Balance and updates its serialized presence.
func (p *PayChannel) SetBalance(value any) {
	p.Balance = value
	p.dirty = true
	p.present |= paychannelBitBalance
}

// SetPublicKey assigns PublicKey and updates its serialized presence.
func (p *PayChannel) SetPublicKey(value string) {
	p.PublicKey = value
	p.dirty = true
	p.present |= paychannelBitPublicKey
}

// SetSettleDelay assigns SettleDelay and updates its serialized presence.
func (p *PayChannel) SetSettleDelay(value uint32) {
	p.SettleDelay = value
	p.dirty = true
	p.present |= paychannelBitSettleDelay
}

// SetExpiration assigns Expiration and updates its serialized presence.
func (p *PayChannel) SetExpiration(value uint32) {
	p.Expiration = value
	p.dirty = true
	p.present |= paychannelBitExpiration
}

// SetCancelAfter assigns CancelAfter and updates its serialized presence.
func (p *PayChannel) SetCancelAfter(value uint32) {
	p.CancelAfter = value
	p.dirty = true
	p.present |= paychannelBitCancelAfter
}

// SetSourceTag assigns SourceTag and updates its serialized presence.
func (p *PayChannel) SetSourceTag(value uint32) {
	p.SourceTag = value
	p.dirty = true
	p.present |= paychannelBitSourceTag
}

// SetDestinationTag assigns DestinationTag and updates its serialized presence.
func (p *PayChannel) SetDestinationTag(value uint32) {
	p.DestinationTag = value
	p.dirty = true
	p.present |= paychannelBitDestinationTag
}

// SetOwnerNode assigns OwnerNode and updates its serialized presence.
func (p *PayChannel) SetOwnerNode(value string) {
	p.OwnerNode = value
	p.dirty = true
	p.present |= paychannelBitOwnerNode
}

// SetDestinationNode assigns DestinationNode and updates its serialized presence.
func (p *PayChannel) SetDestinationNode(value string) {
	p.DestinationNode = value
	p.dirty = true
	p.present |= paychannelBitDestinationNode
}

// SetFlags assigns Flags and updates its serialized presence.
func (p *PayChannel) SetFlags(value uint32) {
	p.Flags = value
	p.dirty = true
	p.present |= paychannelBitFlags
}

// SetPreviousTxnID assigns PreviousTxnID and updates its serialized presence.
func (p *PayChannel) SetPreviousTxnID(value string) {
	p.PreviousTxnID = value
	p.dirty = true
	p.present |= paychannelBitPreviousTxnID
}

// SetPreviousTxnLgrSeq assigns PreviousTxnLgrSeq and updates its serialized presence.
func (p *PayChannel) SetPreviousTxnLgrSeq(value uint32) {
	p.PreviousTxnLgrSeq = value
	p.dirty = true
	p.present |= paychannelBitPreviousTxnLgrSeq
}

func (p *PayChannel) validateRequired() error {
	if p.decoded && !p.dirty {
		return nil
	}
	if p.present&paychannelBitAccount == 0 {
		return errors.New("ledgerfields: PayChannel: required field Account is not set")
	}
	if p.present&paychannelBitDestination == 0 {
		return errors.New("ledgerfields: PayChannel: required field Destination is not set")
	}
	if p.present&paychannelBitAmount == 0 {
		return errors.New("ledgerfields: PayChannel: required field Amount is not set")
	}
	if p.present&paychannelBitBalance == 0 {
		return errors.New("ledgerfields: PayChannel: required field Balance is not set")
	}
	if p.present&paychannelBitPublicKey == 0 {
		return errors.New("ledgerfields: PayChannel: required field PublicKey is not set")
	}
	if p.present&paychannelBitSettleDelay == 0 {
		return errors.New("ledgerfields: PayChannel: required field SettleDelay is not set")
	}
	if p.present&paychannelBitOwnerNode == 0 {
		return errors.New("ledgerfields: PayChannel: required field OwnerNode is not set")
	}
	if p.present&paychannelBitFlags == 0 {
		return errors.New("ledgerfields: PayChannel: required field Flags is not set")
	}
	return nil
}

func (p *PayChannel) validateDecoded() error {
	if p.present&paychannelBitAccount == 0 {
		return errors.New("ledgerfields: PayChannel: required field Account is missing")
	}
	if p.present&paychannelBitDestination == 0 {
		return errors.New("ledgerfields: PayChannel: required field Destination is missing")
	}
	if p.present&paychannelBitAmount == 0 {
		return errors.New("ledgerfields: PayChannel: required field Amount is missing")
	}
	if p.present&paychannelBitBalance == 0 {
		return errors.New("ledgerfields: PayChannel: required field Balance is missing")
	}
	if p.present&paychannelBitPublicKey == 0 {
		return errors.New("ledgerfields: PayChannel: required field PublicKey is missing")
	}
	if p.present&paychannelBitSettleDelay == 0 {
		return errors.New("ledgerfields: PayChannel: required field SettleDelay is missing")
	}
	if p.present&paychannelBitOwnerNode == 0 {
		return errors.New("ledgerfields: PayChannel: required field OwnerNode is missing")
	}
	if p.present&paychannelBitFlags == 0 {
		return errors.New("ledgerfields: PayChannel: required field Flags is missing")
	}
	if p.present&paychannelBitPreviousTxnID == 0 {
		return errors.New("ledgerfields: PayChannel: required field PreviousTxnID is missing")
	}
	if p.present&paychannelBitPreviousTxnLgrSeq == 0 {
		return errors.New("ledgerfields: PayChannel: required field PreviousTxnLgrSeq is missing")
	}
	return nil
}

// Decode populates the struct from binary ledger-entry data via a streaming
// reader and enforces the current rippled ledger template.
func (p *PayChannel) Decode(data []byte) error {
	return p.decode(data, false)
}

func (p *PayChannel) decodeLegacy(data []byte) error {
	return p.decode(data, true)
}

func (p *PayChannel) decode(data []byte, legacy bool) error {
	*p = PayChannel{}
	sr := newStreamReader(data)
	seenFields := make(map[[2]int]struct{})
	sawLedgerEntryType := false
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		fieldID := [2]int{typeCode, fieldCode}
		if _, exists := seenFields[fieldID]; exists {
			return fmt.Errorf("ledgerfields: PayChannel: duplicate field type=%d field=%d", typeCode, fieldCode)
		}
		seenFields[fieldID] = struct{}{}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				if val != 120 {
					return fmt.Errorf("ledgerfields: PayChannel: LedgerEntryType is %d, want 120", val)
				}
				sawLedgerEntryType = true
			default:
				return newErrUnknownField("PayChannel", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				p.Flags = val
				p.present |= paychannelBitFlags
			case 3:
				p.SourceTag = val
				p.present |= paychannelBitSourceTag
			case 4:
				p.Sequence = val
				p.present |= paychannelBitSequence
			case 5:
				p.PreviousTxnLgrSeq = val
				p.present |= paychannelBitPreviousTxnLgrSeq
			case 10:
				p.Expiration = val
				p.present |= paychannelBitExpiration
			case 14:
				p.DestinationTag = val
				p.present |= paychannelBitDestinationTag
			case 36:
				p.CancelAfter = val
				p.present |= paychannelBitCancelAfter
			case 39:
				p.SettleDelay = val
				p.present |= paychannelBitSettleDelay
			default:
				return newErrUnknownField("PayChannel", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 4:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				p.OwnerNode = val
				p.present |= paychannelBitOwnerNode
			case 9:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				p.DestinationNode = val
				p.present |= paychannelBitDestinationNode
			default:
				return newErrUnknownField("PayChannel", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				p.PreviousTxnID = val
				p.present |= paychannelBitPreviousTxnID
			default:
				return newErrUnknownField("PayChannel", typeCode, fieldCode)
			}
		case 6: // Amount
			val, err := sr.readAmountAny()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				p.Amount = val
				p.present |= paychannelBitAmount
			case 2:
				p.Balance = val
				p.present |= paychannelBitBalance
			default:
				return newErrUnknownField("PayChannel", typeCode, fieldCode)
			}
		case 7: // Blob
			val, err := sr.readBlobHex()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				p.PublicKey = val
				p.present |= paychannelBitPublicKey
			default:
				return newErrUnknownField("PayChannel", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				p.Account = val
				p.present |= paychannelBitAccount
			case 3:
				p.Destination = val
				p.present |= paychannelBitDestination
			default:
				return newErrUnknownField("PayChannel", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("PayChannel", typeCode, fieldCode)
		}
	}
	if !sawLedgerEntryType {
		return errors.New("ledgerfields: PayChannel: missing LedgerEntryType")
	}
	p.decoded = true
	if !legacy {
		return p.validateDecoded()
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (p *PayChannel) emitAll(out map[string]any, skipDefault bool) {
	if p.present&paychannelBitAccount != 0 && !(skipDefault && p.Account == "") {
		out["Account"] = p.Account
	}
	if p.present&paychannelBitDestination != 0 && !(skipDefault && p.Destination == "") {
		out["Destination"] = p.Destination
	}
	if p.present&paychannelBitSequence != 0 && !(skipDefault && p.Sequence == 0) {
		out["Sequence"] = p.Sequence
	}
	if p.present&paychannelBitAmount != 0 && !(skipDefault && amountIsDefault(p.Amount)) {
		out["Amount"] = p.Amount
	}
	if p.present&paychannelBitBalance != 0 && !(skipDefault && amountIsDefault(p.Balance)) {
		out["Balance"] = p.Balance
	}
	if p.present&paychannelBitPublicKey != 0 && !(skipDefault && p.PublicKey == "") {
		out["PublicKey"] = p.PublicKey
	}
	if p.present&paychannelBitSettleDelay != 0 && !(skipDefault && p.SettleDelay == 0) {
		out["SettleDelay"] = p.SettleDelay
	}
	if p.present&paychannelBitExpiration != 0 && !(skipDefault && p.Expiration == 0) {
		out["Expiration"] = p.Expiration
	}
	if p.present&paychannelBitCancelAfter != 0 && !(skipDefault && p.CancelAfter == 0) {
		out["CancelAfter"] = p.CancelAfter
	}
	if p.present&paychannelBitSourceTag != 0 && !(skipDefault && p.SourceTag == 0) {
		out["SourceTag"] = p.SourceTag
	}
	if p.present&paychannelBitDestinationTag != 0 && !(skipDefault && p.DestinationTag == 0) {
		out["DestinationTag"] = p.DestinationTag
	}
	if p.present&paychannelBitOwnerNode != 0 && !(skipDefault && isZeroHexString(p.OwnerNode)) {
		out["OwnerNode"] = p.OwnerNode
	}
	if p.present&paychannelBitDestinationNode != 0 && !(skipDefault && isZeroHexString(p.DestinationNode)) {
		out["DestinationNode"] = p.DestinationNode
	}
	if p.present&paychannelBitFlags != 0 && !(skipDefault && p.Flags == 0) {
		out["Flags"] = p.Flags
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (p *PayChannel) EmitNewFields(out map[string]any) {
	p.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (p *PayChannel) EmitFinalFields(out map[string]any) {
	p.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (p *PayChannel) EmitPreviousFields(prev Entry, out map[string]any) {
	prv, ok := prev.(*PayChannel)
	if !ok || prv == nil {
		return
	}
	emitIfChangedString(out, "Account", prv.Account, p.Account, prv.present&paychannelBitAccount, p.present&paychannelBitAccount)
	emitIfChangedString(out, "Destination", prv.Destination, p.Destination, prv.present&paychannelBitDestination, p.present&paychannelBitDestination)
	emitIfChangedUint32(out, "Sequence", prv.Sequence, p.Sequence, prv.present&paychannelBitSequence, p.present&paychannelBitSequence)
	emitIfChangedAmount(out, "Amount", prv.Amount, p.Amount, prv.present&paychannelBitAmount, p.present&paychannelBitAmount)
	emitIfChangedAmount(out, "Balance", prv.Balance, p.Balance, prv.present&paychannelBitBalance, p.present&paychannelBitBalance)
	emitIfChangedString(out, "PublicKey", prv.PublicKey, p.PublicKey, prv.present&paychannelBitPublicKey, p.present&paychannelBitPublicKey)
	emitIfChangedUint32(out, "SettleDelay", prv.SettleDelay, p.SettleDelay, prv.present&paychannelBitSettleDelay, p.present&paychannelBitSettleDelay)
	emitIfChangedUint32(out, "Expiration", prv.Expiration, p.Expiration, prv.present&paychannelBitExpiration, p.present&paychannelBitExpiration)
	emitIfChangedUint32(out, "CancelAfter", prv.CancelAfter, p.CancelAfter, prv.present&paychannelBitCancelAfter, p.present&paychannelBitCancelAfter)
	emitIfChangedUint32(out, "SourceTag", prv.SourceTag, p.SourceTag, prv.present&paychannelBitSourceTag, p.present&paychannelBitSourceTag)
	emitIfChangedUint32(out, "DestinationTag", prv.DestinationTag, p.DestinationTag, prv.present&paychannelBitDestinationTag, p.present&paychannelBitDestinationTag)
	emitIfChangedString(out, "OwnerNode", prv.OwnerNode, p.OwnerNode, prv.present&paychannelBitOwnerNode, p.present&paychannelBitOwnerNode)
	emitIfChangedString(out, "DestinationNode", prv.DestinationNode, p.DestinationNode, prv.present&paychannelBitDestinationNode, p.present&paychannelBitDestinationNode)
	emitIfChangedUint32(out, "Flags", prv.Flags, p.Flags, prv.present&paychannelBitFlags, p.present&paychannelBitFlags)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (p *PayChannel) EmitChangeOrigFields(out map[string]any) {
	if p.present&paychannelBitAccount != 0 {
		out["Account"] = p.Account
	}
	if p.present&paychannelBitDestination != 0 {
		out["Destination"] = p.Destination
	}
	if p.present&paychannelBitSequence != 0 {
		out["Sequence"] = p.Sequence
	}
	if p.present&paychannelBitAmount != 0 {
		out["Amount"] = p.Amount
	}
	if p.present&paychannelBitBalance != 0 {
		out["Balance"] = p.Balance
	}
	if p.present&paychannelBitPublicKey != 0 {
		out["PublicKey"] = p.PublicKey
	}
	if p.present&paychannelBitSettleDelay != 0 {
		out["SettleDelay"] = p.SettleDelay
	}
	if p.present&paychannelBitExpiration != 0 {
		out["Expiration"] = p.Expiration
	}
	if p.present&paychannelBitCancelAfter != 0 {
		out["CancelAfter"] = p.CancelAfter
	}
	if p.present&paychannelBitSourceTag != 0 {
		out["SourceTag"] = p.SourceTag
	}
	if p.present&paychannelBitDestinationTag != 0 {
		out["DestinationTag"] = p.DestinationTag
	}
	if p.present&paychannelBitOwnerNode != 0 {
		out["OwnerNode"] = p.OwnerNode
	}
	if p.present&paychannelBitDestinationNode != 0 {
		out["DestinationNode"] = p.DestinationNode
	}
	if p.present&paychannelBitFlags != 0 {
		out["Flags"] = p.Flags
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (p *PayChannel) EmitDeleteFinalFields(out map[string]any) {
	p.emitAll(out, false)
	if p.present&paychannelBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = p.PreviousTxnID
	}
	if p.present&paychannelBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = p.PreviousTxnLgrSeq
	}
}

func (p *PayChannel) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	p.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (p *PayChannel) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if p.present&paychannelBitPreviousTxnID != 0 {
		id = p.PreviousTxnID
	}
	if p.present&paychannelBitPreviousTxnLgrSeq != 0 {
		seq = p.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (p *PayChannel) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "PayChannel",
	}
	if p.present&paychannelBitAccount != 0 {
		out["Account"] = p.Account
	}
	if p.present&paychannelBitDestination != 0 {
		out["Destination"] = p.Destination
	}
	if p.present&paychannelBitSequence != 0 {
		out["Sequence"] = p.Sequence
	}
	if p.present&paychannelBitAmount != 0 {
		out["Amount"] = p.Amount
	}
	if p.present&paychannelBitBalance != 0 {
		out["Balance"] = p.Balance
	}
	if p.present&paychannelBitPublicKey != 0 {
		out["PublicKey"] = p.PublicKey
	}
	if p.present&paychannelBitSettleDelay != 0 {
		out["SettleDelay"] = p.SettleDelay
	}
	if p.present&paychannelBitExpiration != 0 {
		out["Expiration"] = p.Expiration
	}
	if p.present&paychannelBitCancelAfter != 0 {
		out["CancelAfter"] = p.CancelAfter
	}
	if p.present&paychannelBitSourceTag != 0 {
		out["SourceTag"] = p.SourceTag
	}
	if p.present&paychannelBitDestinationTag != 0 {
		out["DestinationTag"] = p.DestinationTag
	}
	if p.present&paychannelBitOwnerNode != 0 {
		out["OwnerNode"] = p.OwnerNode
	}
	if p.present&paychannelBitDestinationNode != 0 {
		out["DestinationNode"] = p.DestinationNode
	}
	if p.present&paychannelBitFlags != 0 {
		out["Flags"] = p.Flags
	}
	if p.present&paychannelBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = p.PreviousTxnID
	}
	if p.present&paychannelBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = p.PreviousTxnLgrSeq
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Legacy decode
// aliases and non-canonical input ordering are emitted in canonical form.
func (p *PayChannel) Encode() ([]byte, error) {
	if err := p.validateRequired(); err != nil {
		return nil, err
	}
	return binarycodec.EncodeBytes(p.ToMap())
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (p *PayChannel) Hash(index [32]byte) ([32]byte, error) {
	data, err := p.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode()
	return sha512half.Sum(prefix[:], data, index[:]), nil
}
