// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

import (
	"errors"
	"fmt"

	"github.com/LeJamon/go-xrpl/codec/binarycodec"
	"github.com/LeJamon/go-xrpl/crypto/sha512half"
	"github.com/LeJamon/go-xrpl/protocol"
)

func init() {
	Register("RippleState", func() Entry { return new(RippleState) })
}

// RippleState is the typed representation of a RippleState ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every canonical field declared in the spec — including those excluded from
// metadata (sMD_Never) — so decoding and re-encoding does not drop them.
type RippleState struct {
	present           uint64
	decoded           bool
	dirty             bool
	decodedBinary     []byte
	Flags             uint32
	Balance           any    // Amount (XRP string | IOU map)
	LowLimit          any    // Amount (XRP string | IOU map)
	HighLimit         any    // Amount (XRP string | IOU map)
	LowNode           string // UInt64 (lowercase hex, no leading zeros)
	HighNode          string // UInt64 (lowercase hex, no leading zeros)
	LowQualityIn      uint32
	LowQualityOut     uint32
	HighQualityIn     uint32
	HighQualityOut    uint32
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
}

const (
	ripplestateBitFlags uint64 = 1 << iota
	ripplestateBitBalance
	ripplestateBitLowLimit
	ripplestateBitHighLimit
	ripplestateBitLowNode
	ripplestateBitHighNode
	ripplestateBitLowQualityIn
	ripplestateBitLowQualityOut
	ripplestateBitHighQualityIn
	ripplestateBitHighQualityOut
	ripplestateBitPreviousTxnID
	ripplestateBitPreviousTxnLgrSeq
)

// SetFlags assigns Flags and updates its serialized presence.
func (r *RippleState) SetFlags(value uint32) {
	r.Flags = value
	r.dirty = true
	r.present |= ripplestateBitFlags
}

// SetBalance assigns Balance and updates its serialized presence.
func (r *RippleState) SetBalance(value any) {
	r.Balance = value
	r.dirty = true
	r.present |= ripplestateBitBalance
}

// SetLowLimit assigns LowLimit and updates its serialized presence.
func (r *RippleState) SetLowLimit(value any) {
	r.LowLimit = value
	r.dirty = true
	r.present |= ripplestateBitLowLimit
}

// SetHighLimit assigns HighLimit and updates its serialized presence.
func (r *RippleState) SetHighLimit(value any) {
	r.HighLimit = value
	r.dirty = true
	r.present |= ripplestateBitHighLimit
}

// SetLowNode assigns LowNode and updates its serialized presence.
func (r *RippleState) SetLowNode(value string) {
	r.LowNode = value
	r.dirty = true
	r.present |= ripplestateBitLowNode
}

// SetHighNode assigns HighNode and updates its serialized presence.
func (r *RippleState) SetHighNode(value string) {
	r.HighNode = value
	r.dirty = true
	r.present |= ripplestateBitHighNode
}

// SetLowQualityIn assigns LowQualityIn and updates its serialized presence.
func (r *RippleState) SetLowQualityIn(value uint32) {
	r.LowQualityIn = value
	r.dirty = true
	r.present |= ripplestateBitLowQualityIn
}

// SetLowQualityOut assigns LowQualityOut and updates its serialized presence.
func (r *RippleState) SetLowQualityOut(value uint32) {
	r.LowQualityOut = value
	r.dirty = true
	r.present |= ripplestateBitLowQualityOut
}

// SetHighQualityIn assigns HighQualityIn and updates its serialized presence.
func (r *RippleState) SetHighQualityIn(value uint32) {
	r.HighQualityIn = value
	r.dirty = true
	r.present |= ripplestateBitHighQualityIn
}

// SetHighQualityOut assigns HighQualityOut and updates its serialized presence.
func (r *RippleState) SetHighQualityOut(value uint32) {
	r.HighQualityOut = value
	r.dirty = true
	r.present |= ripplestateBitHighQualityOut
}

// SetPreviousTxnID assigns PreviousTxnID and updates its serialized presence.
func (r *RippleState) SetPreviousTxnID(value string) {
	r.PreviousTxnID = value
	r.dirty = true
	r.present |= ripplestateBitPreviousTxnID
}

// SetPreviousTxnLgrSeq assigns PreviousTxnLgrSeq and updates its serialized presence.
func (r *RippleState) SetPreviousTxnLgrSeq(value uint32) {
	r.PreviousTxnLgrSeq = value
	r.dirty = true
	r.present |= ripplestateBitPreviousTxnLgrSeq
}

func (r *RippleState) validateRequired() error {
	if r.decoded && !r.dirty {
		return nil
	}
	if r.present&ripplestateBitFlags == 0 {
		return errors.New("ledgerfields: RippleState: required field Flags is not set")
	}
	if r.present&ripplestateBitBalance == 0 {
		return errors.New("ledgerfields: RippleState: required field Balance is not set")
	}
	if r.present&ripplestateBitLowLimit == 0 {
		return errors.New("ledgerfields: RippleState: required field LowLimit is not set")
	}
	if r.present&ripplestateBitHighLimit == 0 {
		return errors.New("ledgerfields: RippleState: required field HighLimit is not set")
	}
	return nil
}

func (r *RippleState) validateDecoded() error {
	if r.present&ripplestateBitFlags == 0 {
		return errors.New("ledgerfields: RippleState: required field Flags is missing")
	}
	if r.present&ripplestateBitBalance == 0 {
		return errors.New("ledgerfields: RippleState: required field Balance is missing")
	}
	if r.present&ripplestateBitLowLimit == 0 {
		return errors.New("ledgerfields: RippleState: required field LowLimit is missing")
	}
	if r.present&ripplestateBitHighLimit == 0 {
		return errors.New("ledgerfields: RippleState: required field HighLimit is missing")
	}
	if r.present&ripplestateBitPreviousTxnID == 0 {
		return errors.New("ledgerfields: RippleState: required field PreviousTxnID is missing")
	}
	if r.present&ripplestateBitPreviousTxnLgrSeq == 0 {
		return errors.New("ledgerfields: RippleState: required field PreviousTxnLgrSeq is missing")
	}
	return nil
}

// Decode populates the struct from binary ledger-entry data via a streaming
// reader and enforces the current rippled ledger template.
func (r *RippleState) Decode(data []byte) error {
	return r.decode(data, false)
}

func (r *RippleState) decodeLegacy(data []byte) error {
	return r.decode(data, true)
}

func (r *RippleState) decode(data []byte, legacy bool) error {
	*r = RippleState{}
	sr := newStreamReader(data)
	seenFields := make(map[[2]int]struct{})
	sawLedgerEntryType := false
	preserveDecodedBinary := false
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		fieldID := [2]int{typeCode, fieldCode}
		if _, exists := seenFields[fieldID]; exists {
			return fmt.Errorf("ledgerfields: RippleState: duplicate field type=%d field=%d", typeCode, fieldCode)
		}
		seenFields[fieldID] = struct{}{}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				if val != 114 {
					return fmt.Errorf("ledgerfields: RippleState: LedgerEntryType is %d, want 114", val)
				}
				sawLedgerEntryType = true
			default:
				return newErrUnknownField("RippleState", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				r.Flags = val
				r.present |= ripplestateBitFlags
			case 5:
				r.PreviousTxnLgrSeq = val
				r.present |= ripplestateBitPreviousTxnLgrSeq
			case 16:
				r.HighQualityIn = val
				r.present |= ripplestateBitHighQualityIn
			case 17:
				r.HighQualityOut = val
				r.present |= ripplestateBitHighQualityOut
			case 18:
				r.LowQualityIn = val
				r.present |= ripplestateBitLowQualityIn
			case 19:
				r.LowQualityOut = val
				r.present |= ripplestateBitLowQualityOut
			default:
				return newErrUnknownField("RippleState", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 7:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				r.LowNode = val
				r.present |= ripplestateBitLowNode
			case 8:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				r.HighNode = val
				r.present |= ripplestateBitHighNode
			default:
				return newErrUnknownField("RippleState", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				r.PreviousTxnID = val
				r.present |= ripplestateBitPreviousTxnID
			default:
				return newErrUnknownField("RippleState", typeCode, fieldCode)
			}
		case 6: // Amount
			val, badCurrency, err := sr.readAmountAnyAllowBadCurrency()
			preserveDecodedBinary = preserveDecodedBinary || badCurrency
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				r.Balance = val
				r.present |= ripplestateBitBalance
			case 6:
				r.LowLimit = val
				r.present |= ripplestateBitLowLimit
			case 7:
				r.HighLimit = val
				r.present |= ripplestateBitHighLimit
			default:
				return newErrUnknownField("RippleState", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("RippleState", typeCode, fieldCode)
		}
	}
	if !sawLedgerEntryType {
		return errors.New("ledgerfields: RippleState: missing LedgerEntryType")
	}
	if preserveDecodedBinary {
		r.decodedBinary = append([]byte(nil), data...)
	}
	r.decoded = true
	if !legacy {
		return r.validateDecoded()
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (r *RippleState) emitAll(out map[string]any, skipDefault bool) {
	if r.present&ripplestateBitFlags != 0 && !(skipDefault && r.Flags == 0) {
		out["Flags"] = r.Flags
	}
	if r.present&ripplestateBitBalance != 0 && !(skipDefault && amountIsDefault(r.Balance)) {
		out["Balance"] = r.Balance
	}
	if r.present&ripplestateBitLowLimit != 0 && !(skipDefault && amountIsDefault(r.LowLimit)) {
		out["LowLimit"] = r.LowLimit
	}
	if r.present&ripplestateBitHighLimit != 0 && !(skipDefault && amountIsDefault(r.HighLimit)) {
		out["HighLimit"] = r.HighLimit
	}
	if r.present&ripplestateBitLowNode != 0 && !(skipDefault && isZeroHexString(r.LowNode)) {
		out["LowNode"] = r.LowNode
	}
	if r.present&ripplestateBitHighNode != 0 && !(skipDefault && isZeroHexString(r.HighNode)) {
		out["HighNode"] = r.HighNode
	}
	if r.present&ripplestateBitLowQualityIn != 0 && !(skipDefault && r.LowQualityIn == 0) {
		out["LowQualityIn"] = r.LowQualityIn
	}
	if r.present&ripplestateBitLowQualityOut != 0 && !(skipDefault && r.LowQualityOut == 0) {
		out["LowQualityOut"] = r.LowQualityOut
	}
	if r.present&ripplestateBitHighQualityIn != 0 && !(skipDefault && r.HighQualityIn == 0) {
		out["HighQualityIn"] = r.HighQualityIn
	}
	if r.present&ripplestateBitHighQualityOut != 0 && !(skipDefault && r.HighQualityOut == 0) {
		out["HighQualityOut"] = r.HighQualityOut
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (r *RippleState) EmitNewFields(out map[string]any) {
	r.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (r *RippleState) EmitFinalFields(out map[string]any) {
	r.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (r *RippleState) EmitPreviousFields(prev Entry, out map[string]any) {
	prv, ok := prev.(*RippleState)
	if !ok || prv == nil {
		return
	}
	emitIfChangedUint32(out, "Flags", prv.Flags, r.Flags, prv.present&ripplestateBitFlags, r.present&ripplestateBitFlags)
	emitIfChangedAmount(out, "Balance", prv.Balance, r.Balance, prv.present&ripplestateBitBalance, r.present&ripplestateBitBalance)
	emitIfChangedAmount(out, "LowLimit", prv.LowLimit, r.LowLimit, prv.present&ripplestateBitLowLimit, r.present&ripplestateBitLowLimit)
	emitIfChangedAmount(out, "HighLimit", prv.HighLimit, r.HighLimit, prv.present&ripplestateBitHighLimit, r.present&ripplestateBitHighLimit)
	emitIfChangedString(out, "LowNode", prv.LowNode, r.LowNode, prv.present&ripplestateBitLowNode, r.present&ripplestateBitLowNode)
	emitIfChangedString(out, "HighNode", prv.HighNode, r.HighNode, prv.present&ripplestateBitHighNode, r.present&ripplestateBitHighNode)
	emitIfChangedUint32(out, "LowQualityIn", prv.LowQualityIn, r.LowQualityIn, prv.present&ripplestateBitLowQualityIn, r.present&ripplestateBitLowQualityIn)
	emitIfChangedUint32(out, "LowQualityOut", prv.LowQualityOut, r.LowQualityOut, prv.present&ripplestateBitLowQualityOut, r.present&ripplestateBitLowQualityOut)
	emitIfChangedUint32(out, "HighQualityIn", prv.HighQualityIn, r.HighQualityIn, prv.present&ripplestateBitHighQualityIn, r.present&ripplestateBitHighQualityIn)
	emitIfChangedUint32(out, "HighQualityOut", prv.HighQualityOut, r.HighQualityOut, prv.present&ripplestateBitHighQualityOut, r.present&ripplestateBitHighQualityOut)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (r *RippleState) EmitChangeOrigFields(out map[string]any) {
	if r.present&ripplestateBitFlags != 0 {
		out["Flags"] = r.Flags
	}
	if r.present&ripplestateBitBalance != 0 {
		out["Balance"] = r.Balance
	}
	if r.present&ripplestateBitLowLimit != 0 {
		out["LowLimit"] = r.LowLimit
	}
	if r.present&ripplestateBitHighLimit != 0 {
		out["HighLimit"] = r.HighLimit
	}
	if r.present&ripplestateBitLowNode != 0 {
		out["LowNode"] = r.LowNode
	}
	if r.present&ripplestateBitHighNode != 0 {
		out["HighNode"] = r.HighNode
	}
	if r.present&ripplestateBitLowQualityIn != 0 {
		out["LowQualityIn"] = r.LowQualityIn
	}
	if r.present&ripplestateBitLowQualityOut != 0 {
		out["LowQualityOut"] = r.LowQualityOut
	}
	if r.present&ripplestateBitHighQualityIn != 0 {
		out["HighQualityIn"] = r.HighQualityIn
	}
	if r.present&ripplestateBitHighQualityOut != 0 {
		out["HighQualityOut"] = r.HighQualityOut
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (r *RippleState) EmitDeleteFinalFields(out map[string]any) {
	r.emitAll(out, false)
	if r.present&ripplestateBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = r.PreviousTxnID
	}
	if r.present&ripplestateBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = r.PreviousTxnLgrSeq
	}
}

func (r *RippleState) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	r.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (r *RippleState) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if r.present&ripplestateBitPreviousTxnID != 0 {
		id = r.PreviousTxnID
	}
	if r.present&ripplestateBitPreviousTxnLgrSeq != 0 {
		seq = r.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (r *RippleState) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "RippleState",
	}
	if r.present&ripplestateBitFlags != 0 {
		out["Flags"] = r.Flags
	}
	if r.present&ripplestateBitBalance != 0 {
		out["Balance"] = r.Balance
	}
	if r.present&ripplestateBitLowLimit != 0 {
		out["LowLimit"] = r.LowLimit
	}
	if r.present&ripplestateBitHighLimit != 0 {
		out["HighLimit"] = r.HighLimit
	}
	if r.present&ripplestateBitLowNode != 0 {
		out["LowNode"] = r.LowNode
	}
	if r.present&ripplestateBitHighNode != 0 {
		out["HighNode"] = r.HighNode
	}
	if r.present&ripplestateBitLowQualityIn != 0 {
		out["LowQualityIn"] = r.LowQualityIn
	}
	if r.present&ripplestateBitLowQualityOut != 0 {
		out["LowQualityOut"] = r.LowQualityOut
	}
	if r.present&ripplestateBitHighQualityIn != 0 {
		out["HighQualityIn"] = r.HighQualityIn
	}
	if r.present&ripplestateBitHighQualityOut != 0 {
		out["HighQualityOut"] = r.HighQualityOut
	}
	if r.present&ripplestateBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = r.PreviousTxnID
	}
	if r.present&ripplestateBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = r.PreviousTxnLgrSeq
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Legacy decode
// aliases and non-canonical input ordering are emitted in canonical form.
func (r *RippleState) Encode() ([]byte, error) {
	if err := r.validateRequired(); err != nil {
		return nil, err
	}
	if r.decoded && !r.dirty && len(r.decodedBinary) != 0 {
		return append([]byte(nil), r.decodedBinary...), nil
	}
	return binarycodec.EncodeBytes(r.ToMap())
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (r *RippleState) Hash(index [32]byte) ([32]byte, error) {
	data, err := r.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode()
	return sha512half.Sum(prefix[:], data, index[:]), nil
}
