// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

import (
	"github.com/LeJamon/go-xrpl/codec/binarycodec"
	"github.com/LeJamon/go-xrpl/crypto/common"
	"github.com/LeJamon/go-xrpl/protocol"
)

func init() {
	Register("RippleState", func() Entry { return new(RippleState) })
}

// RippleState is the typed representation of a RippleState ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every on-wire field — including those excluded from metadata
// (sMD_Never) — so Decode → Encode is byte-identical.
type RippleState struct {
	present           uint64
	Flags             uint32
	Balance           any    // Amount (XRP string | IOU map)
	LowLimit          any    // Amount (XRP string | IOU map)
	HighLimit         any    // Amount (XRP string | IOU map)
	LowNode           string // UInt64 (lowercase hex, no leading zeros)
	HighNode          string // UInt64 (lowercase hex, no leading zeros)
	LowQualityIn      uint32
	LowQualityOut     uint32
	HighQualityIn     uint32
	HighQualityOut    uint32
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
}

const (
	ripplestateBitFlags uint64 = 1 << iota
	ripplestateBitBalance
	ripplestateBitLowLimit
	ripplestateBitHighLimit
	ripplestateBitLowNode
	ripplestateBitHighNode
	ripplestateBitLowQualityIn
	ripplestateBitLowQualityOut
	ripplestateBitHighQualityIn
	ripplestateBitHighQualityOut
	ripplestateBitPreviousTxnID
	ripplestateBitPreviousTxnLgrSeq
)

// Decode populates the struct from binary ledger-entry data via a streaming
// reader. Unknown / sMD_Never fields are skipped without allocation.
func (r *RippleState) Decode(data []byte) error {
	*r = RippleState{}
	sr := newStreamReader(data)
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				_ = val // synthetic LedgerEntryType; discard
			default:
				return newErrUnknownField("RippleState", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				r.Flags = val
				r.present |= ripplestateBitFlags
			case 5:
				r.PreviousTxnLgrSeq = val
				r.present |= ripplestateBitPreviousTxnLgrSeq
			case 16:
				r.HighQualityIn = val
				r.present |= ripplestateBitHighQualityIn
			case 17:
				r.HighQualityOut = val
				r.present |= ripplestateBitHighQualityOut
			case 18:
				r.LowQualityIn = val
				r.present |= ripplestateBitLowQualityIn
			case 19:
				r.LowQualityOut = val
				r.present |= ripplestateBitLowQualityOut
			default:
				return newErrUnknownField("RippleState", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 7:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				r.LowNode = val
				r.present |= ripplestateBitLowNode
			case 8:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				r.HighNode = val
				r.present |= ripplestateBitHighNode
			default:
				return newErrUnknownField("RippleState", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				r.PreviousTxnID = val
				r.present |= ripplestateBitPreviousTxnID
			default:
				return newErrUnknownField("RippleState", typeCode, fieldCode)
			}
		case 6: // Amount
			val, err := sr.readAmountAny()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				r.Balance = val
				r.present |= ripplestateBitBalance
			case 6:
				r.LowLimit = val
				r.present |= ripplestateBitLowLimit
			case 7:
				r.HighLimit = val
				r.present |= ripplestateBitHighLimit
			default:
				return newErrUnknownField("RippleState", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("RippleState", typeCode, fieldCode)
		}
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (r *RippleState) emitAll(out map[string]any, skipDefault bool) {
	if r.present&ripplestateBitFlags != 0 && !(skipDefault && r.Flags == 0) {
		out["Flags"] = r.Flags
	}
	if r.present&ripplestateBitBalance != 0 {
		out["Balance"] = r.Balance
	}
	if r.present&ripplestateBitLowLimit != 0 {
		out["LowLimit"] = r.LowLimit
	}
	if r.present&ripplestateBitHighLimit != 0 {
		out["HighLimit"] = r.HighLimit
	}
	if r.present&ripplestateBitLowNode != 0 && !(skipDefault && isZeroHexString(r.LowNode)) {
		out["LowNode"] = r.LowNode
	}
	if r.present&ripplestateBitHighNode != 0 && !(skipDefault && isZeroHexString(r.HighNode)) {
		out["HighNode"] = r.HighNode
	}
	if r.present&ripplestateBitLowQualityIn != 0 && !(skipDefault && r.LowQualityIn == 0) {
		out["LowQualityIn"] = r.LowQualityIn
	}
	if r.present&ripplestateBitLowQualityOut != 0 && !(skipDefault && r.LowQualityOut == 0) {
		out["LowQualityOut"] = r.LowQualityOut
	}
	if r.present&ripplestateBitHighQualityIn != 0 && !(skipDefault && r.HighQualityIn == 0) {
		out["HighQualityIn"] = r.HighQualityIn
	}
	if r.present&ripplestateBitHighQualityOut != 0 && !(skipDefault && r.HighQualityOut == 0) {
		out["HighQualityOut"] = r.HighQualityOut
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (r *RippleState) EmitNewFields(out map[string]any) {
	r.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (r *RippleState) EmitFinalFields(out map[string]any) {
	r.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (r *RippleState) EmitPreviousFields(prev Entry, out map[string]any) {
	p, ok := prev.(*RippleState)
	if !ok || p == nil {
		return
	}
	emitIfChangedUint32(out, "Flags", p.Flags, r.Flags, p.present&ripplestateBitFlags, r.present&ripplestateBitFlags)
	emitIfChangedAmount(out, "Balance", p.Balance, r.Balance, p.present&ripplestateBitBalance, r.present&ripplestateBitBalance)
	emitIfChangedAmount(out, "LowLimit", p.LowLimit, r.LowLimit, p.present&ripplestateBitLowLimit, r.present&ripplestateBitLowLimit)
	emitIfChangedAmount(out, "HighLimit", p.HighLimit, r.HighLimit, p.present&ripplestateBitHighLimit, r.present&ripplestateBitHighLimit)
	emitIfChangedString(out, "LowNode", p.LowNode, r.LowNode, p.present&ripplestateBitLowNode, r.present&ripplestateBitLowNode)
	emitIfChangedString(out, "HighNode", p.HighNode, r.HighNode, p.present&ripplestateBitHighNode, r.present&ripplestateBitHighNode)
	emitIfChangedUint32(out, "LowQualityIn", p.LowQualityIn, r.LowQualityIn, p.present&ripplestateBitLowQualityIn, r.present&ripplestateBitLowQualityIn)
	emitIfChangedUint32(out, "LowQualityOut", p.LowQualityOut, r.LowQualityOut, p.present&ripplestateBitLowQualityOut, r.present&ripplestateBitLowQualityOut)
	emitIfChangedUint32(out, "HighQualityIn", p.HighQualityIn, r.HighQualityIn, p.present&ripplestateBitHighQualityIn, r.present&ripplestateBitHighQualityIn)
	emitIfChangedUint32(out, "HighQualityOut", p.HighQualityOut, r.HighQualityOut, p.present&ripplestateBitHighQualityOut, r.present&ripplestateBitHighQualityOut)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (r *RippleState) EmitChangeOrigFields(out map[string]any) {
	if r.present&ripplestateBitFlags != 0 {
		out["Flags"] = r.Flags
	}
	if r.present&ripplestateBitBalance != 0 {
		out["Balance"] = r.Balance
	}
	if r.present&ripplestateBitLowLimit != 0 {
		out["LowLimit"] = r.LowLimit
	}
	if r.present&ripplestateBitHighLimit != 0 {
		out["HighLimit"] = r.HighLimit
	}
	if r.present&ripplestateBitLowNode != 0 {
		out["LowNode"] = r.LowNode
	}
	if r.present&ripplestateBitHighNode != 0 {
		out["HighNode"] = r.HighNode
	}
	if r.present&ripplestateBitLowQualityIn != 0 {
		out["LowQualityIn"] = r.LowQualityIn
	}
	if r.present&ripplestateBitLowQualityOut != 0 {
		out["LowQualityOut"] = r.LowQualityOut
	}
	if r.present&ripplestateBitHighQualityIn != 0 {
		out["HighQualityIn"] = r.HighQualityIn
	}
	if r.present&ripplestateBitHighQualityOut != 0 {
		out["HighQualityOut"] = r.HighQualityOut
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (r *RippleState) EmitDeleteFinalFields(out map[string]any) {
	r.emitAll(out, false)
	if r.present&ripplestateBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = r.PreviousTxnID
	}
	if r.present&ripplestateBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = r.PreviousTxnLgrSeq
	}
}

func (r *RippleState) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	r.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (r *RippleState) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if r.present&ripplestateBitPreviousTxnID != 0 {
		id = r.PreviousTxnID
	}
	if r.present&ripplestateBitPreviousTxnLgrSeq != 0 {
		seq = r.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (r *RippleState) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "RippleState",
	}
	if r.present&ripplestateBitFlags != 0 {
		out["Flags"] = r.Flags
	}
	if r.present&ripplestateBitBalance != 0 {
		out["Balance"] = r.Balance
	}
	if r.present&ripplestateBitLowLimit != 0 {
		out["LowLimit"] = r.LowLimit
	}
	if r.present&ripplestateBitHighLimit != 0 {
		out["HighLimit"] = r.HighLimit
	}
	if r.present&ripplestateBitLowNode != 0 {
		out["LowNode"] = r.LowNode
	}
	if r.present&ripplestateBitHighNode != 0 {
		out["HighNode"] = r.HighNode
	}
	if r.present&ripplestateBitLowQualityIn != 0 {
		out["LowQualityIn"] = r.LowQualityIn
	}
	if r.present&ripplestateBitLowQualityOut != 0 {
		out["LowQualityOut"] = r.LowQualityOut
	}
	if r.present&ripplestateBitHighQualityIn != 0 {
		out["HighQualityIn"] = r.HighQualityIn
	}
	if r.present&ripplestateBitHighQualityOut != 0 {
		out["HighQualityOut"] = r.HighQualityOut
	}
	if r.present&ripplestateBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = r.PreviousTxnID
	}
	if r.present&ripplestateBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = r.PreviousTxnLgrSeq
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Round-trip
// invariant: Decode(data); Encode() == data for any byte sequence that
// Decode accepts.
func (r *RippleState) Encode() ([]byte, error) {
	return binarycodec.EncodeBytes(r.ToMap())
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (r *RippleState) Hash(index [32]byte) ([32]byte, error) {
	data, err := r.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode
	return common.Sha512Half(prefix[:], data, index[:]), nil
}
