// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

func init() {
	Register("Ticket", func() Entry { return new(Ticket) })
}

// Ticket is the typed metadata-hot-path representation of a
// Ticket ledger entry. The present bitset tracks which fields appear on
// the decoded blob so the emit methods only write entries that actually exist.
type Ticket struct {
	present           uint64
	Account           string // AccountID (base58)
	OwnerNode         string // UInt64 (lowercase hex, no leading zeros)
	TicketSequence    uint32
	Flags             uint32
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
}

const (
	ticketBitAccount uint64 = 1 << iota
	ticketBitOwnerNode
	ticketBitTicketSequence
	ticketBitFlags
	ticketBitPreviousTxnID
	ticketBitPreviousTxnLgrSeq
)

// Decode populates the struct from binary ledger-entry data via a streaming
// reader. Unknown / sMD_Never fields are skipped without allocation.
func (t *Ticket) Decode(data []byte) error {
	*t = Ticket{}
	sr := newStreamReader(data)
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				_ = val // LedgerEntryType is sMD_Never; discard
			default:
				return newErrUnknownField("Ticket", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				t.Flags = val
				t.present |= ticketBitFlags
			case 5:
				t.PreviousTxnLgrSeq = val
				t.present |= ticketBitPreviousTxnLgrSeq
			case 41:
				t.TicketSequence = val
				t.present |= ticketBitTicketSequence
			default:
				return newErrUnknownField("Ticket", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 4:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				t.OwnerNode = val
				t.present |= ticketBitOwnerNode
			default:
				return newErrUnknownField("Ticket", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				t.PreviousTxnID = val
				t.present |= ticketBitPreviousTxnID
			default:
				return newErrUnknownField("Ticket", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				t.Account = val
				t.present |= ticketBitAccount
			default:
				return newErrUnknownField("Ticket", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("Ticket", typeCode, fieldCode)
		}
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (t *Ticket) emitAll(out map[string]any, skipDefault bool) {
	if t.present&ticketBitAccount != 0 && !(skipDefault && t.Account == "") {
		out["Account"] = t.Account
	}
	if t.present&ticketBitOwnerNode != 0 && !(skipDefault && isZeroHexString(t.OwnerNode)) {
		out["OwnerNode"] = t.OwnerNode
	}
	if t.present&ticketBitTicketSequence != 0 && !(skipDefault && t.TicketSequence == 0) {
		out["TicketSequence"] = t.TicketSequence
	}
	if t.present&ticketBitFlags != 0 && !(skipDefault && t.Flags == 0) {
		out["Flags"] = t.Flags
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (t *Ticket) EmitNewFields(out map[string]any) {
	t.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (t *Ticket) EmitFinalFields(out map[string]any) {
	t.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig).
func (t *Ticket) EmitPreviousFields(prev Entry, out map[string]any) {
	p, ok := prev.(*Ticket)
	if !ok || p == nil {
		return
	}
	emitIfChangedString(out, "Account", p.Account, t.Account, p.present&ticketBitAccount, t.present&ticketBitAccount)
	emitIfChangedString(out, "OwnerNode", p.OwnerNode, t.OwnerNode, p.present&ticketBitOwnerNode, t.present&ticketBitOwnerNode)
	emitIfChangedUint32(out, "TicketSequence", p.TicketSequence, t.TicketSequence, p.present&ticketBitTicketSequence, t.present&ticketBitTicketSequence)
	emitIfChangedUint32(out, "Flags", p.Flags, t.Flags, p.present&ticketBitFlags, t.present&ticketBitFlags)
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (t *Ticket) EmitDeleteFinalFields(out map[string]any) {
	t.emitAll(out, false)
	if t.present&ticketBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = t.PreviousTxnID
	}
	if t.present&ticketBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = t.PreviousTxnLgrSeq
	}
}

func (t *Ticket) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	t.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (t *Ticket) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if t.present&ticketBitPreviousTxnID != 0 {
		id = t.PreviousTxnID
	}
	if t.present&ticketBitPreviousTxnLgrSeq != 0 {
		seq = t.PreviousTxnLgrSeq
	}
	return id, seq
}
