// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

import (
	"errors"
	"fmt"

	"github.com/LeJamon/go-xrpl/codec/binarycodec"
	"github.com/LeJamon/go-xrpl/crypto/sha512half"
	"github.com/LeJamon/go-xrpl/protocol"
)

func init() {
	Register("Vault", func() Entry { return new(Vault) })
}

// Vault is the typed representation of a Vault ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every canonical field declared in the spec — including those excluded from
// metadata (sMD_Never) — so decoding and re-encoding does not drop them.
type Vault struct {
	present           uint64
	decoded           bool
	dirty             bool
	Sequence          uint32
	OwnerNode         string // UInt64 (lowercase hex, no leading zeros)
	Owner             string // AccountID (base58)
	Account           string // AccountID (base58)
	Data              string // Blob (uppercase hex)
	Asset             any
	AssetsTotal       any
	AssetsAvailable   any
	AssetsMaximum     any
	LossUnrealized    any
	ShareMPTID        string
	WithdrawalPolicy  int
	Scale             int
	Flags             uint32
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
}

const (
	vaultBitSequence uint64 = 1 << iota
	vaultBitOwnerNode
	vaultBitOwner
	vaultBitAccount
	vaultBitData
	vaultBitAsset
	vaultBitAssetsTotal
	vaultBitAssetsAvailable
	vaultBitAssetsMaximum
	vaultBitLossUnrealized
	vaultBitShareMPTID
	vaultBitWithdrawalPolicy
	vaultBitScale
	vaultBitFlags
	vaultBitPreviousTxnID
	vaultBitPreviousTxnLgrSeq
)

// SetSequence assigns Sequence and updates its serialized presence.
func (v *Vault) SetSequence(value uint32) {
	v.Sequence = value
	v.dirty = true
	v.present |= vaultBitSequence
}

// SetOwnerNode assigns OwnerNode and updates its serialized presence.
func (v *Vault) SetOwnerNode(value string) {
	v.OwnerNode = value
	v.dirty = true
	v.present |= vaultBitOwnerNode
}

// SetOwner assigns Owner and updates its serialized presence.
func (v *Vault) SetOwner(value string) {
	v.Owner = value
	v.dirty = true
	v.present |= vaultBitOwner
}

// SetAccount assigns Account and updates its serialized presence.
func (v *Vault) SetAccount(value string) {
	v.Account = value
	v.dirty = true
	v.present |= vaultBitAccount
}

// SetData assigns Data and updates its serialized presence.
func (v *Vault) SetData(value string) {
	v.Data = value
	v.dirty = true
	v.present |= vaultBitData
}

// SetAsset assigns Asset and updates its serialized presence.
func (v *Vault) SetAsset(value any) {
	v.Asset = value
	v.dirty = true
	v.present |= vaultBitAsset
}

// SetAssetsTotal assigns AssetsTotal and updates its serialized presence.
func (v *Vault) SetAssetsTotal(value any) {
	v.AssetsTotal = value
	v.dirty = true
	if value == nil || (numberIsDefault(value)) {
		v.present &^= vaultBitAssetsTotal
		return
	}
	v.present |= vaultBitAssetsTotal
}

// SetAssetsAvailable assigns AssetsAvailable and updates its serialized presence.
func (v *Vault) SetAssetsAvailable(value any) {
	v.AssetsAvailable = value
	v.dirty = true
	if value == nil || (numberIsDefault(value)) {
		v.present &^= vaultBitAssetsAvailable
		return
	}
	v.present |= vaultBitAssetsAvailable
}

// SetAssetsMaximum assigns AssetsMaximum and updates its serialized presence.
func (v *Vault) SetAssetsMaximum(value any) {
	v.AssetsMaximum = value
	v.dirty = true
	if value == nil || (numberIsDefault(value)) {
		v.present &^= vaultBitAssetsMaximum
		return
	}
	v.present |= vaultBitAssetsMaximum
}

// SetLossUnrealized assigns LossUnrealized and updates its serialized presence.
func (v *Vault) SetLossUnrealized(value any) {
	v.LossUnrealized = value
	v.dirty = true
	if value == nil || (numberIsDefault(value)) {
		v.present &^= vaultBitLossUnrealized
		return
	}
	v.present |= vaultBitLossUnrealized
}

// SetShareMPTID assigns ShareMPTID and updates its serialized presence.
func (v *Vault) SetShareMPTID(value string) {
	v.ShareMPTID = value
	v.dirty = true
	v.present |= vaultBitShareMPTID
}

// SetWithdrawalPolicy assigns WithdrawalPolicy and updates its serialized presence.
func (v *Vault) SetWithdrawalPolicy(value uint8) {
	v.WithdrawalPolicy = int(value)
	v.dirty = true
	v.present |= vaultBitWithdrawalPolicy
}

// SetScale assigns Scale and updates its serialized presence.
func (v *Vault) SetScale(value uint8) {
	v.Scale = int(value)
	v.dirty = true
	if value == 0 {
		v.present &^= vaultBitScale
		return
	}
	v.present |= vaultBitScale
}

// SetFlags assigns Flags and updates its serialized presence.
func (v *Vault) SetFlags(value uint32) {
	v.Flags = value
	v.dirty = true
	v.present |= vaultBitFlags
}

// SetPreviousTxnID assigns PreviousTxnID and updates its serialized presence.
func (v *Vault) SetPreviousTxnID(value string) {
	v.PreviousTxnID = value
	v.dirty = true
	v.present |= vaultBitPreviousTxnID
}

// SetPreviousTxnLgrSeq assigns PreviousTxnLgrSeq and updates its serialized presence.
func (v *Vault) SetPreviousTxnLgrSeq(value uint32) {
	v.PreviousTxnLgrSeq = value
	v.dirty = true
	v.present |= vaultBitPreviousTxnLgrSeq
}

func (v *Vault) validateRequired() error {
	if v.decoded && !v.dirty {
		return nil
	}
	if v.present&vaultBitSequence == 0 {
		return errors.New("ledgerfields: Vault: required field Sequence is not set")
	}
	if v.present&vaultBitOwnerNode == 0 {
		return errors.New("ledgerfields: Vault: required field OwnerNode is not set")
	}
	if v.present&vaultBitOwner == 0 {
		return errors.New("ledgerfields: Vault: required field Owner is not set")
	}
	if v.present&vaultBitAccount == 0 {
		return errors.New("ledgerfields: Vault: required field Account is not set")
	}
	if v.present&vaultBitAsset == 0 {
		return errors.New("ledgerfields: Vault: required field Asset is not set")
	}
	if v.present&vaultBitShareMPTID == 0 {
		return errors.New("ledgerfields: Vault: required field ShareMPTID is not set")
	}
	if v.present&vaultBitWithdrawalPolicy == 0 {
		return errors.New("ledgerfields: Vault: required field WithdrawalPolicy is not set")
	}
	if v.present&vaultBitFlags == 0 {
		return errors.New("ledgerfields: Vault: required field Flags is not set")
	}
	return nil
}

func (v *Vault) validateDecoded() error {
	if v.present&vaultBitSequence == 0 {
		return errors.New("ledgerfields: Vault: required field Sequence is missing")
	}
	if v.present&vaultBitOwnerNode == 0 {
		return errors.New("ledgerfields: Vault: required field OwnerNode is missing")
	}
	if v.present&vaultBitOwner == 0 {
		return errors.New("ledgerfields: Vault: required field Owner is missing")
	}
	if v.present&vaultBitAccount == 0 {
		return errors.New("ledgerfields: Vault: required field Account is missing")
	}
	if v.present&vaultBitAsset == 0 {
		return errors.New("ledgerfields: Vault: required field Asset is missing")
	}
	if v.present&vaultBitAssetsTotal != 0 && numberIsDefault(v.AssetsTotal) {
		return errors.New("ledgerfields: Vault: default field AssetsTotal is explicitly set")
	}
	if v.present&vaultBitAssetsAvailable != 0 && numberIsDefault(v.AssetsAvailable) {
		return errors.New("ledgerfields: Vault: default field AssetsAvailable is explicitly set")
	}
	if v.present&vaultBitAssetsMaximum != 0 && numberIsDefault(v.AssetsMaximum) {
		return errors.New("ledgerfields: Vault: default field AssetsMaximum is explicitly set")
	}
	if v.present&vaultBitLossUnrealized != 0 && numberIsDefault(v.LossUnrealized) {
		return errors.New("ledgerfields: Vault: default field LossUnrealized is explicitly set")
	}
	if v.present&vaultBitShareMPTID == 0 {
		return errors.New("ledgerfields: Vault: required field ShareMPTID is missing")
	}
	if v.present&vaultBitWithdrawalPolicy == 0 {
		return errors.New("ledgerfields: Vault: required field WithdrawalPolicy is missing")
	}
	if v.present&vaultBitScale != 0 && v.Scale == 0 {
		return errors.New("ledgerfields: Vault: default field Scale is explicitly set")
	}
	if v.present&vaultBitFlags == 0 {
		return errors.New("ledgerfields: Vault: required field Flags is missing")
	}
	if v.present&vaultBitPreviousTxnID == 0 {
		return errors.New("ledgerfields: Vault: required field PreviousTxnID is missing")
	}
	if v.present&vaultBitPreviousTxnLgrSeq == 0 {
		return errors.New("ledgerfields: Vault: required field PreviousTxnLgrSeq is missing")
	}
	return nil
}

// Decode populates the struct from binary ledger-entry data via a streaming
// reader and enforces the current rippled ledger template.
func (v *Vault) Decode(data []byte) error {
	return v.decode(data, false)
}

func (v *Vault) decodeLegacy(data []byte) error {
	return v.decode(data, true)
}

func (v *Vault) decode(data []byte, legacy bool) error {
	*v = Vault{}
	sr := newStreamReader(data)
	seenFields := make(map[[2]int]struct{})
	sawLedgerEntryType := false
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		fieldID := [2]int{typeCode, fieldCode}
		if _, exists := seenFields[fieldID]; exists {
			return fmt.Errorf("ledgerfields: Vault: duplicate field type=%d field=%d", typeCode, fieldCode)
		}
		seenFields[fieldID] = struct{}{}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				if val != 132 {
					return fmt.Errorf("ledgerfields: Vault: LedgerEntryType is %d, want 132", val)
				}
				sawLedgerEntryType = true
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				v.Flags = val
				v.present |= vaultBitFlags
			case 4:
				v.Sequence = val
				v.present |= vaultBitSequence
			case 5:
				v.PreviousTxnLgrSeq = val
				v.present |= vaultBitPreviousTxnLgrSeq
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 4:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				v.OwnerNode = val
				v.present |= vaultBitOwnerNode
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				v.PreviousTxnID = val
				v.present |= vaultBitPreviousTxnID
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		case 7: // Blob
			val, err := sr.readBlobHex()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 27:
				v.Data = val
				v.present |= vaultBitData
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				v.Account = val
				v.present |= vaultBitAccount
			case 2:
				v.Owner = val
				v.present |= vaultBitOwner
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		case 9: // Number
			val, err := sr.readNumber()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				v.AssetsAvailable = val
				v.present |= vaultBitAssetsAvailable
			case 3:
				v.AssetsMaximum = val
				v.present |= vaultBitAssetsMaximum
			case 4:
				v.AssetsTotal = val
				v.present |= vaultBitAssetsTotal
			case 5:
				v.LossUnrealized = val
				v.present |= vaultBitLossUnrealized
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		case 16: // UInt8
			byteVal, err := sr.readUint8()
			if err != nil {
				return err
			}
			val := int(byteVal)
			switch fieldCode {
			case 4:
				v.Scale = val
				v.present |= vaultBitScale
			case 20:
				v.WithdrawalPolicy = val
				v.present |= vaultBitWithdrawalPolicy
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		case 21: // Hash192
			val, err := sr.readHash(24)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				v.ShareMPTID = val
				v.present |= vaultBitShareMPTID
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		case 24: // Issue
			val, err := sr.readIssue()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 3:
				v.Asset = val
				v.present |= vaultBitAsset
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("Vault", typeCode, fieldCode)
		}
	}
	if !sawLedgerEntryType {
		return errors.New("ledgerfields: Vault: missing LedgerEntryType")
	}
	v.decoded = true
	if !legacy {
		return v.validateDecoded()
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (v *Vault) emitAll(out map[string]any, skipDefault bool) {
	if v.present&vaultBitSequence != 0 && !(skipDefault && v.Sequence == 0) {
		out["Sequence"] = v.Sequence
	}
	if v.present&vaultBitOwnerNode != 0 && !(skipDefault && isZeroHexString(v.OwnerNode)) {
		out["OwnerNode"] = v.OwnerNode
	}
	if v.present&vaultBitOwner != 0 && !(skipDefault && v.Owner == "") {
		out["Owner"] = v.Owner
	}
	if v.present&vaultBitAccount != 0 && !(skipDefault && v.Account == "") {
		out["Account"] = v.Account
	}
	if v.present&vaultBitData != 0 && !(skipDefault && v.Data == "") {
		out["Data"] = v.Data
	}
	if v.present&vaultBitAsset != 0 && !(skipDefault && issueIsDefault(v.Asset)) {
		out["Asset"] = v.Asset
	}
	if v.present&vaultBitAssetsTotal != 0 && !(skipDefault && numberIsDefault(v.AssetsTotal)) {
		out["AssetsTotal"] = v.AssetsTotal
	}
	if v.present&vaultBitAssetsAvailable != 0 && !(skipDefault && numberIsDefault(v.AssetsAvailable)) {
		out["AssetsAvailable"] = v.AssetsAvailable
	}
	if v.present&vaultBitAssetsMaximum != 0 && !(skipDefault && numberIsDefault(v.AssetsMaximum)) {
		out["AssetsMaximum"] = v.AssetsMaximum
	}
	if v.present&vaultBitLossUnrealized != 0 && !(skipDefault && numberIsDefault(v.LossUnrealized)) {
		out["LossUnrealized"] = v.LossUnrealized
	}
	if v.present&vaultBitShareMPTID != 0 && !(skipDefault && isZeroHexString(v.ShareMPTID)) {
		out["ShareMPTID"] = v.ShareMPTID
	}
	if v.present&vaultBitWithdrawalPolicy != 0 && !(skipDefault && v.WithdrawalPolicy == 0) {
		out["WithdrawalPolicy"] = v.WithdrawalPolicy
	}
	if v.present&vaultBitScale != 0 && !(skipDefault && v.Scale == 0) {
		out["Scale"] = v.Scale
	}
	if v.present&vaultBitFlags != 0 && !(skipDefault && v.Flags == 0) {
		out["Flags"] = v.Flags
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (v *Vault) EmitNewFields(out map[string]any) {
	v.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (v *Vault) EmitFinalFields(out map[string]any) {
	v.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (v *Vault) EmitPreviousFields(prev Entry, out map[string]any) {
	prv, ok := prev.(*Vault)
	if !ok || prv == nil {
		return
	}
	emitIfChangedUint32(out, "Sequence", prv.Sequence, v.Sequence, prv.present&vaultBitSequence, v.present&vaultBitSequence)
	emitIfChangedString(out, "OwnerNode", prv.OwnerNode, v.OwnerNode, prv.present&vaultBitOwnerNode, v.present&vaultBitOwnerNode)
	emitIfChangedString(out, "Owner", prv.Owner, v.Owner, prv.present&vaultBitOwner, v.present&vaultBitOwner)
	emitIfChangedString(out, "Account", prv.Account, v.Account, prv.present&vaultBitAccount, v.present&vaultBitAccount)
	emitIfChangedString(out, "Data", prv.Data, v.Data, prv.present&vaultBitData, v.present&vaultBitData)
	emitIfChangedDeep(out, "Asset", prv.Asset, v.Asset, prv.present&vaultBitAsset, v.present&vaultBitAsset)
	emitIfChangedDeep(out, "AssetsTotal", prv.AssetsTotal, v.AssetsTotal, prv.present&vaultBitAssetsTotal, v.present&vaultBitAssetsTotal)
	emitIfChangedDeep(out, "AssetsAvailable", prv.AssetsAvailable, v.AssetsAvailable, prv.present&vaultBitAssetsAvailable, v.present&vaultBitAssetsAvailable)
	emitIfChangedDeep(out, "AssetsMaximum", prv.AssetsMaximum, v.AssetsMaximum, prv.present&vaultBitAssetsMaximum, v.present&vaultBitAssetsMaximum)
	emitIfChangedDeep(out, "LossUnrealized", prv.LossUnrealized, v.LossUnrealized, prv.present&vaultBitLossUnrealized, v.present&vaultBitLossUnrealized)
	emitIfChangedString(out, "ShareMPTID", prv.ShareMPTID, v.ShareMPTID, prv.present&vaultBitShareMPTID, v.present&vaultBitShareMPTID)
	emitIfChangedInt(out, "WithdrawalPolicy", prv.WithdrawalPolicy, v.WithdrawalPolicy, prv.present&vaultBitWithdrawalPolicy, v.present&vaultBitWithdrawalPolicy)
	emitIfChangedInt(out, "Scale", prv.Scale, v.Scale, prv.present&vaultBitScale, v.present&vaultBitScale)
	emitIfChangedUint32(out, "Flags", prv.Flags, v.Flags, prv.present&vaultBitFlags, v.present&vaultBitFlags)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (v *Vault) EmitChangeOrigFields(out map[string]any) {
	if v.present&vaultBitSequence != 0 {
		out["Sequence"] = v.Sequence
	}
	if v.present&vaultBitOwnerNode != 0 {
		out["OwnerNode"] = v.OwnerNode
	}
	if v.present&vaultBitOwner != 0 {
		out["Owner"] = v.Owner
	}
	if v.present&vaultBitAccount != 0 {
		out["Account"] = v.Account
	}
	if v.present&vaultBitData != 0 {
		out["Data"] = v.Data
	}
	if v.present&vaultBitAsset != 0 {
		out["Asset"] = v.Asset
	}
	if v.present&vaultBitAssetsTotal != 0 {
		out["AssetsTotal"] = v.AssetsTotal
	}
	if v.present&vaultBitAssetsAvailable != 0 {
		out["AssetsAvailable"] = v.AssetsAvailable
	}
	if v.present&vaultBitAssetsMaximum != 0 {
		out["AssetsMaximum"] = v.AssetsMaximum
	}
	if v.present&vaultBitLossUnrealized != 0 {
		out["LossUnrealized"] = v.LossUnrealized
	}
	if v.present&vaultBitShareMPTID != 0 {
		out["ShareMPTID"] = v.ShareMPTID
	}
	if v.present&vaultBitWithdrawalPolicy != 0 {
		out["WithdrawalPolicy"] = v.WithdrawalPolicy
	}
	if v.present&vaultBitScale != 0 {
		out["Scale"] = v.Scale
	}
	if v.present&vaultBitFlags != 0 {
		out["Flags"] = v.Flags
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (v *Vault) EmitDeleteFinalFields(out map[string]any) {
	v.emitAll(out, false)
	if v.present&vaultBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = v.PreviousTxnID
	}
	if v.present&vaultBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = v.PreviousTxnLgrSeq
	}
}

func (v *Vault) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	v.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (v *Vault) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if v.present&vaultBitPreviousTxnID != 0 {
		id = v.PreviousTxnID
	}
	if v.present&vaultBitPreviousTxnLgrSeq != 0 {
		seq = v.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (v *Vault) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "Vault",
	}
	if v.present&vaultBitSequence != 0 {
		out["Sequence"] = v.Sequence
	}
	if v.present&vaultBitOwnerNode != 0 {
		out["OwnerNode"] = v.OwnerNode
	}
	if v.present&vaultBitOwner != 0 {
		out["Owner"] = v.Owner
	}
	if v.present&vaultBitAccount != 0 {
		out["Account"] = v.Account
	}
	if v.present&vaultBitData != 0 {
		out["Data"] = v.Data
	}
	if v.present&vaultBitAsset != 0 {
		out["Asset"] = v.Asset
	}
	if v.present&vaultBitAssetsTotal != 0 {
		out["AssetsTotal"] = v.AssetsTotal
	}
	if v.present&vaultBitAssetsAvailable != 0 {
		out["AssetsAvailable"] = v.AssetsAvailable
	}
	if v.present&vaultBitAssetsMaximum != 0 {
		out["AssetsMaximum"] = v.AssetsMaximum
	}
	if v.present&vaultBitLossUnrealized != 0 {
		out["LossUnrealized"] = v.LossUnrealized
	}
	if v.present&vaultBitShareMPTID != 0 {
		out["ShareMPTID"] = v.ShareMPTID
	}
	if v.present&vaultBitWithdrawalPolicy != 0 {
		out["WithdrawalPolicy"] = v.WithdrawalPolicy
	}
	if v.present&vaultBitScale != 0 {
		out["Scale"] = v.Scale
	}
	if v.present&vaultBitFlags != 0 {
		out["Flags"] = v.Flags
	}
	if v.present&vaultBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = v.PreviousTxnID
	}
	if v.present&vaultBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = v.PreviousTxnLgrSeq
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Legacy decode
// aliases and non-canonical input ordering are emitted in canonical form.
func (v *Vault) Encode() ([]byte, error) {
	if err := v.validateRequired(); err != nil {
		return nil, err
	}
	out := v.ToMap()
	if v.present&vaultBitPreviousTxnID == 0 {
		out["PreviousTxnID"] = "0000000000000000000000000000000000000000000000000000000000000000"
	}
	if v.present&vaultBitPreviousTxnLgrSeq == 0 {
		out["PreviousTxnLgrSeq"] = uint32(0)
	}
	return binarycodec.EncodeBytes(out)
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (v *Vault) Hash(index [32]byte) ([32]byte, error) {
	data, err := v.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode()
	return sha512half.Sum(prefix[:], data, index[:]), nil
}
