// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

func init() {
	Register("Vault", func() Entry { return new(Vault) })
}

// Vault is the typed metadata-hot-path representation of a
// Vault ledger entry. The present bitset tracks which fields appear on
// the decoded blob so the emit methods only write entries that actually exist.
type Vault struct {
	present           uint64
	Sequence          uint32
	OwnerNode         string // UInt64 (uppercase hex)
	Owner             string // AccountID (base58)
	Account           string // AccountID (base58)
	Data              string // Blob (uppercase hex)
	Asset             any
	AssetsTotal       any
	AssetsAvailable   any
	AssetsMaximum     any
	LossUnrealized    any
	ShareMPTID        string
	WithdrawalPolicy  int
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
}

const (
	vaultBitSequence uint64 = 1 << iota
	vaultBitOwnerNode
	vaultBitOwner
	vaultBitAccount
	vaultBitData
	vaultBitAsset
	vaultBitAssetsTotal
	vaultBitAssetsAvailable
	vaultBitAssetsMaximum
	vaultBitLossUnrealized
	vaultBitShareMPTID
	vaultBitWithdrawalPolicy
	vaultBitPreviousTxnID
	vaultBitPreviousTxnLgrSeq
)

// Decode populates the struct from binary ledger-entry data via a streaming
// reader. Unknown / sMD_Never fields are skipped without allocation.
func (v *Vault) Decode(data []byte) error {
	*v = Vault{}
	sr := newStreamReader(data)
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				_ = val // LedgerEntryType is sMD_Never; discard
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 4:
				v.Sequence = val
				v.present |= vaultBitSequence
			case 5:
				v.PreviousTxnLgrSeq = val
				v.present |= vaultBitPreviousTxnLgrSeq
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		case 3: // UInt64
			val, err := sr.readUint64Hex()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 4:
				v.OwnerNode = val
				v.present |= vaultBitOwnerNode
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				v.PreviousTxnID = val
				v.present |= vaultBitPreviousTxnID
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		case 7: // Blob
			val, err := sr.readBlobHex()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 27:
				v.Data = val
				v.present |= vaultBitData
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				v.Account = val
				v.present |= vaultBitAccount
			case 2:
				v.Owner = val
				v.present |= vaultBitOwner
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		case 9: // Number
			val, err := sr.readNumber()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				v.AssetsAvailable = val
				v.present |= vaultBitAssetsAvailable
			case 3:
				v.AssetsMaximum = val
				v.present |= vaultBitAssetsMaximum
			case 4:
				v.AssetsTotal = val
				v.present |= vaultBitAssetsTotal
			case 5:
				v.LossUnrealized = val
				v.present |= vaultBitLossUnrealized
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		case 16: // UInt8
			byteVal, err := sr.readUint8()
			if err != nil {
				return err
			}
			val := int(byteVal)
			switch fieldCode {
			case 20:
				v.WithdrawalPolicy = val
				v.present |= vaultBitWithdrawalPolicy
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		case 21: // Hash192
			val, err := sr.readHash(24)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				v.ShareMPTID = val
				v.present |= vaultBitShareMPTID
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		case 24: // Issue
			val, err := sr.readIssue()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 3:
				v.Asset = val
				v.present |= vaultBitAsset
			default:
				return newErrUnknownField("Vault", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("Vault", typeCode, fieldCode)
		}
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (v *Vault) emitAll(out map[string]any, skipDefault bool) {
	if v.present&vaultBitSequence != 0 && !(skipDefault && v.Sequence == 0) {
		out["Sequence"] = v.Sequence
	}
	if v.present&vaultBitOwnerNode != 0 && !(skipDefault && isZeroHexString(v.OwnerNode)) {
		out["OwnerNode"] = v.OwnerNode
	}
	if v.present&vaultBitOwner != 0 && !(skipDefault && v.Owner == "") {
		out["Owner"] = v.Owner
	}
	if v.present&vaultBitAccount != 0 && !(skipDefault && v.Account == "") {
		out["Account"] = v.Account
	}
	if v.present&vaultBitData != 0 && !(skipDefault && v.Data == "") {
		out["Data"] = v.Data
	}
	if v.present&vaultBitAsset != 0 {
		out["Asset"] = v.Asset
	}
	if v.present&vaultBitAssetsTotal != 0 {
		out["AssetsTotal"] = v.AssetsTotal
	}
	if v.present&vaultBitAssetsAvailable != 0 {
		out["AssetsAvailable"] = v.AssetsAvailable
	}
	if v.present&vaultBitAssetsMaximum != 0 {
		out["AssetsMaximum"] = v.AssetsMaximum
	}
	if v.present&vaultBitLossUnrealized != 0 {
		out["LossUnrealized"] = v.LossUnrealized
	}
	if v.present&vaultBitShareMPTID != 0 && !(skipDefault && isZeroHexString(v.ShareMPTID)) {
		out["ShareMPTID"] = v.ShareMPTID
	}
	if v.present&vaultBitWithdrawalPolicy != 0 && !(skipDefault && v.WithdrawalPolicy == 0) {
		out["WithdrawalPolicy"] = v.WithdrawalPolicy
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (v *Vault) EmitNewFields(out map[string]any) {
	v.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (v *Vault) EmitFinalFields(out map[string]any) {
	v.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig).
func (v *Vault) EmitPreviousFields(prev Entry, out map[string]any) {
	p, ok := prev.(*Vault)
	if !ok || p == nil {
		return
	}
	emitIfChangedUint32(out, "Sequence", p.Sequence, v.Sequence, p.present&vaultBitSequence, v.present&vaultBitSequence)
	emitIfChangedString(out, "OwnerNode", p.OwnerNode, v.OwnerNode, p.present&vaultBitOwnerNode, v.present&vaultBitOwnerNode)
	emitIfChangedString(out, "Owner", p.Owner, v.Owner, p.present&vaultBitOwner, v.present&vaultBitOwner)
	emitIfChangedString(out, "Account", p.Account, v.Account, p.present&vaultBitAccount, v.present&vaultBitAccount)
	emitIfChangedString(out, "Data", p.Data, v.Data, p.present&vaultBitData, v.present&vaultBitData)
	emitIfChangedDeep(out, "Asset", p.Asset, v.Asset, p.present&vaultBitAsset, v.present&vaultBitAsset)
	emitIfChangedDeep(out, "AssetsTotal", p.AssetsTotal, v.AssetsTotal, p.present&vaultBitAssetsTotal, v.present&vaultBitAssetsTotal)
	emitIfChangedDeep(out, "AssetsAvailable", p.AssetsAvailable, v.AssetsAvailable, p.present&vaultBitAssetsAvailable, v.present&vaultBitAssetsAvailable)
	emitIfChangedDeep(out, "AssetsMaximum", p.AssetsMaximum, v.AssetsMaximum, p.present&vaultBitAssetsMaximum, v.present&vaultBitAssetsMaximum)
	emitIfChangedDeep(out, "LossUnrealized", p.LossUnrealized, v.LossUnrealized, p.present&vaultBitLossUnrealized, v.present&vaultBitLossUnrealized)
	emitIfChangedString(out, "ShareMPTID", p.ShareMPTID, v.ShareMPTID, p.present&vaultBitShareMPTID, v.present&vaultBitShareMPTID)
	emitIfChangedInt(out, "WithdrawalPolicy", p.WithdrawalPolicy, v.WithdrawalPolicy, p.present&vaultBitWithdrawalPolicy, v.present&vaultBitWithdrawalPolicy)
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (v *Vault) EmitDeleteFinalFields(out map[string]any) {
	v.emitAll(out, false)
	if v.present&vaultBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = v.PreviousTxnID
	}
	if v.present&vaultBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = v.PreviousTxnLgrSeq
	}
}

func (v *Vault) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	v.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (v *Vault) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if v.present&vaultBitPreviousTxnID != 0 {
		id = v.PreviousTxnID
	}
	if v.present&vaultBitPreviousTxnLgrSeq != 0 {
		seq = v.PreviousTxnLgrSeq
	}
	return id, seq
}
