// Code generated by ledgerfieldsgen; DO NOT EDIT.
//
// Source: internal/tx/ledgerfields/spec/spec.go
// Regenerate: go generate ./internal/tx/ledgerfields/...

package ledgerfields

import (
	"github.com/LeJamon/go-xrpl/codec/binarycodec"
	"github.com/LeJamon/go-xrpl/crypto/common"
	"github.com/LeJamon/go-xrpl/protocol"
)

func init() {
	Register("XChainOwnedClaimID", func() Entry { return new(XChainOwnedClaimID) })
}

// XChainOwnedClaimID is the typed representation of a XChainOwnedClaimID ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every on-wire field — including those excluded from metadata
// (sMD_Never) — so Decode → Encode is byte-identical.
type XChainOwnedClaimID struct {
	present                 uint64
	Account                 string // AccountID (base58)
	XChainBridge            any
	XChainClaimID           string // UInt64 (lowercase hex, no leading zeros)
	OtherChainSource        string // AccountID (base58)
	XChainClaimAttestations []any
	SignatureReward         any    // Amount (XRP string | IOU map)
	OwnerNode               string // UInt64 (lowercase hex, no leading zeros)
	Flags                   uint32
	PreviousTxnID           string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq       uint32
}

const (
	xchainownedclaimidBitAccount uint64 = 1 << iota
	xchainownedclaimidBitXChainBridge
	xchainownedclaimidBitXChainClaimID
	xchainownedclaimidBitOtherChainSource
	xchainownedclaimidBitXChainClaimAttestations
	xchainownedclaimidBitSignatureReward
	xchainownedclaimidBitOwnerNode
	xchainownedclaimidBitFlags
	xchainownedclaimidBitPreviousTxnID
	xchainownedclaimidBitPreviousTxnLgrSeq
)

// Decode populates the struct from binary ledger-entry data via a streaming
// reader. Unknown / sMD_Never fields are skipped without allocation.
func (x *XChainOwnedClaimID) Decode(data []byte) error {
	*x = XChainOwnedClaimID{}
	sr := newStreamReader(data)
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				_ = val // synthetic LedgerEntryType; discard
			default:
				return newErrUnknownField("XChainOwnedClaimID", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				x.Flags = val
				x.present |= xchainownedclaimidBitFlags
			case 5:
				x.PreviousTxnLgrSeq = val
				x.present |= xchainownedclaimidBitPreviousTxnLgrSeq
			default:
				return newErrUnknownField("XChainOwnedClaimID", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 4:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				x.OwnerNode = val
				x.present |= xchainownedclaimidBitOwnerNode
			case 20:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				x.XChainClaimID = val
				x.present |= xchainownedclaimidBitXChainClaimID
			default:
				return newErrUnknownField("XChainOwnedClaimID", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				x.PreviousTxnID = val
				x.present |= xchainownedclaimidBitPreviousTxnID
			default:
				return newErrUnknownField("XChainOwnedClaimID", typeCode, fieldCode)
			}
		case 6: // Amount
			val, err := sr.readAmountAny()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 29:
				x.SignatureReward = val
				x.present |= xchainownedclaimidBitSignatureReward
			default:
				return newErrUnknownField("XChainOwnedClaimID", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				x.Account = val
				x.present |= xchainownedclaimidBitAccount
			case 18:
				x.OtherChainSource = val
				x.present |= xchainownedclaimidBitOtherChainSource
			default:
				return newErrUnknownField("XChainOwnedClaimID", typeCode, fieldCode)
			}
		case 15: // STArray
			val, err := sr.readSTArray()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 21:
				x.XChainClaimAttestations = val
				x.present |= xchainownedclaimidBitXChainClaimAttestations
			default:
				return newErrUnknownField("XChainOwnedClaimID", typeCode, fieldCode)
			}
		case 25: // XChainBridge
			val, err := sr.readXChainBridge()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				x.XChainBridge = val
				x.present |= xchainownedclaimidBitXChainBridge
			default:
				return newErrUnknownField("XChainOwnedClaimID", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("XChainOwnedClaimID", typeCode, fieldCode)
		}
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (x *XChainOwnedClaimID) emitAll(out map[string]any, skipDefault bool) {
	if x.present&xchainownedclaimidBitAccount != 0 && !(skipDefault && x.Account == "") {
		out["Account"] = x.Account
	}
	if x.present&xchainownedclaimidBitXChainBridge != 0 && !(skipDefault && xchainBridgeIsDefault(x.XChainBridge)) {
		out["XChainBridge"] = x.XChainBridge
	}
	if x.present&xchainownedclaimidBitXChainClaimID != 0 && !(skipDefault && isZeroHexString(x.XChainClaimID)) {
		out["XChainClaimID"] = x.XChainClaimID
	}
	if x.present&xchainownedclaimidBitOtherChainSource != 0 && !(skipDefault && x.OtherChainSource == "") {
		out["OtherChainSource"] = x.OtherChainSource
	}
	if x.present&xchainownedclaimidBitXChainClaimAttestations != 0 && !(skipDefault && len(x.XChainClaimAttestations) == 0) {
		out["XChainClaimAttestations"] = x.XChainClaimAttestations
	}
	if x.present&xchainownedclaimidBitSignatureReward != 0 && !(skipDefault && amountIsDefault(x.SignatureReward)) {
		out["SignatureReward"] = x.SignatureReward
	}
	if x.present&xchainownedclaimidBitOwnerNode != 0 && !(skipDefault && isZeroHexString(x.OwnerNode)) {
		out["OwnerNode"] = x.OwnerNode
	}
	if x.present&xchainownedclaimidBitFlags != 0 && !(skipDefault && x.Flags == 0) {
		out["Flags"] = x.Flags
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (x *XChainOwnedClaimID) EmitNewFields(out map[string]any) {
	x.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (x *XChainOwnedClaimID) EmitFinalFields(out map[string]any) {
	x.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (x *XChainOwnedClaimID) EmitPreviousFields(prev Entry, out map[string]any) {
	prv, ok := prev.(*XChainOwnedClaimID)
	if !ok || prv == nil {
		return
	}
	emitIfChangedString(out, "Account", prv.Account, x.Account, prv.present&xchainownedclaimidBitAccount, x.present&xchainownedclaimidBitAccount)
	emitIfChangedDeep(out, "XChainBridge", prv.XChainBridge, x.XChainBridge, prv.present&xchainownedclaimidBitXChainBridge, x.present&xchainownedclaimidBitXChainBridge)
	emitIfChangedString(out, "XChainClaimID", prv.XChainClaimID, x.XChainClaimID, prv.present&xchainownedclaimidBitXChainClaimID, x.present&xchainownedclaimidBitXChainClaimID)
	emitIfChangedString(out, "OtherChainSource", prv.OtherChainSource, x.OtherChainSource, prv.present&xchainownedclaimidBitOtherChainSource, x.present&xchainownedclaimidBitOtherChainSource)
	emitIfChangedDeep(out, "XChainClaimAttestations", prv.XChainClaimAttestations, x.XChainClaimAttestations, prv.present&xchainownedclaimidBitXChainClaimAttestations, x.present&xchainownedclaimidBitXChainClaimAttestations)
	emitIfChangedAmount(out, "SignatureReward", prv.SignatureReward, x.SignatureReward, prv.present&xchainownedclaimidBitSignatureReward, x.present&xchainownedclaimidBitSignatureReward)
	emitIfChangedString(out, "OwnerNode", prv.OwnerNode, x.OwnerNode, prv.present&xchainownedclaimidBitOwnerNode, x.present&xchainownedclaimidBitOwnerNode)
	emitIfChangedUint32(out, "Flags", prv.Flags, x.Flags, prv.present&xchainownedclaimidBitFlags, x.present&xchainownedclaimidBitFlags)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (x *XChainOwnedClaimID) EmitChangeOrigFields(out map[string]any) {
	if x.present&xchainownedclaimidBitAccount != 0 {
		out["Account"] = x.Account
	}
	if x.present&xchainownedclaimidBitXChainBridge != 0 {
		out["XChainBridge"] = x.XChainBridge
	}
	if x.present&xchainownedclaimidBitXChainClaimID != 0 {
		out["XChainClaimID"] = x.XChainClaimID
	}
	if x.present&xchainownedclaimidBitOtherChainSource != 0 {
		out["OtherChainSource"] = x.OtherChainSource
	}
	if x.present&xchainownedclaimidBitXChainClaimAttestations != 0 {
		out["XChainClaimAttestations"] = x.XChainClaimAttestations
	}
	if x.present&xchainownedclaimidBitSignatureReward != 0 {
		out["SignatureReward"] = x.SignatureReward
	}
	if x.present&xchainownedclaimidBitOwnerNode != 0 {
		out["OwnerNode"] = x.OwnerNode
	}
	if x.present&xchainownedclaimidBitFlags != 0 {
		out["Flags"] = x.Flags
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (x *XChainOwnedClaimID) EmitDeleteFinalFields(out map[string]any) {
	x.emitAll(out, false)
	if x.present&xchainownedclaimidBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = x.PreviousTxnID
	}
	if x.present&xchainownedclaimidBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = x.PreviousTxnLgrSeq
	}
}

func (x *XChainOwnedClaimID) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	x.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (x *XChainOwnedClaimID) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if x.present&xchainownedclaimidBitPreviousTxnID != 0 {
		id = x.PreviousTxnID
	}
	if x.present&xchainownedclaimidBitPreviousTxnLgrSeq != 0 {
		seq = x.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (x *XChainOwnedClaimID) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "XChainOwnedClaimID",
	}
	if x.present&xchainownedclaimidBitAccount != 0 {
		out["Account"] = x.Account
	}
	if x.present&xchainownedclaimidBitXChainBridge != 0 {
		out["XChainBridge"] = x.XChainBridge
	}
	if x.present&xchainownedclaimidBitXChainClaimID != 0 {
		out["XChainClaimID"] = x.XChainClaimID
	}
	if x.present&xchainownedclaimidBitOtherChainSource != 0 {
		out["OtherChainSource"] = x.OtherChainSource
	}
	if x.present&xchainownedclaimidBitXChainClaimAttestations != 0 {
		out["XChainClaimAttestations"] = x.XChainClaimAttestations
	}
	if x.present&xchainownedclaimidBitSignatureReward != 0 {
		out["SignatureReward"] = x.SignatureReward
	}
	if x.present&xchainownedclaimidBitOwnerNode != 0 {
		out["OwnerNode"] = x.OwnerNode
	}
	if x.present&xchainownedclaimidBitFlags != 0 {
		out["Flags"] = x.Flags
	}
	if x.present&xchainownedclaimidBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = x.PreviousTxnID
	}
	if x.present&xchainownedclaimidBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = x.PreviousTxnLgrSeq
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Round-trip
// invariant: Decode(data); Encode() == data for any byte sequence that
// Decode accepts.
func (x *XChainOwnedClaimID) Encode() ([]byte, error) {
	return binarycodec.EncodeBytes(x.ToMap())
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (x *XChainOwnedClaimID) Hash(index [32]byte) ([32]byte, error) {
	data, err := x.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode
	return common.Sha512Half(prefix[:], data, index[:]), nil
}
