package handlers

import "github.com/LeJamon/goXRPLd/internal/rpc/types"

// Compile-time interface checks for every RPC method handler. Each
// handler embeds BaseHandler or AdminHandler for the boilerplate
// RequiredRole / SupportedApiVersions / RequiredCondition methods, but
// provides its own Handle() — that's the part that drifts. Listing
// every type here makes drift fail at build time rather than at
// dispatch time.
var (
	_ types.MethodHandler = (*AccountChannelsMethod)(nil)
	_ types.MethodHandler = (*AccountCurrenciesMethod)(nil)
	_ types.MethodHandler = (*AccountInfoMethod)(nil)
	_ types.MethodHandler = (*AccountLinesMethod)(nil)
	_ types.MethodHandler = (*AccountNftsMethod)(nil)
	_ types.MethodHandler = (*AccountObjectsMethod)(nil)
	_ types.MethodHandler = (*AccountOffersMethod)(nil)
	_ types.MethodHandler = (*AccountTxMethod)(nil)
	_ types.MethodHandler = (*AMMInfoMethod)(nil)
	_ types.MethodHandler = (*BlackListMethod)(nil)
	_ types.MethodHandler = (*BookChangesMethod)(nil)
	_ types.MethodHandler = (*BookOffersMethod)(nil)
	_ types.MethodHandler = (*CanDeleteMethod)(nil)
	_ types.MethodHandler = (*ChannelAuthorizeMethod)(nil)
	_ types.MethodHandler = (*ChannelVerifyMethod)(nil)
	_ types.MethodHandler = (*ConnectMethod)(nil)
	_ types.MethodHandler = (*ConsensusInfoMethod)(nil)
	_ types.MethodHandler = (*CrawlShardsMethod)(nil)
	_ types.MethodHandler = (*DepositAuthorizedMethod)(nil)
	_ types.MethodHandler = (*DownloadShardMethod)(nil)
	_ types.MethodHandler = (*FeatureMethod)(nil)
	_ types.MethodHandler = (*FeeMethod)(nil)
	_ types.MethodHandler = (*FetchInfoMethod)(nil)
	_ types.MethodHandler = (*GatewayBalancesMethod)(nil)
	_ types.MethodHandler = (*GetAggregatePriceMethod)(nil)
	_ types.MethodHandler = (*GetCountsMethod)(nil)
	_ types.MethodHandler = (*JsonMethod)(nil)
	_ types.MethodHandler = (*LedgerAcceptMethod)(nil)
	_ types.MethodHandler = (*LedgerCleanerMethod)(nil)
	_ types.MethodHandler = (*LedgerClosedMethod)(nil)
	_ types.MethodHandler = (*LedgerCurrentMethod)(nil)
	_ types.MethodHandler = (*LedgerDataMethod)(nil)
	_ types.MethodHandler = (*LedgerDiffMethod)(nil)
	_ types.MethodHandler = (*LedgerEntryMethod)(nil)
	_ types.MethodHandler = (*LedgerHeaderMethod)(nil)
	_ types.MethodHandler = (*LedgerIndexMethod)(nil)
	_ types.MethodHandler = (*LedgerMethod)(nil)
	_ types.MethodHandler = (*LedgerRangeMethod)(nil)
	_ types.MethodHandler = (*LedgerRequestMethod)(nil)
	_ types.MethodHandler = (*LogLevelMethod)(nil)
	_ types.MethodHandler = (*LogRotateMethod)(nil)
	_ types.MethodHandler = (*ManifestMethod)(nil)
	_ types.MethodHandler = (*NftBuyOffersMethod)(nil)
	_ types.MethodHandler = (*NftSellOffersMethod)(nil)
	_ types.MethodHandler = (*NoRippleCheckMethod)(nil)
	_ types.MethodHandler = (*OwnerInfoMethod)(nil)
	_ types.MethodHandler = (*PathFindMethod)(nil)
	_ types.MethodHandler = (*PeerReservationsAddMethod)(nil)
	_ types.MethodHandler = (*PeerReservationsDelMethod)(nil)
	_ types.MethodHandler = (*PeerReservationsListMethod)(nil)
	_ types.MethodHandler = (*PeersMethod)(nil)
	_ types.MethodHandler = (*PingMethod)(nil)
	_ types.MethodHandler = (*PrintMethod)(nil)
	_ types.MethodHandler = (*RandomMethod)(nil)
	_ types.MethodHandler = (*RipplePathFindMethod)(nil)
	_ types.MethodHandler = (*ServerDefinitionsMethod)(nil)
	_ types.MethodHandler = (*ServerInfoMethod)(nil)
	_ types.MethodHandler = (*ServerStateMethod)(nil)
	_ types.MethodHandler = (*SignForMethod)(nil)
	_ types.MethodHandler = (*SignMethod)(nil)
	_ types.MethodHandler = (*SimulateMethod)(nil)
	_ types.MethodHandler = (*StopMethod)(nil)
	_ types.MethodHandler = (*SubmitMethod)(nil)
	_ types.MethodHandler = (*SubmitMultisignedMethod)(nil)
	_ types.MethodHandler = (*SubscribeMethod)(nil)
	_ types.MethodHandler = (*TransactionEntryMethod)(nil)
	_ types.MethodHandler = (*TxHistoryMethod)(nil)
	_ types.MethodHandler = (*TxMethod)(nil)
	_ types.MethodHandler = (*TxReduceRelayMethod)(nil)
	_ types.MethodHandler = (*UnlListMethod)(nil)
	_ types.MethodHandler = (*UnsubscribeMethod)(nil)
	_ types.MethodHandler = (*ValidationCreateMethod)(nil)
	_ types.MethodHandler = (*ValidatorInfoMethod)(nil)
	_ types.MethodHandler = (*ValidatorListSitesMethod)(nil)
	_ types.MethodHandler = (*ValidatorsMethod)(nil)
	_ types.MethodHandler = (*VaultInfoMethod)(nil)
	_ types.MethodHandler = (*VersionMethod)(nil)
	_ types.MethodHandler = (*WalletProposeMethod)(nil)
)
