package schema

// FormatField is one entry in a ledger-entry SOTemplate for the
// server_definitions LEDGER_ENTRY_FORMATS section. Style is the rippled
// SOEStyle int (0=required, 1=optional, 2=default).
type FormatField struct {
	Name  string
	Style int
}

var commonFormatFields = []FormatField{
	{"LedgerIndex", 1},
	{"LedgerEntryType", 0},
	{"Flags", 0},
	{"Sponsor", 1},
}

// CommonFields returns the fields shared by all ledger-entry formats.
func CommonFields() []FormatField {
	return append([]FormatField(nil), commonFormatFields...)
}

// formats maps each ledger-entry type NAME (as in definitions
// LedgerEntryTypes, e.g. "AccountRoot","DirectoryNode") to its UNIQUE fields
// (common fields excluded), in ledger_entries.macro order.
// Transcribed from rippled 3.2.0 ledger_entries.macro.
var formats = map[string][]FormatField{
	"NFTokenOffer": {
		{"Owner", 0},
		{"NFTokenID", 0},
		{"Amount", 0},
		{"OwnerNode", 0},
		{"NFTokenOfferNode", 0},
		{"Destination", 1},
		{"Expiration", 1},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
	},
	"Check": {
		{"Account", 0},
		{"Destination", 0},
		{"SendMax", 0},
		{"Sequence", 0},
		{"OwnerNode", 0},
		{"DestinationNode", 0},
		{"Expiration", 1},
		{"InvoiceID", 1},
		{"SourceTag", 1},
		{"DestinationTag", 1},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
	},
	"DID": {
		{"Account", 0},
		{"DIDDocument", 1},
		{"URI", 1},
		{"Data", 1},
		{"OwnerNode", 0},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
	},
	"NegativeUNL": {
		{"DisabledValidators", 1},
		{"ValidatorToDisable", 1},
		{"ValidatorToReEnable", 1},
		{"PreviousTxnID", 1},
		{"PreviousTxnLgrSeq", 1},
	},
	"NFTokenPage": {
		{"PreviousPageMin", 1},
		{"NextPageMin", 1},
		{"NFTokens", 0},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
	},
	"SignerList": {
		{"Owner", 1},
		{"OwnerNode", 0},
		{"SignerQuorum", 0},
		{"SignerEntries", 0},
		{"SignerListID", 0},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
	},
	"Ticket": {
		{"Account", 0},
		{"OwnerNode", 0},
		{"TicketSequence", 0},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
	},
	"AccountRoot": {
		{"Account", 0},
		{"Sequence", 0},
		{"Balance", 0},
		{"OwnerCount", 0},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
		{"AccountTxnID", 1},
		{"RegularKey", 1},
		{"EmailHash", 1},
		{"WalletLocator", 1},
		{"WalletSize", 1},
		{"MessageKey", 1},
		{"TransferRate", 1},
		{"Domain", 1},
		{"TickSize", 1},
		{"TicketCount", 1},
		{"NFTokenMinter", 1},
		{"MintedNFTokens", 2},
		{"BurnedNFTokens", 2},
		{"FirstNFTokenSequence", 1},
		{"SponsoredOwnerCount", 2},
		{"SponsoringOwnerCount", 2},
		{"SponsoringAccountCount", 2},
		{"AMMID", 1},
		{"VaultID", 1},
		{"LoanBrokerID", 1},
	},
	"DirectoryNode": {
		{"Owner", 1},
		{"TakerPaysCurrency", 1},
		{"TakerPaysIssuer", 1},
		{"TakerPaysMPT", 1},
		{"TakerGetsCurrency", 1},
		{"TakerGetsIssuer", 1},
		{"TakerGetsMPT", 1},
		{"ExchangeRate", 1},
		{"Indexes", 0},
		{"RootIndex", 0},
		{"IndexNext", 1},
		{"IndexPrevious", 1},
		{"NFTokenID", 1},
		{"PreviousTxnID", 1},
		{"PreviousTxnLgrSeq", 1},
		{"DomainID", 1},
	},
	"Amendments": {
		{"Amendments", 1},
		{"Majorities", 1},
		{"PreviousTxnID", 1},
		{"PreviousTxnLgrSeq", 1},
	},
	"LedgerHashes": {
		{"FirstLedgerSequence", 1},
		{"LastLedgerSequence", 1},
		{"Hashes", 0},
	},
	"Bridge": {
		{"Account", 0},
		{"SignatureReward", 0},
		{"MinAccountCreateAmount", 1},
		{"XChainBridge", 0},
		{"XChainClaimID", 0},
		{"XChainAccountCreateCount", 0},
		{"XChainAccountClaimCount", 0},
		{"OwnerNode", 0},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
	},
	"Offer": {
		{"Account", 0},
		{"Sequence", 0},
		{"TakerPays", 0},
		{"TakerGets", 0},
		{"BookDirectory", 0},
		{"BookNode", 0},
		{"OwnerNode", 0},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
		{"Expiration", 1},
		{"DomainID", 1},
		{"AdditionalBooks", 1},
	},
	"DepositPreauth": {
		{"Account", 0},
		{"Authorize", 1},
		{"OwnerNode", 0},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
		{"AuthorizeCredentials", 1},
	},
	"XChainOwnedClaimID": {
		{"Account", 0},
		{"XChainBridge", 0},
		{"XChainClaimID", 0},
		{"OtherChainSource", 0},
		{"XChainClaimAttestations", 0},
		{"SignatureReward", 0},
		{"OwnerNode", 0},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
	},
	"RippleState": {
		{"Balance", 0},
		{"LowLimit", 0},
		{"HighLimit", 0},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
		{"LowNode", 1},
		{"LowQualityIn", 1},
		{"LowQualityOut", 1},
		{"HighNode", 1},
		{"HighQualityIn", 1},
		{"HighQualityOut", 1},
		{"HighSponsor", 1},
		{"LowSponsor", 1},
	},
	"FeeSettings": {
		{"BaseFee", 1},
		{"ReferenceFeeUnits", 1},
		{"ReserveBase", 1},
		{"ReserveIncrement", 1},
		{"BaseFeeDrops", 1},
		{"ReserveBaseDrops", 1},
		{"ReserveIncrementDrops", 1},
		{"PreviousTxnID", 1},
		{"PreviousTxnLgrSeq", 1},
	},
	"XChainOwnedCreateAccountClaimID": {
		{"Account", 0},
		{"XChainBridge", 0},
		{"XChainAccountCreateCount", 0},
		{"XChainCreateAccountAttestations", 0},
		{"OwnerNode", 0},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
	},
	"Escrow": {
		{"Account", 0},
		{"Sequence", 1},
		{"Destination", 0},
		{"Amount", 0},
		{"Condition", 1},
		{"CancelAfter", 1},
		{"FinishAfter", 1},
		{"SourceTag", 1},
		{"DestinationTag", 1},
		{"OwnerNode", 0},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
		{"DestinationNode", 1},
		{"TransferRate", 1},
		{"IssuerNode", 1},
	},
	"PayChannel": {
		{"Account", 0},
		{"Destination", 0},
		{"Sequence", 1},
		{"Amount", 0},
		{"Balance", 0},
		{"PublicKey", 0},
		{"SettleDelay", 0},
		{"Expiration", 1},
		{"CancelAfter", 1},
		{"SourceTag", 1},
		{"DestinationTag", 1},
		{"OwnerNode", 0},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
		{"DestinationNode", 1},
	},
	"AMM": {
		{"Account", 0},
		{"TradingFee", 2},
		{"VoteSlots", 1},
		{"AuctionSlot", 1},
		{"LPTokenBalance", 0},
		{"Asset", 0},
		{"Asset2", 0},
		{"OwnerNode", 0},
		{"PreviousTxnID", 1},
		{"PreviousTxnLgrSeq", 1},
	},
	"MPTokenIssuance": {
		{"Issuer", 0},
		{"Sequence", 0},
		{"TransferFee", 2},
		{"OwnerNode", 0},
		{"AssetScale", 2},
		{"MaximumAmount", 1},
		{"OutstandingAmount", 0},
		{"LockedAmount", 1},
		{"MPTokenMetadata", 1},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
		{"DomainID", 1},
		{"ImmutableFlags", 2},
		{"ReferenceHolding", 1},
		{"IssuerEncryptionKey", 1},
		{"AuditorEncryptionKey", 1},
		{"ConfidentialOutstandingAmount", 2},
	},
	"MPToken": {
		{"Account", 0},
		{"MPTokenIssuanceID", 0},
		{"MPTAmount", 2},
		{"LockedAmount", 1},
		{"OwnerNode", 0},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
		{"ConfidentialBalanceInbox", 1},
		{"ConfidentialBalanceSpending", 1},
		{"ConfidentialBalanceVersion", 2},
		{"IssuerEncryptedBalance", 1},
		{"AuditorEncryptedBalance", 1},
		{"HolderEncryptionKey", 1},
	},
	"Oracle": {
		{"Owner", 0},
		{"OracleDocumentID", 1},
		{"Provider", 0},
		{"PriceDataSeries", 0},
		{"AssetClass", 0},
		{"LastUpdateTime", 0},
		{"URI", 1},
		{"OwnerNode", 0},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
	},
	"Credential": {
		{"Subject", 0},
		{"Issuer", 0},
		{"CredentialType", 0},
		{"Expiration", 1},
		{"URI", 1},
		{"IssuerNode", 0},
		{"SubjectNode", 1},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
	},
	"PermissionedDomain": {
		{"Owner", 0},
		{"Sequence", 0},
		{"AcceptedCredentials", 0},
		{"OwnerNode", 0},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
	},
	"Delegate": {
		{"Account", 0},
		{"Authorize", 0},
		{"Permissions", 0},
		{"OwnerNode", 0},
		{"DestinationNode", 1},
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
	},
	"Vault": {
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
		{"Sequence", 0},
		{"OwnerNode", 0},
		{"Owner", 0},
		{"Account", 0},
		{"Data", 1},
		{"Asset", 0},
		{"AssetsTotal", 2},
		{"AssetsAvailable", 2},
		{"AssetsMaximum", 2},
		{"LossUnrealized", 2},
		{"ShareMPTID", 0},
		{"WithdrawalPolicy", 0},
		{"Scale", 2},
	},
	"LoanBroker": {
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
		{"Sequence", 0},
		{"OwnerNode", 0},
		{"VaultNode", 0},
		{"VaultID", 0},
		{"Account", 0},
		{"Owner", 0},
		{"LoanSequence", 0},
		{"Data", 2},
		{"ManagementFeeRate", 2},
		{"OwnerCount", 2},
		{"DebtTotal", 2},
		{"DebtMaximum", 2},
		{"CoverAvailable", 2},
		{"CoverRateMinimum", 2},
		{"CoverRateLiquidation", 2},
	},
	"Loan": {
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
		{"OwnerNode", 0},
		{"LoanBrokerNode", 0},
		{"LoanBrokerID", 0},
		{"LoanSequence", 0},
		{"Borrower", 0},
		{"LoanOriginationFee", 2},
		{"LoanServiceFee", 2},
		{"LatePaymentFee", 2},
		{"ClosePaymentFee", 2},
		{"OverpaymentFee", 2},
		{"InterestRate", 2},
		{"LateInterestRate", 2},
		{"CloseInterestRate", 2},
		{"OverpaymentInterestRate", 2},
		{"StartDate", 0},
		{"PaymentInterval", 0},
		{"GracePeriod", 2},
		{"PreviousPaymentDueDate", 2},
		{"NextPaymentDueDate", 2},
		{"PaymentRemaining", 2},
		{"PeriodicPayment", 0},
		{"PrincipalOutstanding", 2},
		{"TotalValueOutstanding", 2},
		{"ManagementFeeOutstanding", 2},
		{"LoanScale", 2},
	},
	"Sponsorship": {
		{"PreviousTxnID", 0},
		{"PreviousTxnLgrSeq", 0},
		{"Owner", 0},
		{"Sponsee", 0},
		{"FeeAmount", 1},
		{"MaxFee", 1},
		{"RemainingOwnerCount", 2},
		{"OwnerNode", 0},
		{"SponseeNode", 0},
	},
}

// Formats returns the canonical ledger-entry formats.
func Formats() map[string][]FormatField {
	out := make(map[string][]FormatField, len(formats))
	for name, fields := range formats {
		out[name] = append([]FormatField(nil), fields...)
	}
	return out
}
