// Code generated by entrygen; DO NOT EDIT.
//
// Source: ledger/entry/schema/spec.go
// Regenerate: go generate ./ledger/entry/...

package entry

import (
	"errors"
	"fmt"

	"github.com/LeJamon/go-xrpl/codec/binarycodec"
	"github.com/LeJamon/go-xrpl/crypto/sha512half"
	"github.com/LeJamon/go-xrpl/protocol"
)

// Bridge is the typed representation of a Bridge ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every canonical field declared in the spec — including those excluded from
// metadata (sMD_Never) — so decoding and re-encoding does not drop them.
type Bridge struct {
	present                  uint64
	decoded                  bool
	dirty                    bool
	Account                  string // AccountID (base58)
	SignatureReward          any    // Amount (XRP string | IOU map)
	MinAccountCreateAmount   any    // Amount (XRP string | IOU map)
	XChainBridge             any
	XChainClaimID            string // UInt64 (lowercase hex, no leading zeros)
	XChainAccountCreateCount string // UInt64 (lowercase hex, no leading zeros)
	XChainAccountClaimCount  string // UInt64 (lowercase hex, no leading zeros)
	OwnerNode                string // UInt64 (lowercase hex, no leading zeros)
	Flags                    uint32
	PreviousTxnID            string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq        uint32
}

// Type returns the concrete ledger-entry type.
func (*Bridge) Type() Type {
	return Type(105)
}

const (
	bridgeBitAccount uint64 = 1 << iota
	bridgeBitSignatureReward
	bridgeBitMinAccountCreateAmount
	bridgeBitXChainBridge
	bridgeBitXChainClaimID
	bridgeBitXChainAccountCreateCount
	bridgeBitXChainAccountClaimCount
	bridgeBitOwnerNode
	bridgeBitFlags
	bridgeBitPreviousTxnID
	bridgeBitPreviousTxnLgrSeq
)

// SetAccount assigns Account and updates its serialized presence.
func (b *Bridge) SetAccount(value string) {
	b.Account = value
	b.dirty = true
	b.present |= bridgeBitAccount
}

// SetSignatureReward assigns SignatureReward and updates its serialized presence.
func (b *Bridge) SetSignatureReward(value any) {
	b.SignatureReward = value
	b.dirty = true
	b.present |= bridgeBitSignatureReward
}

// SetMinAccountCreateAmount assigns MinAccountCreateAmount and updates its serialized presence.
func (b *Bridge) SetMinAccountCreateAmount(value any) {
	b.MinAccountCreateAmount = value
	b.dirty = true
	b.present |= bridgeBitMinAccountCreateAmount
}

// SetXChainBridge assigns XChainBridge and updates its serialized presence.
func (b *Bridge) SetXChainBridge(value any) {
	b.XChainBridge = value
	b.dirty = true
	b.present |= bridgeBitXChainBridge
}

// SetXChainClaimID assigns XChainClaimID and updates its serialized presence.
func (b *Bridge) SetXChainClaimID(value string) {
	b.XChainClaimID = value
	b.dirty = true
	b.present |= bridgeBitXChainClaimID
}

// SetXChainAccountCreateCount assigns XChainAccountCreateCount and updates its serialized presence.
func (b *Bridge) SetXChainAccountCreateCount(value string) {
	b.XChainAccountCreateCount = value
	b.dirty = true
	b.present |= bridgeBitXChainAccountCreateCount
}

// SetXChainAccountClaimCount assigns XChainAccountClaimCount and updates its serialized presence.
func (b *Bridge) SetXChainAccountClaimCount(value string) {
	b.XChainAccountClaimCount = value
	b.dirty = true
	b.present |= bridgeBitXChainAccountClaimCount
}

// SetOwnerNode assigns OwnerNode and updates its serialized presence.
func (b *Bridge) SetOwnerNode(value string) {
	b.OwnerNode = value
	b.dirty = true
	b.present |= bridgeBitOwnerNode
}

// SetFlags assigns Flags and updates its serialized presence.
func (b *Bridge) SetFlags(value uint32) {
	b.Flags = value
	b.dirty = true
	b.present |= bridgeBitFlags
}

// SetPreviousTxnID assigns PreviousTxnID and updates its serialized presence.
func (b *Bridge) SetPreviousTxnID(value string) {
	b.PreviousTxnID = value
	b.dirty = true
	b.present |= bridgeBitPreviousTxnID
}

// SetPreviousTxnLgrSeq assigns PreviousTxnLgrSeq and updates its serialized presence.
func (b *Bridge) SetPreviousTxnLgrSeq(value uint32) {
	b.PreviousTxnLgrSeq = value
	b.dirty = true
	b.present |= bridgeBitPreviousTxnLgrSeq
}

func (b *Bridge) validateRequired() error {
	if b.decoded && !b.dirty {
		return nil
	}
	if b.present&bridgeBitAccount == 0 {
		return errors.New("ledgerfields: Bridge: required field Account is not set")
	}
	if b.present&bridgeBitSignatureReward == 0 {
		return errors.New("ledgerfields: Bridge: required field SignatureReward is not set")
	}
	if b.present&bridgeBitXChainBridge == 0 {
		return errors.New("ledgerfields: Bridge: required field XChainBridge is not set")
	}
	if b.present&bridgeBitXChainClaimID == 0 {
		return errors.New("ledgerfields: Bridge: required field XChainClaimID is not set")
	}
	if b.present&bridgeBitXChainAccountCreateCount == 0 {
		return errors.New("ledgerfields: Bridge: required field XChainAccountCreateCount is not set")
	}
	if b.present&bridgeBitXChainAccountClaimCount == 0 {
		return errors.New("ledgerfields: Bridge: required field XChainAccountClaimCount is not set")
	}
	if b.present&bridgeBitOwnerNode == 0 {
		return errors.New("ledgerfields: Bridge: required field OwnerNode is not set")
	}
	if b.present&bridgeBitFlags == 0 {
		return errors.New("ledgerfields: Bridge: required field Flags is not set")
	}
	return nil
}

func (b *Bridge) validateDecoded() error {
	if b.present&bridgeBitAccount == 0 {
		return errors.New("ledgerfields: Bridge: required field Account is missing")
	}
	if b.present&bridgeBitSignatureReward == 0 {
		return errors.New("ledgerfields: Bridge: required field SignatureReward is missing")
	}
	if b.present&bridgeBitXChainBridge == 0 {
		return errors.New("ledgerfields: Bridge: required field XChainBridge is missing")
	}
	if b.present&bridgeBitXChainClaimID == 0 {
		return errors.New("ledgerfields: Bridge: required field XChainClaimID is missing")
	}
	if b.present&bridgeBitXChainAccountCreateCount == 0 {
		return errors.New("ledgerfields: Bridge: required field XChainAccountCreateCount is missing")
	}
	if b.present&bridgeBitXChainAccountClaimCount == 0 {
		return errors.New("ledgerfields: Bridge: required field XChainAccountClaimCount is missing")
	}
	if b.present&bridgeBitOwnerNode == 0 {
		return errors.New("ledgerfields: Bridge: required field OwnerNode is missing")
	}
	if b.present&bridgeBitFlags == 0 {
		return errors.New("ledgerfields: Bridge: required field Flags is missing")
	}
	if b.present&bridgeBitPreviousTxnID == 0 {
		return errors.New("ledgerfields: Bridge: required field PreviousTxnID is missing")
	}
	if b.present&bridgeBitPreviousTxnLgrSeq == 0 {
		return errors.New("ledgerfields: Bridge: required field PreviousTxnLgrSeq is missing")
	}
	return nil
}

// Decode populates the struct from binary ledger-entry data via a streaming
// reader and enforces the current rippled ledger template.
func (b *Bridge) Decode(data []byte) error {
	return b.decode(data, false)
}

func (b *Bridge) decodeLegacy(data []byte) error {
	return b.decode(data, true)
}

func (b *Bridge) decode(data []byte, legacy bool) error {
	*b = Bridge{}
	sr := newStreamReader(data)
	seenFields := make(map[[2]int]struct{})
	sawLedgerEntryType := false
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		fieldID := [2]int{typeCode, fieldCode}
		if _, exists := seenFields[fieldID]; exists {
			return fmt.Errorf("ledgerfields: Bridge: duplicate field type=%d field=%d", typeCode, fieldCode)
		}
		seenFields[fieldID] = struct{}{}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				if val != 105 {
					return fmt.Errorf("ledgerfields: Bridge: LedgerEntryType is %d, want 105", val)
				}
				sawLedgerEntryType = true
			default:
				return newErrUnknownField("Bridge", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				b.Flags = val
				b.present |= bridgeBitFlags
			case 5:
				b.PreviousTxnLgrSeq = val
				b.present |= bridgeBitPreviousTxnLgrSeq
			default:
				return newErrUnknownField("Bridge", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 4:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				b.OwnerNode = val
				b.present |= bridgeBitOwnerNode
			case 20:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				b.XChainClaimID = val
				b.present |= bridgeBitXChainClaimID
			case 21:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				b.XChainAccountCreateCount = val
				b.present |= bridgeBitXChainAccountCreateCount
			case 22:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				b.XChainAccountClaimCount = val
				b.present |= bridgeBitXChainAccountClaimCount
			default:
				return newErrUnknownField("Bridge", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				b.PreviousTxnID = val
				b.present |= bridgeBitPreviousTxnID
			default:
				return newErrUnknownField("Bridge", typeCode, fieldCode)
			}
		case 6: // Amount
			val, err := sr.readAmountAny()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 29:
				b.SignatureReward = val
				b.present |= bridgeBitSignatureReward
			case 30:
				b.MinAccountCreateAmount = val
				b.present |= bridgeBitMinAccountCreateAmount
			default:
				return newErrUnknownField("Bridge", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				b.Account = val
				b.present |= bridgeBitAccount
			default:
				return newErrUnknownField("Bridge", typeCode, fieldCode)
			}
		case 25: // XChainBridge
			val, err := sr.readXChainBridge()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				b.XChainBridge = val
				b.present |= bridgeBitXChainBridge
			default:
				return newErrUnknownField("Bridge", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("Bridge", typeCode, fieldCode)
		}
	}
	if !sawLedgerEntryType {
		return errors.New("ledgerfields: Bridge: missing LedgerEntryType")
	}
	b.decoded = true
	if !legacy {
		return b.validateDecoded()
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (b *Bridge) emitAll(out map[string]any, skipDefault bool) {
	if b.present&bridgeBitAccount != 0 && !(skipDefault && b.Account == "") {
		out["Account"] = b.Account
	}
	if b.present&bridgeBitSignatureReward != 0 && !(skipDefault && amountIsDefault(b.SignatureReward)) {
		out["SignatureReward"] = b.SignatureReward
	}
	if b.present&bridgeBitMinAccountCreateAmount != 0 && !(skipDefault && amountIsDefault(b.MinAccountCreateAmount)) {
		out["MinAccountCreateAmount"] = b.MinAccountCreateAmount
	}
	if b.present&bridgeBitXChainBridge != 0 && !(skipDefault && xchainBridgeIsDefault(b.XChainBridge)) {
		out["XChainBridge"] = b.XChainBridge
	}
	if b.present&bridgeBitXChainClaimID != 0 && !(skipDefault && isZeroHexString(b.XChainClaimID)) {
		out["XChainClaimID"] = b.XChainClaimID
	}
	if b.present&bridgeBitXChainAccountCreateCount != 0 && !(skipDefault && isZeroHexString(b.XChainAccountCreateCount)) {
		out["XChainAccountCreateCount"] = b.XChainAccountCreateCount
	}
	if b.present&bridgeBitXChainAccountClaimCount != 0 && !(skipDefault && isZeroHexString(b.XChainAccountClaimCount)) {
		out["XChainAccountClaimCount"] = b.XChainAccountClaimCount
	}
	if b.present&bridgeBitOwnerNode != 0 && !(skipDefault && isZeroHexString(b.OwnerNode)) {
		out["OwnerNode"] = b.OwnerNode
	}
	if b.present&bridgeBitFlags != 0 && !(skipDefault && b.Flags == 0) {
		out["Flags"] = b.Flags
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (b *Bridge) EmitNewFields(out map[string]any) {
	b.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (b *Bridge) EmitFinalFields(out map[string]any) {
	b.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (b *Bridge) EmitPreviousFields(prev Entry, out map[string]any) {
	prv, ok := prev.(*Bridge)
	if !ok || prv == nil {
		return
	}
	emitIfChangedString(out, "Account", prv.Account, b.Account, prv.present&bridgeBitAccount, b.present&bridgeBitAccount)
	emitIfChangedAmount(out, "SignatureReward", prv.SignatureReward, b.SignatureReward, prv.present&bridgeBitSignatureReward, b.present&bridgeBitSignatureReward)
	emitIfChangedAmount(out, "MinAccountCreateAmount", prv.MinAccountCreateAmount, b.MinAccountCreateAmount, prv.present&bridgeBitMinAccountCreateAmount, b.present&bridgeBitMinAccountCreateAmount)
	emitIfChangedDeep(out, "XChainBridge", prv.XChainBridge, b.XChainBridge, prv.present&bridgeBitXChainBridge, b.present&bridgeBitXChainBridge)
	emitIfChangedString(out, "XChainClaimID", prv.XChainClaimID, b.XChainClaimID, prv.present&bridgeBitXChainClaimID, b.present&bridgeBitXChainClaimID)
	emitIfChangedString(out, "XChainAccountCreateCount", prv.XChainAccountCreateCount, b.XChainAccountCreateCount, prv.present&bridgeBitXChainAccountCreateCount, b.present&bridgeBitXChainAccountCreateCount)
	emitIfChangedString(out, "XChainAccountClaimCount", prv.XChainAccountClaimCount, b.XChainAccountClaimCount, prv.present&bridgeBitXChainAccountClaimCount, b.present&bridgeBitXChainAccountClaimCount)
	emitIfChangedString(out, "OwnerNode", prv.OwnerNode, b.OwnerNode, prv.present&bridgeBitOwnerNode, b.present&bridgeBitOwnerNode)
	emitIfChangedUint32(out, "Flags", prv.Flags, b.Flags, prv.present&bridgeBitFlags, b.present&bridgeBitFlags)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (b *Bridge) EmitChangeOrigFields(out map[string]any) {
	if b.present&bridgeBitAccount != 0 {
		out["Account"] = b.Account
	}
	if b.present&bridgeBitSignatureReward != 0 {
		out["SignatureReward"] = b.SignatureReward
	}
	if b.present&bridgeBitMinAccountCreateAmount != 0 {
		out["MinAccountCreateAmount"] = b.MinAccountCreateAmount
	}
	if b.present&bridgeBitXChainBridge != 0 {
		out["XChainBridge"] = b.XChainBridge
	}
	if b.present&bridgeBitXChainClaimID != 0 {
		out["XChainClaimID"] = b.XChainClaimID
	}
	if b.present&bridgeBitXChainAccountCreateCount != 0 {
		out["XChainAccountCreateCount"] = b.XChainAccountCreateCount
	}
	if b.present&bridgeBitXChainAccountClaimCount != 0 {
		out["XChainAccountClaimCount"] = b.XChainAccountClaimCount
	}
	if b.present&bridgeBitOwnerNode != 0 {
		out["OwnerNode"] = b.OwnerNode
	}
	if b.present&bridgeBitFlags != 0 {
		out["Flags"] = b.Flags
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (b *Bridge) EmitDeleteFinalFields(out map[string]any) {
	b.emitAll(out, false)
	if b.present&bridgeBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = b.PreviousTxnID
	}
	if b.present&bridgeBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = b.PreviousTxnLgrSeq
	}
}

func (b *Bridge) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	b.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (b *Bridge) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if b.present&bridgeBitPreviousTxnID != 0 {
		id = b.PreviousTxnID
	}
	if b.present&bridgeBitPreviousTxnLgrSeq != 0 {
		seq = b.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (b *Bridge) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "Bridge",
	}
	if b.present&bridgeBitAccount != 0 {
		out["Account"] = b.Account
	}
	if b.present&bridgeBitSignatureReward != 0 {
		out["SignatureReward"] = b.SignatureReward
	}
	if b.present&bridgeBitMinAccountCreateAmount != 0 {
		out["MinAccountCreateAmount"] = b.MinAccountCreateAmount
	}
	if b.present&bridgeBitXChainBridge != 0 {
		out["XChainBridge"] = b.XChainBridge
	}
	if b.present&bridgeBitXChainClaimID != 0 {
		out["XChainClaimID"] = b.XChainClaimID
	}
	if b.present&bridgeBitXChainAccountCreateCount != 0 {
		out["XChainAccountCreateCount"] = b.XChainAccountCreateCount
	}
	if b.present&bridgeBitXChainAccountClaimCount != 0 {
		out["XChainAccountClaimCount"] = b.XChainAccountClaimCount
	}
	if b.present&bridgeBitOwnerNode != 0 {
		out["OwnerNode"] = b.OwnerNode
	}
	if b.present&bridgeBitFlags != 0 {
		out["Flags"] = b.Flags
	}
	if b.present&bridgeBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = b.PreviousTxnID
	}
	if b.present&bridgeBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = b.PreviousTxnLgrSeq
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Legacy decode
// aliases and non-canonical input ordering are emitted in canonical form.
func (b *Bridge) Encode() ([]byte, error) {
	if err := b.validateRequired(); err != nil {
		return nil, err
	}
	out := b.ToMap()
	if b.present&bridgeBitPreviousTxnID == 0 {
		out["PreviousTxnID"] = "0000000000000000000000000000000000000000000000000000000000000000"
	}
	if b.present&bridgeBitPreviousTxnLgrSeq == 0 {
		out["PreviousTxnLgrSeq"] = uint32(0)
	}
	return binarycodec.EncodeBytes(out)
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (b *Bridge) Hash(index [32]byte) ([32]byte, error) {
	data, err := b.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode()
	return sha512half.Sum(prefix[:], data, index[:]), nil
}
