// Code generated by entrygen; DO NOT EDIT.
//
// Source: ledger/entry/schema/spec.go
// Regenerate: go generate ./ledger/entry/...

package entry

import (
	"errors"
	"fmt"

	"github.com/LeJamon/go-xrpl/codec/binarycodec"
	"github.com/LeJamon/go-xrpl/crypto/sha512half"
	"github.com/LeJamon/go-xrpl/protocol"
)

// MPTokenIssuance is the typed representation of a MPTokenIssuance ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every canonical field declared in the spec — including those excluded from
// metadata (sMD_Never) — so decoding and re-encoding does not drop them.
type MPTokenIssuance struct {
	present           uint64
	decoded           bool
	dirty             bool
	Issuer            string // AccountID (base58)
	Sequence          uint32
	TransferFee       int
	OwnerNode         string // UInt64 (lowercase hex, no leading zeros)
	AssetScale        int
	MaximumAmount     string // UInt64 (decimal string, sMD_BaseTen)
	OutstandingAmount string // UInt64 (decimal string, sMD_BaseTen)
	LockedAmount      string // UInt64 (decimal string, sMD_BaseTen)
	MPTokenMetadata   string // Blob (uppercase hex)
	DomainID          string // Hash256 (uppercase hex)
	ImmutableFlags    uint32
	ReferenceHolding  string // Hash256 (uppercase hex)
	Flags             uint32
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
	Sponsor           string // AccountID (base58)
}

// Type returns the concrete ledger-entry type.
func (*MPTokenIssuance) Type() Type {
	return Type(126)
}

const (
	mptokenissuanceBitIssuer uint64 = 1 << iota
	mptokenissuanceBitSequence
	mptokenissuanceBitTransferFee
	mptokenissuanceBitOwnerNode
	mptokenissuanceBitAssetScale
	mptokenissuanceBitMaximumAmount
	mptokenissuanceBitOutstandingAmount
	mptokenissuanceBitLockedAmount
	mptokenissuanceBitMPTokenMetadata
	mptokenissuanceBitDomainID
	mptokenissuanceBitImmutableFlags
	mptokenissuanceBitReferenceHolding
	mptokenissuanceBitFlags
	mptokenissuanceBitPreviousTxnID
	mptokenissuanceBitPreviousTxnLgrSeq
	mptokenissuanceBitSponsor
)

// SetIssuer assigns Issuer and updates its serialized presence.
func (m *MPTokenIssuance) SetIssuer(value string) {
	m.Issuer = value
	m.dirty = true
	m.present |= mptokenissuanceBitIssuer
}

// SetSequence assigns Sequence and updates its serialized presence.
func (m *MPTokenIssuance) SetSequence(value uint32) {
	m.Sequence = value
	m.dirty = true
	m.present |= mptokenissuanceBitSequence
}

// SetTransferFee assigns TransferFee and updates its serialized presence.
func (m *MPTokenIssuance) SetTransferFee(value uint16) {
	m.TransferFee = int(value)
	m.dirty = true
	if value == 0 {
		m.present &^= mptokenissuanceBitTransferFee
		return
	}
	m.present |= mptokenissuanceBitTransferFee
}

// SetOwnerNode assigns OwnerNode and updates its serialized presence.
func (m *MPTokenIssuance) SetOwnerNode(value string) {
	m.OwnerNode = value
	m.dirty = true
	m.present |= mptokenissuanceBitOwnerNode
}

// SetAssetScale assigns AssetScale and updates its serialized presence.
func (m *MPTokenIssuance) SetAssetScale(value uint8) {
	m.AssetScale = int(value)
	m.dirty = true
	if value == 0 {
		m.present &^= mptokenissuanceBitAssetScale
		return
	}
	m.present |= mptokenissuanceBitAssetScale
}

// SetMaximumAmount assigns MaximumAmount and updates its serialized presence.
func (m *MPTokenIssuance) SetMaximumAmount(value string) {
	m.MaximumAmount = value
	m.dirty = true
	m.present |= mptokenissuanceBitMaximumAmount
}

// SetOutstandingAmount assigns OutstandingAmount and updates its serialized presence.
func (m *MPTokenIssuance) SetOutstandingAmount(value string) {
	m.OutstandingAmount = value
	m.dirty = true
	m.present |= mptokenissuanceBitOutstandingAmount
}

// SetLockedAmount assigns LockedAmount and updates its serialized presence.
func (m *MPTokenIssuance) SetLockedAmount(value string) {
	m.LockedAmount = value
	m.dirty = true
	m.present |= mptokenissuanceBitLockedAmount
}

// SetMPTokenMetadata assigns MPTokenMetadata and updates its serialized presence.
func (m *MPTokenIssuance) SetMPTokenMetadata(value string) {
	m.MPTokenMetadata = value
	m.dirty = true
	m.present |= mptokenissuanceBitMPTokenMetadata
}

// SetDomainID assigns DomainID and updates its serialized presence.
func (m *MPTokenIssuance) SetDomainID(value string) {
	m.DomainID = value
	m.dirty = true
	m.present |= mptokenissuanceBitDomainID
}

// SetImmutableFlags assigns ImmutableFlags and updates its serialized presence.
func (m *MPTokenIssuance) SetImmutableFlags(value uint32) {
	m.ImmutableFlags = value
	m.dirty = true
	if value == 0 {
		m.present &^= mptokenissuanceBitImmutableFlags
		return
	}
	m.present |= mptokenissuanceBitImmutableFlags
}

// SetReferenceHolding assigns ReferenceHolding and updates its serialized presence.
func (m *MPTokenIssuance) SetReferenceHolding(value string) {
	m.ReferenceHolding = value
	m.dirty = true
	m.present |= mptokenissuanceBitReferenceHolding
}

// SetFlags assigns Flags and updates its serialized presence.
func (m *MPTokenIssuance) SetFlags(value uint32) {
	m.Flags = value
	m.dirty = true
	m.present |= mptokenissuanceBitFlags
}

// SetPreviousTxnID assigns PreviousTxnID and updates its serialized presence.
func (m *MPTokenIssuance) SetPreviousTxnID(value string) {
	m.PreviousTxnID = value
	m.dirty = true
	m.present |= mptokenissuanceBitPreviousTxnID
}

// SetPreviousTxnLgrSeq assigns PreviousTxnLgrSeq and updates its serialized presence.
func (m *MPTokenIssuance) SetPreviousTxnLgrSeq(value uint32) {
	m.PreviousTxnLgrSeq = value
	m.dirty = true
	m.present |= mptokenissuanceBitPreviousTxnLgrSeq
}

// SetSponsor assigns Sponsor and updates its serialized presence.
func (m *MPTokenIssuance) SetSponsor(value string) {
	m.Sponsor = value
	m.dirty = true
	m.present |= mptokenissuanceBitSponsor
}

func (m *MPTokenIssuance) validateRequired() error {
	if m.decoded && !m.dirty {
		return nil
	}
	if m.present&mptokenissuanceBitIssuer == 0 {
		return errors.New("ledgerfields: MPTokenIssuance: required field Issuer is not set")
	}
	if m.present&mptokenissuanceBitSequence == 0 {
		return errors.New("ledgerfields: MPTokenIssuance: required field Sequence is not set")
	}
	if m.present&mptokenissuanceBitOwnerNode == 0 {
		return errors.New("ledgerfields: MPTokenIssuance: required field OwnerNode is not set")
	}
	if m.present&mptokenissuanceBitOutstandingAmount == 0 {
		return errors.New("ledgerfields: MPTokenIssuance: required field OutstandingAmount is not set")
	}
	if m.present&mptokenissuanceBitFlags == 0 {
		return errors.New("ledgerfields: MPTokenIssuance: required field Flags is not set")
	}
	return nil
}

func (m *MPTokenIssuance) validateDecoded() error {
	if m.present&mptokenissuanceBitIssuer == 0 {
		return errors.New("ledgerfields: MPTokenIssuance: required field Issuer is missing")
	}
	if m.present&mptokenissuanceBitSequence == 0 {
		return errors.New("ledgerfields: MPTokenIssuance: required field Sequence is missing")
	}
	if m.present&mptokenissuanceBitTransferFee != 0 && m.TransferFee == 0 {
		return errors.New("ledgerfields: MPTokenIssuance: default field TransferFee is explicitly set")
	}
	if m.present&mptokenissuanceBitOwnerNode == 0 {
		return errors.New("ledgerfields: MPTokenIssuance: required field OwnerNode is missing")
	}
	if m.present&mptokenissuanceBitAssetScale != 0 && m.AssetScale == 0 {
		return errors.New("ledgerfields: MPTokenIssuance: default field AssetScale is explicitly set")
	}
	if m.present&mptokenissuanceBitOutstandingAmount == 0 {
		return errors.New("ledgerfields: MPTokenIssuance: required field OutstandingAmount is missing")
	}
	if m.present&mptokenissuanceBitImmutableFlags != 0 && m.ImmutableFlags == 0 {
		return errors.New("ledgerfields: MPTokenIssuance: default field ImmutableFlags is explicitly set")
	}
	if m.present&mptokenissuanceBitFlags == 0 {
		return errors.New("ledgerfields: MPTokenIssuance: required field Flags is missing")
	}
	if m.present&mptokenissuanceBitPreviousTxnID == 0 {
		return errors.New("ledgerfields: MPTokenIssuance: required field PreviousTxnID is missing")
	}
	if m.present&mptokenissuanceBitPreviousTxnLgrSeq == 0 {
		return errors.New("ledgerfields: MPTokenIssuance: required field PreviousTxnLgrSeq is missing")
	}
	return nil
}

// Decode populates the struct from binary ledger-entry data via a streaming
// reader and enforces the current rippled ledger template.
func (m *MPTokenIssuance) Decode(data []byte) error {
	return m.decode(data, false)
}

func (m *MPTokenIssuance) decodeLegacy(data []byte) error {
	return m.decode(data, true)
}

func (m *MPTokenIssuance) decode(data []byte, legacy bool) error {
	*m = MPTokenIssuance{}
	sr := newStreamReader(data)
	seenFields := make(map[[2]int]struct{})
	sawLedgerEntryType := false
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		fieldID := [2]int{typeCode, fieldCode}
		if _, exists := seenFields[fieldID]; exists {
			return fmt.Errorf("ledgerfields: MPTokenIssuance: duplicate field type=%d field=%d", typeCode, fieldCode)
		}
		seenFields[fieldID] = struct{}{}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				if val != 126 {
					return fmt.Errorf("ledgerfields: MPTokenIssuance: LedgerEntryType is %d, want 126", val)
				}
				sawLedgerEntryType = true
			case 4:
				m.TransferFee = val
				m.present |= mptokenissuanceBitTransferFee
			default:
				return newErrUnknownField("MPTokenIssuance", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				m.Flags = val
				m.present |= mptokenissuanceBitFlags
			case 4:
				m.Sequence = val
				m.present |= mptokenissuanceBitSequence
			case 5:
				m.PreviousTxnLgrSeq = val
				m.present |= mptokenissuanceBitPreviousTxnLgrSeq
			case 53:
				m.ImmutableFlags = val
				m.present |= mptokenissuanceBitImmutableFlags
			default:
				return newErrUnknownField("MPTokenIssuance", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 4:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				m.OwnerNode = val
				m.present |= mptokenissuanceBitOwnerNode
			case 24:
				val, err := sr.readUint64Decimal()
				if err != nil {
					return err
				}
				m.MaximumAmount = val
				m.present |= mptokenissuanceBitMaximumAmount
			case 25:
				val, err := sr.readUint64Decimal()
				if err != nil {
					return err
				}
				m.OutstandingAmount = val
				m.present |= mptokenissuanceBitOutstandingAmount
			case 29:
				val, err := sr.readUint64Decimal()
				if err != nil {
					return err
				}
				m.LockedAmount = val
				m.present |= mptokenissuanceBitLockedAmount
			default:
				return newErrUnknownField("MPTokenIssuance", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				m.PreviousTxnID = val
				m.present |= mptokenissuanceBitPreviousTxnID
			case 34:
				m.DomainID = val
				m.present |= mptokenissuanceBitDomainID
			case 39:
				m.ReferenceHolding = val
				m.present |= mptokenissuanceBitReferenceHolding
			default:
				return newErrUnknownField("MPTokenIssuance", typeCode, fieldCode)
			}
		case 7: // Blob
			val, err := sr.readBlobHex()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 30:
				m.MPTokenMetadata = val
				m.present |= mptokenissuanceBitMPTokenMetadata
			default:
				return newErrUnknownField("MPTokenIssuance", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 4:
				m.Issuer = val
				m.present |= mptokenissuanceBitIssuer
			case 27:
				m.Sponsor = val
				m.present |= mptokenissuanceBitSponsor
			default:
				return newErrUnknownField("MPTokenIssuance", typeCode, fieldCode)
			}
		case 16: // UInt8
			byteVal, err := sr.readUint8()
			if err != nil {
				return err
			}
			val := int(byteVal)
			switch fieldCode {
			case 5:
				m.AssetScale = val
				m.present |= mptokenissuanceBitAssetScale
			default:
				return newErrUnknownField("MPTokenIssuance", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("MPTokenIssuance", typeCode, fieldCode)
		}
	}
	if !sawLedgerEntryType {
		return errors.New("ledgerfields: MPTokenIssuance: missing LedgerEntryType")
	}
	m.decoded = true
	if !legacy {
		return m.validateDecoded()
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (m *MPTokenIssuance) emitAll(out map[string]any, skipDefault bool) {
	if m.present&mptokenissuanceBitIssuer != 0 && !(skipDefault && m.Issuer == "") {
		out["Issuer"] = m.Issuer
	}
	if m.present&mptokenissuanceBitSequence != 0 && !(skipDefault && m.Sequence == 0) {
		out["Sequence"] = m.Sequence
	}
	if m.present&mptokenissuanceBitTransferFee != 0 && !(skipDefault && m.TransferFee == 0) {
		out["TransferFee"] = m.TransferFee
	}
	if m.present&mptokenissuanceBitOwnerNode != 0 && !(skipDefault && isZeroHexString(m.OwnerNode)) {
		out["OwnerNode"] = m.OwnerNode
	}
	if m.present&mptokenissuanceBitAssetScale != 0 && !(skipDefault && m.AssetScale == 0) {
		out["AssetScale"] = m.AssetScale
	}
	if m.present&mptokenissuanceBitMaximumAmount != 0 && !(skipDefault && isZeroHexString(m.MaximumAmount)) {
		out["MaximumAmount"] = m.MaximumAmount
	}
	if m.present&mptokenissuanceBitOutstandingAmount != 0 && !(skipDefault && isZeroHexString(m.OutstandingAmount)) {
		out["OutstandingAmount"] = m.OutstandingAmount
	}
	if m.present&mptokenissuanceBitLockedAmount != 0 && !(skipDefault && isZeroHexString(m.LockedAmount)) {
		out["LockedAmount"] = m.LockedAmount
	}
	if m.present&mptokenissuanceBitMPTokenMetadata != 0 && !(skipDefault && m.MPTokenMetadata == "") {
		out["MPTokenMetadata"] = m.MPTokenMetadata
	}
	if m.present&mptokenissuanceBitDomainID != 0 && !(skipDefault && isZeroHexString(m.DomainID)) {
		out["DomainID"] = m.DomainID
	}
	if m.present&mptokenissuanceBitImmutableFlags != 0 && !(skipDefault && m.ImmutableFlags == 0) {
		out["ImmutableFlags"] = m.ImmutableFlags
	}
	if m.present&mptokenissuanceBitReferenceHolding != 0 && !(skipDefault && isZeroHexString(m.ReferenceHolding)) {
		out["ReferenceHolding"] = m.ReferenceHolding
	}
	if m.present&mptokenissuanceBitFlags != 0 && !(skipDefault && m.Flags == 0) {
		out["Flags"] = m.Flags
	}
	if m.present&mptokenissuanceBitSponsor != 0 && !(skipDefault && m.Sponsor == "") {
		out["Sponsor"] = m.Sponsor
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (m *MPTokenIssuance) EmitNewFields(out map[string]any) {
	m.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (m *MPTokenIssuance) EmitFinalFields(out map[string]any) {
	m.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (m *MPTokenIssuance) EmitPreviousFields(prev Entry, out map[string]any) {
	prv, ok := prev.(*MPTokenIssuance)
	if !ok || prv == nil {
		return
	}
	emitIfChangedString(out, "Issuer", prv.Issuer, m.Issuer, prv.present&mptokenissuanceBitIssuer, m.present&mptokenissuanceBitIssuer)
	emitIfChangedUint32(out, "Sequence", prv.Sequence, m.Sequence, prv.present&mptokenissuanceBitSequence, m.present&mptokenissuanceBitSequence)
	emitIfChangedInt(out, "TransferFee", prv.TransferFee, m.TransferFee, prv.present&mptokenissuanceBitTransferFee, m.present&mptokenissuanceBitTransferFee)
	emitIfChangedString(out, "OwnerNode", prv.OwnerNode, m.OwnerNode, prv.present&mptokenissuanceBitOwnerNode, m.present&mptokenissuanceBitOwnerNode)
	emitIfChangedInt(out, "AssetScale", prv.AssetScale, m.AssetScale, prv.present&mptokenissuanceBitAssetScale, m.present&mptokenissuanceBitAssetScale)
	emitIfChangedString(out, "MaximumAmount", prv.MaximumAmount, m.MaximumAmount, prv.present&mptokenissuanceBitMaximumAmount, m.present&mptokenissuanceBitMaximumAmount)
	emitIfChangedString(out, "OutstandingAmount", prv.OutstandingAmount, m.OutstandingAmount, prv.present&mptokenissuanceBitOutstandingAmount, m.present&mptokenissuanceBitOutstandingAmount)
	emitIfChangedString(out, "LockedAmount", prv.LockedAmount, m.LockedAmount, prv.present&mptokenissuanceBitLockedAmount, m.present&mptokenissuanceBitLockedAmount)
	emitIfChangedString(out, "MPTokenMetadata", prv.MPTokenMetadata, m.MPTokenMetadata, prv.present&mptokenissuanceBitMPTokenMetadata, m.present&mptokenissuanceBitMPTokenMetadata)
	emitIfChangedString(out, "DomainID", prv.DomainID, m.DomainID, prv.present&mptokenissuanceBitDomainID, m.present&mptokenissuanceBitDomainID)
	emitIfChangedUint32(out, "ImmutableFlags", prv.ImmutableFlags, m.ImmutableFlags, prv.present&mptokenissuanceBitImmutableFlags, m.present&mptokenissuanceBitImmutableFlags)
	emitIfChangedString(out, "ReferenceHolding", prv.ReferenceHolding, m.ReferenceHolding, prv.present&mptokenissuanceBitReferenceHolding, m.present&mptokenissuanceBitReferenceHolding)
	emitIfChangedUint32(out, "Flags", prv.Flags, m.Flags, prv.present&mptokenissuanceBitFlags, m.present&mptokenissuanceBitFlags)
	emitIfChangedString(out, "Sponsor", prv.Sponsor, m.Sponsor, prv.present&mptokenissuanceBitSponsor, m.present&mptokenissuanceBitSponsor)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (m *MPTokenIssuance) EmitChangeOrigFields(out map[string]any) {
	if m.present&mptokenissuanceBitIssuer != 0 {
		out["Issuer"] = m.Issuer
	}
	if m.present&mptokenissuanceBitSequence != 0 {
		out["Sequence"] = m.Sequence
	}
	if m.present&mptokenissuanceBitTransferFee != 0 {
		out["TransferFee"] = m.TransferFee
	}
	if m.present&mptokenissuanceBitOwnerNode != 0 {
		out["OwnerNode"] = m.OwnerNode
	}
	if m.present&mptokenissuanceBitAssetScale != 0 {
		out["AssetScale"] = m.AssetScale
	}
	if m.present&mptokenissuanceBitMaximumAmount != 0 {
		out["MaximumAmount"] = m.MaximumAmount
	}
	if m.present&mptokenissuanceBitOutstandingAmount != 0 {
		out["OutstandingAmount"] = m.OutstandingAmount
	}
	if m.present&mptokenissuanceBitLockedAmount != 0 {
		out["LockedAmount"] = m.LockedAmount
	}
	if m.present&mptokenissuanceBitMPTokenMetadata != 0 {
		out["MPTokenMetadata"] = m.MPTokenMetadata
	}
	if m.present&mptokenissuanceBitDomainID != 0 {
		out["DomainID"] = m.DomainID
	}
	if m.present&mptokenissuanceBitImmutableFlags != 0 {
		out["ImmutableFlags"] = m.ImmutableFlags
	}
	if m.present&mptokenissuanceBitReferenceHolding != 0 {
		out["ReferenceHolding"] = m.ReferenceHolding
	}
	if m.present&mptokenissuanceBitFlags != 0 {
		out["Flags"] = m.Flags
	}
	if m.present&mptokenissuanceBitSponsor != 0 {
		out["Sponsor"] = m.Sponsor
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (m *MPTokenIssuance) EmitDeleteFinalFields(out map[string]any) {
	m.emitAll(out, false)
	if m.present&mptokenissuanceBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = m.PreviousTxnID
	}
	if m.present&mptokenissuanceBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = m.PreviousTxnLgrSeq
	}
}

func (m *MPTokenIssuance) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	m.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (m *MPTokenIssuance) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if m.present&mptokenissuanceBitPreviousTxnID != 0 {
		id = m.PreviousTxnID
	}
	if m.present&mptokenissuanceBitPreviousTxnLgrSeq != 0 {
		seq = m.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (m *MPTokenIssuance) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "MPTokenIssuance",
	}
	if m.present&mptokenissuanceBitIssuer != 0 {
		out["Issuer"] = m.Issuer
	}
	if m.present&mptokenissuanceBitSequence != 0 {
		out["Sequence"] = m.Sequence
	}
	if m.present&mptokenissuanceBitTransferFee != 0 {
		out["TransferFee"] = m.TransferFee
	}
	if m.present&mptokenissuanceBitOwnerNode != 0 {
		out["OwnerNode"] = m.OwnerNode
	}
	if m.present&mptokenissuanceBitAssetScale != 0 {
		out["AssetScale"] = m.AssetScale
	}
	if m.present&mptokenissuanceBitMaximumAmount != 0 {
		out["MaximumAmount"] = m.MaximumAmount
	}
	if m.present&mptokenissuanceBitOutstandingAmount != 0 {
		out["OutstandingAmount"] = m.OutstandingAmount
	}
	if m.present&mptokenissuanceBitLockedAmount != 0 {
		out["LockedAmount"] = m.LockedAmount
	}
	if m.present&mptokenissuanceBitMPTokenMetadata != 0 {
		out["MPTokenMetadata"] = m.MPTokenMetadata
	}
	if m.present&mptokenissuanceBitDomainID != 0 {
		out["DomainID"] = m.DomainID
	}
	if m.present&mptokenissuanceBitImmutableFlags != 0 {
		out["ImmutableFlags"] = m.ImmutableFlags
	}
	if m.present&mptokenissuanceBitReferenceHolding != 0 {
		out["ReferenceHolding"] = m.ReferenceHolding
	}
	if m.present&mptokenissuanceBitFlags != 0 {
		out["Flags"] = m.Flags
	}
	if m.present&mptokenissuanceBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = m.PreviousTxnID
	}
	if m.present&mptokenissuanceBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = m.PreviousTxnLgrSeq
	}
	if m.present&mptokenissuanceBitSponsor != 0 {
		out["Sponsor"] = m.Sponsor
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Legacy decode
// aliases and non-canonical input ordering are emitted in canonical form.
func (m *MPTokenIssuance) Encode() ([]byte, error) {
	if err := m.validateRequired(); err != nil {
		return nil, err
	}
	out := m.ToMap()
	if m.present&mptokenissuanceBitPreviousTxnID == 0 {
		out["PreviousTxnID"] = "0000000000000000000000000000000000000000000000000000000000000000"
	}
	if m.present&mptokenissuanceBitPreviousTxnLgrSeq == 0 {
		out["PreviousTxnLgrSeq"] = uint32(0)
	}
	return binarycodec.EncodeBytes(out)
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (m *MPTokenIssuance) Hash(index [32]byte) ([32]byte, error) {
	data, err := m.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode()
	return sha512half.Sum(prefix[:], data, index[:]), nil
}
