// Code generated by entrygen; DO NOT EDIT.
//
// Source: ledger/entry/schema/spec.go
// Regenerate: go generate ./ledger/entry/...

package entry

import (
	"errors"
	"fmt"

	"github.com/LeJamon/go-xrpl/codec/binarycodec"
	"github.com/LeJamon/go-xrpl/crypto/sha512half"
	"github.com/LeJamon/go-xrpl/protocol"
)

// NFTokenOffer is the typed representation of a NFTokenOffer ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every canonical field declared in the spec — including those excluded from
// metadata (sMD_Never) — so decoding and re-encoding does not drop them.
type NFTokenOffer struct {
	present           uint64
	decoded           bool
	dirty             bool
	Owner             string // AccountID (base58)
	NFTokenID         string // Hash256 (uppercase hex)
	Amount            any    // Amount (XRP string | IOU map)
	OwnerNode         string // UInt64 (lowercase hex, no leading zeros)
	NFTokenOfferNode  string // UInt64 (lowercase hex, no leading zeros)
	Destination       string // AccountID (base58)
	Expiration        uint32
	Flags             uint32
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
	Sponsor           string // AccountID (base58)
}

// Type returns the concrete ledger-entry type.
func (*NFTokenOffer) Type() Type {
	return Type(55)
}

const (
	nftokenofferBitOwner uint64 = 1 << iota
	nftokenofferBitNFTokenID
	nftokenofferBitAmount
	nftokenofferBitOwnerNode
	nftokenofferBitNFTokenOfferNode
	nftokenofferBitDestination
	nftokenofferBitExpiration
	nftokenofferBitFlags
	nftokenofferBitPreviousTxnID
	nftokenofferBitPreviousTxnLgrSeq
	nftokenofferBitSponsor
)

// SetOwner assigns Owner and updates its serialized presence.
func (n *NFTokenOffer) SetOwner(value string) {
	n.Owner = value
	n.dirty = true
	n.present |= nftokenofferBitOwner
}

// SetNFTokenID assigns NFTokenID and updates its serialized presence.
func (n *NFTokenOffer) SetNFTokenID(value string) {
	n.NFTokenID = value
	n.dirty = true
	n.present |= nftokenofferBitNFTokenID
}

// SetAmount assigns Amount and updates its serialized presence.
func (n *NFTokenOffer) SetAmount(value any) {
	n.Amount = value
	n.dirty = true
	n.present |= nftokenofferBitAmount
}

// SetOwnerNode assigns OwnerNode and updates its serialized presence.
func (n *NFTokenOffer) SetOwnerNode(value string) {
	n.OwnerNode = value
	n.dirty = true
	n.present |= nftokenofferBitOwnerNode
}

// SetNFTokenOfferNode assigns NFTokenOfferNode and updates its serialized presence.
func (n *NFTokenOffer) SetNFTokenOfferNode(value string) {
	n.NFTokenOfferNode = value
	n.dirty = true
	n.present |= nftokenofferBitNFTokenOfferNode
}

// SetDestination assigns Destination and updates its serialized presence.
func (n *NFTokenOffer) SetDestination(value string) {
	n.Destination = value
	n.dirty = true
	n.present |= nftokenofferBitDestination
}

// SetExpiration assigns Expiration and updates its serialized presence.
func (n *NFTokenOffer) SetExpiration(value uint32) {
	n.Expiration = value
	n.dirty = true
	n.present |= nftokenofferBitExpiration
}

// SetFlags assigns Flags and updates its serialized presence.
func (n *NFTokenOffer) SetFlags(value uint32) {
	n.Flags = value
	n.dirty = true
	n.present |= nftokenofferBitFlags
}

// SetPreviousTxnID assigns PreviousTxnID and updates its serialized presence.
func (n *NFTokenOffer) SetPreviousTxnID(value string) {
	n.PreviousTxnID = value
	n.dirty = true
	n.present |= nftokenofferBitPreviousTxnID
}

// SetPreviousTxnLgrSeq assigns PreviousTxnLgrSeq and updates its serialized presence.
func (n *NFTokenOffer) SetPreviousTxnLgrSeq(value uint32) {
	n.PreviousTxnLgrSeq = value
	n.dirty = true
	n.present |= nftokenofferBitPreviousTxnLgrSeq
}

// SetSponsor assigns Sponsor and updates its serialized presence.
func (n *NFTokenOffer) SetSponsor(value string) {
	n.Sponsor = value
	n.dirty = true
	n.present |= nftokenofferBitSponsor
}

// HasOwner reports whether Owner is present.
func (n *NFTokenOffer) HasOwner() bool {
	return n != nil && n.present&nftokenofferBitOwner != 0
}

// GetOwner returns the 20-byte AccountID.
func (n *NFTokenOffer) GetOwner() ([20]byte, error) {
	if n == nil {
		return [20]byte{}, nil
	}
	return accountIDValueFromString(n.Owner, "NFTokenOffer.Owner")
}

// SetOwnerValue assigns a 20-byte AccountID.
func (n *NFTokenOffer) SetOwnerValue(value [20]byte) error {
	address, err := accountIDValueToString(value)
	if err != nil {
		return err
	}
	n.SetOwner(address)
	return nil
}

// HasNFTokenID reports whether NFTokenID is present.
func (n *NFTokenOffer) HasNFTokenID() bool {
	return n != nil && n.present&nftokenofferBitNFTokenID != 0
}

// GetNFTokenID returns the typed 256-bit hash.
func (n *NFTokenOffer) GetNFTokenID() ([32]byte, error) {
	var result [32]byte
	if n == nil {
		return result, nil
	}
	raw, err := hashValueFromString(n.NFTokenID, "NFTokenOffer.NFTokenID", 32)
	copy(result[:], raw)
	return result, err
}

// SetNFTokenIDValue assigns a typed 256-bit hash.
func (n *NFTokenOffer) SetNFTokenIDValue(value [32]byte) {
	n.SetNFTokenID(hashValueToString(value[:]))
}

// HasAmount reports whether Amount is present.
func (n *NFTokenOffer) HasAmount() bool {
	return n != nil && n.present&nftokenofferBitAmount != 0
}

// GetAmount returns the typed Amount value.
func (n *NFTokenOffer) GetAmount() (AmountValue, error) {
	if n == nil {
		return AmountValue{}, nil
	}
	return amountValueFromAny(n.Amount, "NFTokenOffer.Amount", false)
}

// SetAmountValue assigns a typed Amount value.
func (n *NFTokenOffer) SetAmountValue(value AmountValue) error {
	encoded, err := amountValueToAny(value, "NFTokenOffer.Amount", false)
	if err != nil {
		return err
	}
	n.SetAmount(encoded)
	return nil
}

// HasOwnerNode reports whether OwnerNode is present.
func (n *NFTokenOffer) HasOwnerNode() bool {
	return n != nil && n.present&nftokenofferBitOwnerNode != 0
}

// GetOwnerNode returns the typed UInt64 value.
func (n *NFTokenOffer) GetOwnerNode() (uint64, error) {
	if n == nil {
		return 0, nil
	}
	return uint64ValueFromString(n.OwnerNode, "NFTokenOffer.OwnerNode", false)
}

// SetOwnerNodeValue assigns a typed UInt64 value.
func (n *NFTokenOffer) SetOwnerNodeValue(value uint64) {
	n.SetOwnerNode(uint64ValueToString(value, false))
}

// HasNFTokenOfferNode reports whether NFTokenOfferNode is present.
func (n *NFTokenOffer) HasNFTokenOfferNode() bool {
	return n != nil && n.present&nftokenofferBitNFTokenOfferNode != 0
}

// GetNFTokenOfferNode returns the typed UInt64 value.
func (n *NFTokenOffer) GetNFTokenOfferNode() (uint64, error) {
	if n == nil {
		return 0, nil
	}
	return uint64ValueFromString(n.NFTokenOfferNode, "NFTokenOffer.NFTokenOfferNode", false)
}

// SetNFTokenOfferNodeValue assigns a typed UInt64 value.
func (n *NFTokenOffer) SetNFTokenOfferNodeValue(value uint64) {
	n.SetNFTokenOfferNode(uint64ValueToString(value, false))
}

// HasDestination reports whether Destination is present.
func (n *NFTokenOffer) HasDestination() bool {
	return n != nil && n.present&nftokenofferBitDestination != 0
}

// ClearDestination removes Destination from the serialized entry.
func (n *NFTokenOffer) ClearDestination() {
	if n == nil {
		return
	}
	n.Destination = ""
	n.present &^= nftokenofferBitDestination
	n.dirty = true
}

// GetDestination returns the 20-byte AccountID.
func (n *NFTokenOffer) GetDestination() ([20]byte, error) {
	if n == nil {
		return [20]byte{}, nil
	}
	return accountIDValueFromString(n.Destination, "NFTokenOffer.Destination")
}

// SetDestinationValue assigns a 20-byte AccountID.
func (n *NFTokenOffer) SetDestinationValue(value [20]byte) error {
	address, err := accountIDValueToString(value)
	if err != nil {
		return err
	}
	n.SetDestination(address)
	return nil
}

// HasExpiration reports whether Expiration is present.
func (n *NFTokenOffer) HasExpiration() bool {
	return n != nil && n.present&nftokenofferBitExpiration != 0
}

// ClearExpiration removes Expiration from the serialized entry.
func (n *NFTokenOffer) ClearExpiration() {
	if n == nil {
		return
	}
	n.Expiration = 0
	n.present &^= nftokenofferBitExpiration
	n.dirty = true
}

// GetExpiration returns the typed UInt32 value.
func (n *NFTokenOffer) GetExpiration() (uint32, error) {
	if n == nil {
		return 0, nil
	}
	return n.Expiration, nil
}

// SetExpirationValue assigns a typed UInt32 value.
func (n *NFTokenOffer) SetExpirationValue(value uint32) {
	n.SetExpiration(value)
}

// HasFlags reports whether Flags is present.
func (n *NFTokenOffer) HasFlags() bool {
	return n != nil && n.present&nftokenofferBitFlags != 0
}

// GetFlags returns the typed UInt32 value.
func (n *NFTokenOffer) GetFlags() (uint32, error) {
	if n == nil {
		return 0, nil
	}
	return n.Flags, nil
}

// SetFlagsValue assigns a typed UInt32 value.
func (n *NFTokenOffer) SetFlagsValue(value uint32) {
	n.SetFlags(value)
}

// HasPreviousTxnID reports whether PreviousTxnID is present.
func (n *NFTokenOffer) HasPreviousTxnID() bool {
	return n != nil && n.present&nftokenofferBitPreviousTxnID != 0
}

// GetPreviousTxnID returns the typed 256-bit hash.
func (n *NFTokenOffer) GetPreviousTxnID() ([32]byte, error) {
	var result [32]byte
	if n == nil {
		return result, nil
	}
	raw, err := hashValueFromString(n.PreviousTxnID, "NFTokenOffer.PreviousTxnID", 32)
	copy(result[:], raw)
	return result, err
}

// SetPreviousTxnIDValue assigns a typed 256-bit hash.
func (n *NFTokenOffer) SetPreviousTxnIDValue(value [32]byte) {
	n.SetPreviousTxnID(hashValueToString(value[:]))
}

// HasPreviousTxnLgrSeq reports whether PreviousTxnLgrSeq is present.
func (n *NFTokenOffer) HasPreviousTxnLgrSeq() bool {
	return n != nil && n.present&nftokenofferBitPreviousTxnLgrSeq != 0
}

// GetPreviousTxnLgrSeq returns the typed UInt32 value.
func (n *NFTokenOffer) GetPreviousTxnLgrSeq() (uint32, error) {
	if n == nil {
		return 0, nil
	}
	return n.PreviousTxnLgrSeq, nil
}

// SetPreviousTxnLgrSeqValue assigns a typed UInt32 value.
func (n *NFTokenOffer) SetPreviousTxnLgrSeqValue(value uint32) {
	n.SetPreviousTxnLgrSeq(value)
}

// HasSponsor reports whether Sponsor is present.
func (n *NFTokenOffer) HasSponsor() bool {
	return n != nil && n.present&nftokenofferBitSponsor != 0
}

// ClearSponsor removes Sponsor from the serialized entry.
func (n *NFTokenOffer) ClearSponsor() {
	if n == nil {
		return
	}
	n.Sponsor = ""
	n.present &^= nftokenofferBitSponsor
	n.dirty = true
}

// GetSponsor returns the 20-byte AccountID.
func (n *NFTokenOffer) GetSponsor() ([20]byte, error) {
	if n == nil {
		return [20]byte{}, nil
	}
	return accountIDValueFromString(n.Sponsor, "NFTokenOffer.Sponsor")
}

// SetSponsorValue assigns a 20-byte AccountID.
func (n *NFTokenOffer) SetSponsorValue(value [20]byte) error {
	address, err := accountIDValueToString(value)
	if err != nil {
		return err
	}
	n.SetSponsor(address)
	return nil
}

func (n *NFTokenOffer) validateRequired() error {
	if n.decoded && !n.dirty {
		return nil
	}
	if n.present&nftokenofferBitOwner == 0 {
		return errors.New("ledgerfields: NFTokenOffer: required field Owner is not set")
	}
	if n.present&nftokenofferBitNFTokenID == 0 {
		return errors.New("ledgerfields: NFTokenOffer: required field NFTokenID is not set")
	}
	if n.present&nftokenofferBitAmount == 0 {
		return errors.New("ledgerfields: NFTokenOffer: required field Amount is not set")
	}
	if n.present&nftokenofferBitOwnerNode == 0 {
		return errors.New("ledgerfields: NFTokenOffer: required field OwnerNode is not set")
	}
	if n.present&nftokenofferBitNFTokenOfferNode == 0 {
		return errors.New("ledgerfields: NFTokenOffer: required field NFTokenOfferNode is not set")
	}
	if n.present&nftokenofferBitFlags == 0 {
		return errors.New("ledgerfields: NFTokenOffer: required field Flags is not set")
	}
	return nil
}

func (n *NFTokenOffer) validateDecoded() error {
	if n.present&nftokenofferBitOwner == 0 {
		return errors.New("ledgerfields: NFTokenOffer: required field Owner is missing")
	}
	if n.present&nftokenofferBitNFTokenID == 0 {
		return errors.New("ledgerfields: NFTokenOffer: required field NFTokenID is missing")
	}
	if n.present&nftokenofferBitAmount == 0 {
		return errors.New("ledgerfields: NFTokenOffer: required field Amount is missing")
	}
	if n.present&nftokenofferBitOwnerNode == 0 {
		return errors.New("ledgerfields: NFTokenOffer: required field OwnerNode is missing")
	}
	if n.present&nftokenofferBitNFTokenOfferNode == 0 {
		return errors.New("ledgerfields: NFTokenOffer: required field NFTokenOfferNode is missing")
	}
	if n.present&nftokenofferBitFlags == 0 {
		return errors.New("ledgerfields: NFTokenOffer: required field Flags is missing")
	}
	if n.present&nftokenofferBitPreviousTxnID == 0 {
		return errors.New("ledgerfields: NFTokenOffer: required field PreviousTxnID is missing")
	}
	if n.present&nftokenofferBitPreviousTxnLgrSeq == 0 {
		return errors.New("ledgerfields: NFTokenOffer: required field PreviousTxnLgrSeq is missing")
	}
	return nil
}

// Decode populates the struct from binary ledger-entry data via a streaming
// reader and enforces the current rippled ledger template.
func (n *NFTokenOffer) Decode(data []byte) error {
	return n.decode(data, false)
}

func (n *NFTokenOffer) decodeLegacy(data []byte) error {
	return n.decode(data, true)
}

func (n *NFTokenOffer) decode(data []byte, legacy bool) error {
	*n = NFTokenOffer{}
	sr := newStreamReader(data)
	seenFields := make(map[[2]int]struct{})
	sawLedgerEntryType := false
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		fieldID := [2]int{typeCode, fieldCode}
		if _, exists := seenFields[fieldID]; exists {
			return fmt.Errorf("ledgerfields: NFTokenOffer: duplicate field type=%d field=%d", typeCode, fieldCode)
		}
		seenFields[fieldID] = struct{}{}
		if !legacy {
			switch {
			case typeCode == 8 && fieldCode == 1:
				return fmt.Errorf("ledgerfields: NFTokenOffer: field type=%d field=%d is not allowed", typeCode, fieldCode)
			}
		}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				if val != 55 {
					return fmt.Errorf("ledgerfields: NFTokenOffer: LedgerEntryType is %d, want 55", val)
				}
				sawLedgerEntryType = true
			default:
				return newErrUnknownField("NFTokenOffer", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				n.Flags = val
				n.present |= nftokenofferBitFlags
			case 5:
				n.PreviousTxnLgrSeq = val
				n.present |= nftokenofferBitPreviousTxnLgrSeq
			case 10:
				n.Expiration = val
				n.present |= nftokenofferBitExpiration
			default:
				return newErrUnknownField("NFTokenOffer", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 4:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				n.OwnerNode = val
				n.present |= nftokenofferBitOwnerNode
			case 12:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				n.NFTokenOfferNode = val
				n.present |= nftokenofferBitNFTokenOfferNode
			default:
				return newErrUnknownField("NFTokenOffer", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				n.PreviousTxnID = val
				n.present |= nftokenofferBitPreviousTxnID
			case 10:
				n.NFTokenID = val
				n.present |= nftokenofferBitNFTokenID
			default:
				return newErrUnknownField("NFTokenOffer", typeCode, fieldCode)
			}
		case 6: // Amount
			val, err := sr.readAmountAny()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				n.Amount = val
				n.present |= nftokenofferBitAmount
			default:
				return newErrUnknownField("NFTokenOffer", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				n.Owner = val
				n.present |= nftokenofferBitOwner
			case 2:
				n.Owner = val
				n.present |= nftokenofferBitOwner
			case 3:
				n.Destination = val
				n.present |= nftokenofferBitDestination
			case 27:
				n.Sponsor = val
				n.present |= nftokenofferBitSponsor
			default:
				return newErrUnknownField("NFTokenOffer", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("NFTokenOffer", typeCode, fieldCode)
		}
	}
	if !sawLedgerEntryType {
		return errors.New("ledgerfields: NFTokenOffer: missing LedgerEntryType")
	}
	n.decoded = true
	if !legacy {
		return n.validateDecoded()
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (n *NFTokenOffer) emitAll(out map[string]any, skipDefault bool) {
	if n.present&nftokenofferBitOwner != 0 && !(skipDefault && n.Owner == "") {
		out["Owner"] = n.Owner
	}
	if n.present&nftokenofferBitNFTokenID != 0 && !(skipDefault && isZeroHexString(n.NFTokenID)) {
		out["NFTokenID"] = n.NFTokenID
	}
	if n.present&nftokenofferBitAmount != 0 && !(skipDefault && amountIsDefault(n.Amount)) {
		out["Amount"] = n.Amount
	}
	if n.present&nftokenofferBitOwnerNode != 0 && !(skipDefault && isZeroHexString(n.OwnerNode)) {
		out["OwnerNode"] = n.OwnerNode
	}
	if n.present&nftokenofferBitNFTokenOfferNode != 0 && !(skipDefault && isZeroHexString(n.NFTokenOfferNode)) {
		out["NFTokenOfferNode"] = n.NFTokenOfferNode
	}
	if n.present&nftokenofferBitDestination != 0 && !(skipDefault && n.Destination == "") {
		out["Destination"] = n.Destination
	}
	if n.present&nftokenofferBitExpiration != 0 && !(skipDefault && n.Expiration == 0) {
		out["Expiration"] = n.Expiration
	}
	if n.present&nftokenofferBitFlags != 0 && !(skipDefault && n.Flags == 0) {
		out["Flags"] = n.Flags
	}
	if n.present&nftokenofferBitSponsor != 0 && !(skipDefault && n.Sponsor == "") {
		out["Sponsor"] = n.Sponsor
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (n *NFTokenOffer) EmitNewFields(out map[string]any) {
	n.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (n *NFTokenOffer) EmitFinalFields(out map[string]any) {
	n.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (n *NFTokenOffer) EmitPreviousFields(prev Entry, out map[string]any) {
	prv, ok := prev.(*NFTokenOffer)
	if !ok || prv == nil {
		return
	}
	emitIfChangedString(out, "Owner", prv.Owner, n.Owner, prv.present&nftokenofferBitOwner, n.present&nftokenofferBitOwner)
	emitIfChangedString(out, "NFTokenID", prv.NFTokenID, n.NFTokenID, prv.present&nftokenofferBitNFTokenID, n.present&nftokenofferBitNFTokenID)
	emitIfChangedAmount(out, "Amount", prv.Amount, n.Amount, prv.present&nftokenofferBitAmount, n.present&nftokenofferBitAmount)
	emitIfChangedString(out, "OwnerNode", prv.OwnerNode, n.OwnerNode, prv.present&nftokenofferBitOwnerNode, n.present&nftokenofferBitOwnerNode)
	emitIfChangedString(out, "NFTokenOfferNode", prv.NFTokenOfferNode, n.NFTokenOfferNode, prv.present&nftokenofferBitNFTokenOfferNode, n.present&nftokenofferBitNFTokenOfferNode)
	emitIfChangedString(out, "Destination", prv.Destination, n.Destination, prv.present&nftokenofferBitDestination, n.present&nftokenofferBitDestination)
	emitIfChangedUint32(out, "Expiration", prv.Expiration, n.Expiration, prv.present&nftokenofferBitExpiration, n.present&nftokenofferBitExpiration)
	emitIfChangedUint32(out, "Flags", prv.Flags, n.Flags, prv.present&nftokenofferBitFlags, n.present&nftokenofferBitFlags)
	emitIfChangedString(out, "Sponsor", prv.Sponsor, n.Sponsor, prv.present&nftokenofferBitSponsor, n.present&nftokenofferBitSponsor)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (n *NFTokenOffer) EmitChangeOrigFields(out map[string]any) {
	if n.present&nftokenofferBitOwner != 0 {
		out["Owner"] = n.Owner
	}
	if n.present&nftokenofferBitNFTokenID != 0 {
		out["NFTokenID"] = n.NFTokenID
	}
	if n.present&nftokenofferBitAmount != 0 {
		out["Amount"] = n.Amount
	}
	if n.present&nftokenofferBitOwnerNode != 0 {
		out["OwnerNode"] = n.OwnerNode
	}
	if n.present&nftokenofferBitNFTokenOfferNode != 0 {
		out["NFTokenOfferNode"] = n.NFTokenOfferNode
	}
	if n.present&nftokenofferBitDestination != 0 {
		out["Destination"] = n.Destination
	}
	if n.present&nftokenofferBitExpiration != 0 {
		out["Expiration"] = n.Expiration
	}
	if n.present&nftokenofferBitFlags != 0 {
		out["Flags"] = n.Flags
	}
	if n.present&nftokenofferBitSponsor != 0 {
		out["Sponsor"] = n.Sponsor
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (n *NFTokenOffer) EmitDeleteFinalFields(out map[string]any) {
	n.emitAll(out, false)
	if n.present&nftokenofferBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = n.PreviousTxnID
	}
	if n.present&nftokenofferBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = n.PreviousTxnLgrSeq
	}
}

func (n *NFTokenOffer) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	n.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (n *NFTokenOffer) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if n.present&nftokenofferBitPreviousTxnID != 0 {
		id = n.PreviousTxnID
	}
	if n.present&nftokenofferBitPreviousTxnLgrSeq != 0 {
		seq = n.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (n *NFTokenOffer) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "NFTokenOffer",
	}
	if n.present&nftokenofferBitOwner != 0 {
		out["Owner"] = n.Owner
	}
	if n.present&nftokenofferBitNFTokenID != 0 {
		out["NFTokenID"] = n.NFTokenID
	}
	if n.present&nftokenofferBitAmount != 0 {
		out["Amount"] = n.Amount
	}
	if n.present&nftokenofferBitOwnerNode != 0 {
		out["OwnerNode"] = n.OwnerNode
	}
	if n.present&nftokenofferBitNFTokenOfferNode != 0 {
		out["NFTokenOfferNode"] = n.NFTokenOfferNode
	}
	if n.present&nftokenofferBitDestination != 0 {
		out["Destination"] = n.Destination
	}
	if n.present&nftokenofferBitExpiration != 0 {
		out["Expiration"] = n.Expiration
	}
	if n.present&nftokenofferBitFlags != 0 {
		out["Flags"] = n.Flags
	}
	if n.present&nftokenofferBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = n.PreviousTxnID
	}
	if n.present&nftokenofferBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = n.PreviousTxnLgrSeq
	}
	if n.present&nftokenofferBitSponsor != 0 {
		out["Sponsor"] = n.Sponsor
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Legacy decode
// aliases and non-canonical input ordering are emitted in canonical form.
func (n *NFTokenOffer) Encode() ([]byte, error) {
	if err := n.validateRequired(); err != nil {
		return nil, err
	}
	out := n.ToMap()
	if n.present&nftokenofferBitPreviousTxnID == 0 {
		out["PreviousTxnID"] = "0000000000000000000000000000000000000000000000000000000000000000"
	}
	if n.present&nftokenofferBitPreviousTxnLgrSeq == 0 {
		out["PreviousTxnLgrSeq"] = uint32(0)
	}
	return binarycodec.EncodeBytes(out)
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (n *NFTokenOffer) Hash(index [32]byte) ([32]byte, error) {
	data, err := n.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode()
	return sha512half.Sum(prefix[:], data, index[:]), nil
}
