// Code generated by entrygen; DO NOT EDIT.
//
// Source: ledger/entry/schema/spec.go
// Regenerate: go generate ./ledger/entry/...

package entry

import (
	"errors"
	"fmt"

	"github.com/LeJamon/go-xrpl/codec/binarycodec"
	"github.com/LeJamon/go-xrpl/crypto/sha512half"
	"github.com/LeJamon/go-xrpl/protocol"
)

// PermissionedDomain is the typed representation of a PermissionedDomain ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every canonical field declared in the spec — including those excluded from
// metadata (sMD_Never) — so decoding and re-encoding does not drop them.
type PermissionedDomain struct {
	present             uint64
	decoded             bool
	dirty               bool
	Owner               string // AccountID (base58)
	Sequence            uint32
	AcceptedCredentials []any
	OwnerNode           string // UInt64 (lowercase hex, no leading zeros)
	Flags               uint32
	PreviousTxnID       string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq   uint32
}

// Type returns the concrete ledger-entry type.
func (*PermissionedDomain) Type() Type {
	return Type(130)
}

const (
	permissioneddomainBitOwner uint64 = 1 << iota
	permissioneddomainBitSequence
	permissioneddomainBitAcceptedCredentials
	permissioneddomainBitOwnerNode
	permissioneddomainBitFlags
	permissioneddomainBitPreviousTxnID
	permissioneddomainBitPreviousTxnLgrSeq
)

// SetOwner assigns Owner and updates its serialized presence.
func (p *PermissionedDomain) SetOwner(value string) {
	p.Owner = value
	p.dirty = true
	p.present |= permissioneddomainBitOwner
}

// SetSequence assigns Sequence and updates its serialized presence.
func (p *PermissionedDomain) SetSequence(value uint32) {
	p.Sequence = value
	p.dirty = true
	p.present |= permissioneddomainBitSequence
}

// SetAcceptedCredentials assigns AcceptedCredentials and updates its serialized presence.
func (p *PermissionedDomain) SetAcceptedCredentials(value []any) {
	p.AcceptedCredentials = value
	p.dirty = true
	p.present |= permissioneddomainBitAcceptedCredentials
}

// SetOwnerNode assigns OwnerNode and updates its serialized presence.
func (p *PermissionedDomain) SetOwnerNode(value string) {
	p.OwnerNode = value
	p.dirty = true
	p.present |= permissioneddomainBitOwnerNode
}

// SetFlags assigns Flags and updates its serialized presence.
func (p *PermissionedDomain) SetFlags(value uint32) {
	p.Flags = value
	p.dirty = true
	p.present |= permissioneddomainBitFlags
}

// SetPreviousTxnID assigns PreviousTxnID and updates its serialized presence.
func (p *PermissionedDomain) SetPreviousTxnID(value string) {
	p.PreviousTxnID = value
	p.dirty = true
	p.present |= permissioneddomainBitPreviousTxnID
}

// SetPreviousTxnLgrSeq assigns PreviousTxnLgrSeq and updates its serialized presence.
func (p *PermissionedDomain) SetPreviousTxnLgrSeq(value uint32) {
	p.PreviousTxnLgrSeq = value
	p.dirty = true
	p.present |= permissioneddomainBitPreviousTxnLgrSeq
}

func (p *PermissionedDomain) validateRequired() error {
	if p.decoded && !p.dirty {
		return nil
	}
	if p.present&permissioneddomainBitOwner == 0 {
		return errors.New("ledgerfields: PermissionedDomain: required field Owner is not set")
	}
	if p.present&permissioneddomainBitSequence == 0 {
		return errors.New("ledgerfields: PermissionedDomain: required field Sequence is not set")
	}
	if p.present&permissioneddomainBitAcceptedCredentials == 0 {
		return errors.New("ledgerfields: PermissionedDomain: required field AcceptedCredentials is not set")
	}
	if p.present&permissioneddomainBitOwnerNode == 0 {
		return errors.New("ledgerfields: PermissionedDomain: required field OwnerNode is not set")
	}
	if p.present&permissioneddomainBitFlags == 0 {
		return errors.New("ledgerfields: PermissionedDomain: required field Flags is not set")
	}
	return nil
}

func (p *PermissionedDomain) validateDecoded() error {
	if p.present&permissioneddomainBitOwner == 0 {
		return errors.New("ledgerfields: PermissionedDomain: required field Owner is missing")
	}
	if p.present&permissioneddomainBitSequence == 0 {
		return errors.New("ledgerfields: PermissionedDomain: required field Sequence is missing")
	}
	if p.present&permissioneddomainBitAcceptedCredentials == 0 {
		return errors.New("ledgerfields: PermissionedDomain: required field AcceptedCredentials is missing")
	}
	if p.present&permissioneddomainBitOwnerNode == 0 {
		return errors.New("ledgerfields: PermissionedDomain: required field OwnerNode is missing")
	}
	if p.present&permissioneddomainBitFlags == 0 {
		return errors.New("ledgerfields: PermissionedDomain: required field Flags is missing")
	}
	if p.present&permissioneddomainBitPreviousTxnID == 0 {
		return errors.New("ledgerfields: PermissionedDomain: required field PreviousTxnID is missing")
	}
	if p.present&permissioneddomainBitPreviousTxnLgrSeq == 0 {
		return errors.New("ledgerfields: PermissionedDomain: required field PreviousTxnLgrSeq is missing")
	}
	return nil
}

// Decode populates the struct from binary ledger-entry data via a streaming
// reader and enforces the current rippled ledger template.
func (p *PermissionedDomain) Decode(data []byte) error {
	return p.decode(data, false)
}

func (p *PermissionedDomain) decodeLegacy(data []byte) error {
	return p.decode(data, true)
}

func (p *PermissionedDomain) decode(data []byte, legacy bool) error {
	*p = PermissionedDomain{}
	sr := newStreamReader(data)
	seenFields := make(map[[2]int]struct{})
	sawLedgerEntryType := false
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		fieldID := [2]int{typeCode, fieldCode}
		if _, exists := seenFields[fieldID]; exists {
			return fmt.Errorf("ledgerfields: PermissionedDomain: duplicate field type=%d field=%d", typeCode, fieldCode)
		}
		seenFields[fieldID] = struct{}{}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				if val != 130 {
					return fmt.Errorf("ledgerfields: PermissionedDomain: LedgerEntryType is %d, want 130", val)
				}
				sawLedgerEntryType = true
			default:
				return newErrUnknownField("PermissionedDomain", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				p.Flags = val
				p.present |= permissioneddomainBitFlags
			case 4:
				p.Sequence = val
				p.present |= permissioneddomainBitSequence
			case 5:
				p.PreviousTxnLgrSeq = val
				p.present |= permissioneddomainBitPreviousTxnLgrSeq
			default:
				return newErrUnknownField("PermissionedDomain", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 4:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				p.OwnerNode = val
				p.present |= permissioneddomainBitOwnerNode
			default:
				return newErrUnknownField("PermissionedDomain", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				p.PreviousTxnID = val
				p.present |= permissioneddomainBitPreviousTxnID
			default:
				return newErrUnknownField("PermissionedDomain", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				p.Owner = val
				p.present |= permissioneddomainBitOwner
			default:
				return newErrUnknownField("PermissionedDomain", typeCode, fieldCode)
			}
		case 15: // STArray
			val, err := sr.readSTArray("AcceptedCredentials")
			if err != nil {
				return err
			}
			switch fieldCode {
			case 28:
				p.AcceptedCredentials = val
				p.present |= permissioneddomainBitAcceptedCredentials
			default:
				return newErrUnknownField("PermissionedDomain", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("PermissionedDomain", typeCode, fieldCode)
		}
	}
	if !sawLedgerEntryType {
		return errors.New("ledgerfields: PermissionedDomain: missing LedgerEntryType")
	}
	p.decoded = true
	if !legacy {
		return p.validateDecoded()
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (p *PermissionedDomain) emitAll(out map[string]any, skipDefault bool) {
	if p.present&permissioneddomainBitOwner != 0 && !(skipDefault && p.Owner == "") {
		out["Owner"] = p.Owner
	}
	if p.present&permissioneddomainBitSequence != 0 && !(skipDefault && p.Sequence == 0) {
		out["Sequence"] = p.Sequence
	}
	if p.present&permissioneddomainBitAcceptedCredentials != 0 && !(skipDefault && len(p.AcceptedCredentials) == 0) {
		out["AcceptedCredentials"] = p.AcceptedCredentials
	}
	if p.present&permissioneddomainBitOwnerNode != 0 && !(skipDefault && isZeroHexString(p.OwnerNode)) {
		out["OwnerNode"] = p.OwnerNode
	}
	if p.present&permissioneddomainBitFlags != 0 && !(skipDefault && p.Flags == 0) {
		out["Flags"] = p.Flags
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (p *PermissionedDomain) EmitNewFields(out map[string]any) {
	p.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (p *PermissionedDomain) EmitFinalFields(out map[string]any) {
	p.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (p *PermissionedDomain) EmitPreviousFields(prev Entry, out map[string]any) {
	prv, ok := prev.(*PermissionedDomain)
	if !ok || prv == nil {
		return
	}
	emitIfChangedString(out, "Owner", prv.Owner, p.Owner, prv.present&permissioneddomainBitOwner, p.present&permissioneddomainBitOwner)
	emitIfChangedUint32(out, "Sequence", prv.Sequence, p.Sequence, prv.present&permissioneddomainBitSequence, p.present&permissioneddomainBitSequence)
	emitIfChangedDeep(out, "AcceptedCredentials", prv.AcceptedCredentials, p.AcceptedCredentials, prv.present&permissioneddomainBitAcceptedCredentials, p.present&permissioneddomainBitAcceptedCredentials)
	emitIfChangedString(out, "OwnerNode", prv.OwnerNode, p.OwnerNode, prv.present&permissioneddomainBitOwnerNode, p.present&permissioneddomainBitOwnerNode)
	emitIfChangedUint32(out, "Flags", prv.Flags, p.Flags, prv.present&permissioneddomainBitFlags, p.present&permissioneddomainBitFlags)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (p *PermissionedDomain) EmitChangeOrigFields(out map[string]any) {
	if p.present&permissioneddomainBitOwner != 0 {
		out["Owner"] = p.Owner
	}
	if p.present&permissioneddomainBitSequence != 0 {
		out["Sequence"] = p.Sequence
	}
	if p.present&permissioneddomainBitAcceptedCredentials != 0 {
		out["AcceptedCredentials"] = p.AcceptedCredentials
	}
	if p.present&permissioneddomainBitOwnerNode != 0 {
		out["OwnerNode"] = p.OwnerNode
	}
	if p.present&permissioneddomainBitFlags != 0 {
		out["Flags"] = p.Flags
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (p *PermissionedDomain) EmitDeleteFinalFields(out map[string]any) {
	p.emitAll(out, false)
	if p.present&permissioneddomainBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = p.PreviousTxnID
	}
	if p.present&permissioneddomainBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = p.PreviousTxnLgrSeq
	}
}

func (p *PermissionedDomain) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	p.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (p *PermissionedDomain) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if p.present&permissioneddomainBitPreviousTxnID != 0 {
		id = p.PreviousTxnID
	}
	if p.present&permissioneddomainBitPreviousTxnLgrSeq != 0 {
		seq = p.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (p *PermissionedDomain) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "PermissionedDomain",
	}
	if p.present&permissioneddomainBitOwner != 0 {
		out["Owner"] = p.Owner
	}
	if p.present&permissioneddomainBitSequence != 0 {
		out["Sequence"] = p.Sequence
	}
	if p.present&permissioneddomainBitAcceptedCredentials != 0 {
		out["AcceptedCredentials"] = p.AcceptedCredentials
	}
	if p.present&permissioneddomainBitOwnerNode != 0 {
		out["OwnerNode"] = p.OwnerNode
	}
	if p.present&permissioneddomainBitFlags != 0 {
		out["Flags"] = p.Flags
	}
	if p.present&permissioneddomainBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = p.PreviousTxnID
	}
	if p.present&permissioneddomainBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = p.PreviousTxnLgrSeq
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Legacy decode
// aliases and non-canonical input ordering are emitted in canonical form.
func (p *PermissionedDomain) Encode() ([]byte, error) {
	if err := p.validateRequired(); err != nil {
		return nil, err
	}
	if p.present&permissioneddomainBitAcceptedCredentials != 0 {
		if err := validateSTArrayForEncode("AcceptedCredentials", p.AcceptedCredentials); err != nil {
			return nil, err
		}
	}
	out := p.ToMap()
	if p.present&permissioneddomainBitPreviousTxnID == 0 {
		out["PreviousTxnID"] = "0000000000000000000000000000000000000000000000000000000000000000"
	}
	if p.present&permissioneddomainBitPreviousTxnLgrSeq == 0 {
		out["PreviousTxnLgrSeq"] = uint32(0)
	}
	return binarycodec.EncodeBytes(out)
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (p *PermissionedDomain) Hash(index [32]byte) ([32]byte, error) {
	data, err := p.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode()
	return sha512half.Sum(prefix[:], data, index[:]), nil
}
