// Code generated by entrygen; DO NOT EDIT.
//
// Source: ledger/entry/schema/spec.go
// Regenerate: go generate ./ledger/entry/...

package entry

import (
	"errors"
	"fmt"

	"github.com/LeJamon/go-xrpl/codec/binarycodec"
	"github.com/LeJamon/go-xrpl/crypto/sha512half"
	"github.com/LeJamon/go-xrpl/protocol"
)

// SignerList is the typed representation of a SignerList ledger entry.
// The present bitset tracks which fields appear on the decoded blob so the
// emit methods only write entries that actually exist. The struct carries
// every canonical field declared in the spec — including those excluded from
// metadata (sMD_Never) — so decoding and re-encoding does not drop them.
type SignerList struct {
	present           uint64
	decoded           bool
	dirty             bool
	Owner             string // AccountID (base58)
	OwnerNode         string // UInt64 (lowercase hex, no leading zeros)
	SignerQuorum      uint32
	SignerEntries     []any
	SignerListID      uint32
	Flags             uint32
	PreviousTxnID     string // Hash256 (uppercase hex)
	PreviousTxnLgrSeq uint32
	Sponsor           string // AccountID (base58)
}

// Type returns the concrete ledger-entry type.
func (*SignerList) Type() Type {
	return Type(83)
}

const (
	signerlistBitOwner uint64 = 1 << iota
	signerlistBitOwnerNode
	signerlistBitSignerQuorum
	signerlistBitSignerEntries
	signerlistBitSignerListID
	signerlistBitFlags
	signerlistBitPreviousTxnID
	signerlistBitPreviousTxnLgrSeq
	signerlistBitSponsor
)

// SetOwner assigns Owner and updates its serialized presence.
func (s *SignerList) SetOwner(value string) {
	s.Owner = value
	s.dirty = true
	s.present |= signerlistBitOwner
}

// SetOwnerNode assigns OwnerNode and updates its serialized presence.
func (s *SignerList) SetOwnerNode(value string) {
	s.OwnerNode = value
	s.dirty = true
	s.present |= signerlistBitOwnerNode
}

// SetSignerQuorum assigns SignerQuorum and updates its serialized presence.
func (s *SignerList) SetSignerQuorum(value uint32) {
	s.SignerQuorum = value
	s.dirty = true
	s.present |= signerlistBitSignerQuorum
}

// SetSignerEntries assigns SignerEntries and updates its serialized presence.
func (s *SignerList) SetSignerEntries(value []any) {
	s.SignerEntries = value
	s.dirty = true
	s.present |= signerlistBitSignerEntries
}

// SetSignerListID assigns SignerListID and updates its serialized presence.
func (s *SignerList) SetSignerListID(value uint32) {
	s.SignerListID = value
	s.dirty = true
	s.present |= signerlistBitSignerListID
}

// SetFlags assigns Flags and updates its serialized presence.
func (s *SignerList) SetFlags(value uint32) {
	s.Flags = value
	s.dirty = true
	s.present |= signerlistBitFlags
}

// SetPreviousTxnID assigns PreviousTxnID and updates its serialized presence.
func (s *SignerList) SetPreviousTxnID(value string) {
	s.PreviousTxnID = value
	s.dirty = true
	s.present |= signerlistBitPreviousTxnID
}

// SetPreviousTxnLgrSeq assigns PreviousTxnLgrSeq and updates its serialized presence.
func (s *SignerList) SetPreviousTxnLgrSeq(value uint32) {
	s.PreviousTxnLgrSeq = value
	s.dirty = true
	s.present |= signerlistBitPreviousTxnLgrSeq
}

// SetSponsor assigns Sponsor and updates its serialized presence.
func (s *SignerList) SetSponsor(value string) {
	s.Sponsor = value
	s.dirty = true
	s.present |= signerlistBitSponsor
}

// HasOwner reports whether Owner is present.
func (s *SignerList) HasOwner() bool {
	return s != nil && s.present&signerlistBitOwner != 0
}

// ClearOwner removes Owner from the serialized entry.
func (s *SignerList) ClearOwner() {
	if s == nil {
		return
	}
	s.Owner = ""
	s.present &^= signerlistBitOwner
	s.dirty = true
}

// GetOwner returns the 20-byte AccountID.
func (s *SignerList) GetOwner() ([20]byte, error) {
	if s == nil {
		return [20]byte{}, nil
	}
	return accountIDValueFromString(s.Owner, "SignerList.Owner")
}

// SetOwnerValue assigns a 20-byte AccountID.
func (s *SignerList) SetOwnerValue(value [20]byte) error {
	address, err := accountIDValueToString(value)
	if err != nil {
		return err
	}
	s.SetOwner(address)
	return nil
}

// HasOwnerNode reports whether OwnerNode is present.
func (s *SignerList) HasOwnerNode() bool {
	return s != nil && s.present&signerlistBitOwnerNode != 0
}

// GetOwnerNode returns the typed UInt64 value.
func (s *SignerList) GetOwnerNode() (uint64, error) {
	if s == nil {
		return 0, nil
	}
	return uint64ValueFromString(s.OwnerNode, "SignerList.OwnerNode", false)
}

// SetOwnerNodeValue assigns a typed UInt64 value.
func (s *SignerList) SetOwnerNodeValue(value uint64) {
	s.SetOwnerNode(uint64ValueToString(value, false))
}

// HasSignerQuorum reports whether SignerQuorum is present.
func (s *SignerList) HasSignerQuorum() bool {
	return s != nil && s.present&signerlistBitSignerQuorum != 0
}

// HasSignerEntries reports whether SignerEntries is present.
func (s *SignerList) HasSignerEntries() bool {
	return s != nil && s.present&signerlistBitSignerEntries != 0
}

// HasSignerListID reports whether SignerListID is present.
func (s *SignerList) HasSignerListID() bool {
	return s != nil && s.present&signerlistBitSignerListID != 0
}

// HasFlags reports whether Flags is present.
func (s *SignerList) HasFlags() bool {
	return s != nil && s.present&signerlistBitFlags != 0
}

// HasPreviousTxnID reports whether PreviousTxnID is present.
func (s *SignerList) HasPreviousTxnID() bool {
	return s != nil && s.present&signerlistBitPreviousTxnID != 0
}

// GetPreviousTxnID returns the typed 256-bit hash.
func (s *SignerList) GetPreviousTxnID() ([32]byte, error) {
	var result [32]byte
	if s == nil {
		return result, nil
	}
	raw, err := hashValueFromString(s.PreviousTxnID, "SignerList.PreviousTxnID", 32)
	copy(result[:], raw)
	return result, err
}

// SetPreviousTxnIDValue assigns a typed 256-bit hash.
func (s *SignerList) SetPreviousTxnIDValue(value [32]byte) {
	s.SetPreviousTxnID(hashValueToString(value[:]))
}

// HasPreviousTxnLgrSeq reports whether PreviousTxnLgrSeq is present.
func (s *SignerList) HasPreviousTxnLgrSeq() bool {
	return s != nil && s.present&signerlistBitPreviousTxnLgrSeq != 0
}

// HasSponsor reports whether Sponsor is present.
func (s *SignerList) HasSponsor() bool {
	return s != nil && s.present&signerlistBitSponsor != 0
}

// ClearSponsor removes Sponsor from the serialized entry.
func (s *SignerList) ClearSponsor() {
	if s == nil {
		return
	}
	s.Sponsor = ""
	s.present &^= signerlistBitSponsor
	s.dirty = true
}

// GetSponsor returns the 20-byte AccountID.
func (s *SignerList) GetSponsor() ([20]byte, error) {
	if s == nil {
		return [20]byte{}, nil
	}
	return accountIDValueFromString(s.Sponsor, "SignerList.Sponsor")
}

// SetSponsorValue assigns a 20-byte AccountID.
func (s *SignerList) SetSponsorValue(value [20]byte) error {
	address, err := accountIDValueToString(value)
	if err != nil {
		return err
	}
	s.SetSponsor(address)
	return nil
}

func (s *SignerList) validateRequired() error {
	if s.decoded && !s.dirty {
		return nil
	}
	if s.present&signerlistBitOwnerNode == 0 {
		return errors.New("ledgerfields: SignerList: required field OwnerNode is not set")
	}
	if s.present&signerlistBitSignerQuorum == 0 {
		return errors.New("ledgerfields: SignerList: required field SignerQuorum is not set")
	}
	if s.present&signerlistBitSignerEntries == 0 {
		return errors.New("ledgerfields: SignerList: required field SignerEntries is not set")
	}
	if s.present&signerlistBitSignerListID == 0 {
		return errors.New("ledgerfields: SignerList: required field SignerListID is not set")
	}
	if s.present&signerlistBitFlags == 0 {
		return errors.New("ledgerfields: SignerList: required field Flags is not set")
	}
	return nil
}

func (s *SignerList) validateDecoded() error {
	if s.present&signerlistBitOwnerNode == 0 {
		return errors.New("ledgerfields: SignerList: required field OwnerNode is missing")
	}
	if s.present&signerlistBitSignerQuorum == 0 {
		return errors.New("ledgerfields: SignerList: required field SignerQuorum is missing")
	}
	if s.present&signerlistBitSignerEntries == 0 {
		return errors.New("ledgerfields: SignerList: required field SignerEntries is missing")
	}
	if s.present&signerlistBitSignerListID == 0 {
		return errors.New("ledgerfields: SignerList: required field SignerListID is missing")
	}
	if s.present&signerlistBitFlags == 0 {
		return errors.New("ledgerfields: SignerList: required field Flags is missing")
	}
	if s.present&signerlistBitPreviousTxnID == 0 {
		return errors.New("ledgerfields: SignerList: required field PreviousTxnID is missing")
	}
	if s.present&signerlistBitPreviousTxnLgrSeq == 0 {
		return errors.New("ledgerfields: SignerList: required field PreviousTxnLgrSeq is missing")
	}
	return nil
}

// Decode populates the struct from binary ledger-entry data via a streaming
// reader and enforces the current rippled ledger template.
func (s *SignerList) Decode(data []byte) error {
	return s.decode(data, false)
}

func (s *SignerList) decodeLegacy(data []byte) error {
	return s.decode(data, true)
}

func (s *SignerList) decode(data []byte, legacy bool) error {
	*s = SignerList{}
	sr := newStreamReader(data)
	seenFields := make(map[[2]int]struct{})
	sawLedgerEntryType := false
	for sr.hasMore() {
		typeCode, fieldCode, err := sr.readFieldHeader()
		if err != nil {
			return err
		}
		fieldID := [2]int{typeCode, fieldCode}
		if _, exists := seenFields[fieldID]; exists {
			return fmt.Errorf("ledgerfields: SignerList: duplicate field type=%d field=%d", typeCode, fieldCode)
		}
		seenFields[fieldID] = struct{}{}
		if !legacy {
			switch {
			case typeCode == 8 && fieldCode == 1:
				return fmt.Errorf("ledgerfields: SignerList: field type=%d field=%d is not allowed", typeCode, fieldCode)
			}
		}
		switch typeCode {
		case 1: // UInt16
			u16Val, err := sr.readUint16()
			if err != nil {
				return err
			}
			val := int(u16Val)
			switch fieldCode {
			case 1:
				if val != 83 {
					return fmt.Errorf("ledgerfields: SignerList: LedgerEntryType is %d, want 83", val)
				}
				sawLedgerEntryType = true
			default:
				return newErrUnknownField("SignerList", typeCode, fieldCode)
			}
		case 2: // UInt32
			val, err := sr.readUint32()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 2:
				s.Flags = val
				s.present |= signerlistBitFlags
			case 5:
				s.PreviousTxnLgrSeq = val
				s.present |= signerlistBitPreviousTxnLgrSeq
			case 35:
				s.SignerQuorum = val
				s.present |= signerlistBitSignerQuorum
			case 38:
				s.SignerListID = val
				s.present |= signerlistBitSignerListID
			default:
				return newErrUnknownField("SignerList", typeCode, fieldCode)
			}
		case 3: // UInt64
			switch fieldCode {
			case 4:
				val, err := sr.readUint64Hex()
				if err != nil {
					return err
				}
				s.OwnerNode = val
				s.present |= signerlistBitOwnerNode
			default:
				return newErrUnknownField("SignerList", typeCode, fieldCode)
			}
		case 5: // Hash256
			val, err := sr.readHash(32)
			if err != nil {
				return err
			}
			switch fieldCode {
			case 5:
				s.PreviousTxnID = val
				s.present |= signerlistBitPreviousTxnID
			default:
				return newErrUnknownField("SignerList", typeCode, fieldCode)
			}
		case 8: // AccountID
			val, err := sr.readAccountID()
			if err != nil {
				return err
			}
			switch fieldCode {
			case 1:
				_ = val // Account decoded for tolerance only; discard
			case 2:
				s.Owner = val
				s.present |= signerlistBitOwner
			case 27:
				s.Sponsor = val
				s.present |= signerlistBitSponsor
			default:
				return newErrUnknownField("SignerList", typeCode, fieldCode)
			}
		case 15: // STArray
			val, err := sr.readSTArray("SignerEntries")
			if err != nil {
				return err
			}
			switch fieldCode {
			case 4:
				s.SignerEntries = val
				s.present |= signerlistBitSignerEntries
			default:
				return newErrUnknownField("SignerList", typeCode, fieldCode)
			}
		default:
			return newErrUnknownField("SignerList", typeCode, fieldCode)
		}
	}
	if !sawLedgerEntryType {
		return errors.New("ledgerfields: SignerList: missing LedgerEntryType")
	}
	s.decoded = true
	if !legacy {
		return s.validateDecoded()
	}
	return nil
}

// emitAll writes every present default-meta field. skipDefault filters the
// "zero" value for CreatedNode.NewFields to match rippled, which omits
// defaulted fields from NewFields.
func (s *SignerList) emitAll(out map[string]any, skipDefault bool) {
	if s.present&signerlistBitOwner != 0 && !(skipDefault && s.Owner == "") {
		out["Owner"] = s.Owner
	}
	if s.present&signerlistBitOwnerNode != 0 && !(skipDefault && isZeroHexString(s.OwnerNode)) {
		out["OwnerNode"] = s.OwnerNode
	}
	if s.present&signerlistBitSignerQuorum != 0 && !(skipDefault && s.SignerQuorum == 0) {
		out["SignerQuorum"] = s.SignerQuorum
	}
	if s.present&signerlistBitSignerEntries != 0 && !(skipDefault && len(s.SignerEntries) == 0) {
		out["SignerEntries"] = s.SignerEntries
	}
	if s.present&signerlistBitSignerListID != 0 && !(skipDefault && s.SignerListID == 0) {
		out["SignerListID"] = s.SignerListID
	}
	if s.present&signerlistBitFlags != 0 && !(skipDefault && s.Flags == 0) {
		out["Flags"] = s.Flags
	}
	if s.present&signerlistBitSponsor != 0 && !(skipDefault && s.Sponsor == "") {
		out["Sponsor"] = s.Sponsor
	}
}

// EmitNewFields emits fields for a CreatedNode (sMD_Create | sMD_Always),
// filtering out default values to match rippled.
func (s *SignerList) EmitNewFields(out map[string]any) {
	s.emitAll(out, true)
}

// EmitFinalFields emits fields for ModifiedNode.FinalFields (sMD_Always |
// sMD_ChangeNew), no default-value filter.
func (s *SignerList) EmitFinalFields(out map[string]any) {
	s.emitAll(out, false)
}

// EmitPreviousFields emits the original values of fields that changed
// between prev and the receiver (sMD_ChangeOrig — MetaDefault only).
func (s *SignerList) EmitPreviousFields(prev Entry, out map[string]any) {
	prv, ok := prev.(*SignerList)
	if !ok || prv == nil {
		return
	}
	emitIfChangedString(out, "Owner", prv.Owner, s.Owner, prv.present&signerlistBitOwner, s.present&signerlistBitOwner)
	emitIfChangedString(out, "OwnerNode", prv.OwnerNode, s.OwnerNode, prv.present&signerlistBitOwnerNode, s.present&signerlistBitOwnerNode)
	emitIfChangedUint32(out, "SignerQuorum", prv.SignerQuorum, s.SignerQuorum, prv.present&signerlistBitSignerQuorum, s.present&signerlistBitSignerQuorum)
	emitIfChangedDeep(out, "SignerEntries", prv.SignerEntries, s.SignerEntries, prv.present&signerlistBitSignerEntries, s.present&signerlistBitSignerEntries)
	emitIfChangedUint32(out, "SignerListID", prv.SignerListID, s.SignerListID, prv.present&signerlistBitSignerListID, s.present&signerlistBitSignerListID)
	emitIfChangedUint32(out, "Flags", prv.Flags, s.Flags, prv.present&signerlistBitFlags, s.present&signerlistBitFlags)
	emitIfChangedString(out, "Sponsor", prv.Sponsor, s.Sponsor, prv.present&signerlistBitSponsor, s.present&signerlistBitSponsor)
}

// EmitChangeOrigFields writes the names of every present field carrying
// sMD_ChangeOrig (MetaDefault). The empty-PreviousFields heuristic uses
// this to scope its orig-vs-cur presence comparison so MetaAlways fields
// (which appear in FinalFields but lack sMD_ChangeOrig at the rippled
// level) cannot trip a spurious STI_NOTPRESENT emission.
func (s *SignerList) EmitChangeOrigFields(out map[string]any) {
	if s.present&signerlistBitOwner != 0 {
		out["Owner"] = s.Owner
	}
	if s.present&signerlistBitOwnerNode != 0 {
		out["OwnerNode"] = s.OwnerNode
	}
	if s.present&signerlistBitSignerQuorum != 0 {
		out["SignerQuorum"] = s.SignerQuorum
	}
	if s.present&signerlistBitSignerEntries != 0 {
		out["SignerEntries"] = s.SignerEntries
	}
	if s.present&signerlistBitSignerListID != 0 {
		out["SignerListID"] = s.SignerListID
	}
	if s.present&signerlistBitFlags != 0 {
		out["Flags"] = s.Flags
	}
	if s.present&signerlistBitSponsor != 0 {
		out["Sponsor"] = s.Sponsor
	}
}

// EmitDeleteFinalFields emits fields for DeletedNode.FinalFields
// (sMD_Always | sMD_DeleteFinal), including PreviousTxn* which are
// otherwise hidden.
func (s *SignerList) EmitDeleteFinalFields(out map[string]any) {
	s.emitAll(out, false)
	if s.present&signerlistBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = s.PreviousTxnID
	}
	if s.present&signerlistBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = s.PreviousTxnLgrSeq
	}
}

func (s *SignerList) EmitDeletePreviousFields(prev Entry, out map[string]any) {
	s.EmitPreviousFields(prev, out)
}

// PreviousTxn returns the threading values from the receiver. Empty id /
// zero seq mean the corresponding field is absent.
func (s *SignerList) PreviousTxn() (string, uint32) {
	var id string
	var seq uint32
	if s.present&signerlistBitPreviousTxnID != 0 {
		id = s.PreviousTxnID
	}
	if s.present&signerlistBitPreviousTxnLgrSeq != 0 {
		seq = s.PreviousTxnLgrSeq
	}
	return id, seq
}

// ToMap returns the canonical JSON-map representation of the receiver,
// suitable for binarycodec.EncodeBytes. Includes every present field —
// metadata-excluded fields (sMD_Never) too — plus the LedgerEntryType
// header that every SLE blob carries.
func (s *SignerList) ToMap() map[string]any {
	out := map[string]any{
		"LedgerEntryType": "SignerList",
	}
	if s.present&signerlistBitOwner != 0 {
		out["Owner"] = s.Owner
	}
	if s.present&signerlistBitOwnerNode != 0 {
		out["OwnerNode"] = s.OwnerNode
	}
	if s.present&signerlistBitSignerQuorum != 0 {
		out["SignerQuorum"] = s.SignerQuorum
	}
	if s.present&signerlistBitSignerEntries != 0 {
		out["SignerEntries"] = s.SignerEntries
	}
	if s.present&signerlistBitSignerListID != 0 {
		out["SignerListID"] = s.SignerListID
	}
	if s.present&signerlistBitFlags != 0 {
		out["Flags"] = s.Flags
	}
	if s.present&signerlistBitPreviousTxnID != 0 {
		out["PreviousTxnID"] = s.PreviousTxnID
	}
	if s.present&signerlistBitPreviousTxnLgrSeq != 0 {
		out["PreviousTxnLgrSeq"] = s.PreviousTxnLgrSeq
	}
	if s.present&signerlistBitSponsor != 0 {
		out["Sponsor"] = s.Sponsor
	}
	return out
}

// Encode serializes the receiver to canonical XRPL binary. Legacy decode
// aliases and non-canonical input ordering are emitted in canonical form.
func (s *SignerList) Encode() ([]byte, error) {
	if err := s.validateRequired(); err != nil {
		return nil, err
	}
	if s.present&signerlistBitSignerEntries != 0 {
		if err := validateSTArrayForEncode("SignerEntries", s.SignerEntries); err != nil {
			return nil, err
		}
	}
	out := s.ToMap()
	if s.present&signerlistBitPreviousTxnID == 0 {
		out["PreviousTxnID"] = "0000000000000000000000000000000000000000000000000000000000000000"
	}
	if s.present&signerlistBitPreviousTxnLgrSeq == 0 {
		out["PreviousTxnLgrSeq"] = uint32(0)
	}
	return binarycodec.EncodeBytes(out)
}

// Hash returns the SHAMap account-state leaf hash for this entry,
// sha512Half(HashPrefixLeafNode || encoded || index). index is the
// 32-byte keylet under which the entry is stored.
func (s *SignerList) Hash(index [32]byte) ([32]byte, error) {
	data, err := s.Encode()
	if err != nil {
		return [32]byte{}, err
	}
	prefix := protocol.HashPrefixLeafNode()
	return sha512half.Sum(prefix[:], data, index[:]), nil
}
